//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  G:\UG智辉钣金插件_源码精简_20260605_最终精简\features\35_QinLiGuanJian\QinLiGuanJian.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Administrator
//              Version: NX 2412
//              Date: 06-29-2026  (Format: mm-dd-yyyy)
//              Time: 16:02
//
//==============================================================================

#ifndef QINLIGUANJIAN_H_INCLUDED
#define QINLIGUANJIAN_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <vector>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_FaceCollector.hxx>

namespace NXOpen
{
class Face;
}

//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                          EntityType_AllowFaces (1 << 4);
#define                         EntityType_AllowDatums (1 << 5);
#define                         EntityType_AllowBodies (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: FaceRules
//------------------------------------------------------------------------------
#define                           FaceRules_SingleFace (1 << 0);
#define                          FaceRules_RegionFaces (1 << 1);
#define                         FaceRules_TangentFaces (1 << 2);
#define                   FaceRules_TangentRegionFaces (1 << 3);
#define                            FaceRules_BodyFaces (1 << 4);
#define                         FaceRules_FeatureFaces (1 << 5);
#define                        FaceRules_AdjacentFaces (1 << 6);
#define                  FaceRules_ConnectedBlendFaces (1 << 7);
#define                        FaceRules_AllBlendFaces (1 << 8);
#define                             FaceRules_RibFaces (1 << 9);
#define                            FaceRules_SlotFaces (1 <<10);
#define                   FaceRules_BossandPocketFaces (1 <<11);
#define                       FaceRules_MergedRibFaces (1 <<12);
#define                  FaceRules_RegionBoundaryFaces (1 <<13);
#define                 FaceRules_FaceandAdjacentFaces (1 <<14);
#define                            FaceRules_HoleFaces (1 <<15);
#define                                FaceRules_曲率横截面 (1 <<16);
#define                                FaceRules_漫水填充面 (1 <<17);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport QinLiGuanJian
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    QinLiGuanJian();
    ~QinLiGuanJian();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the QinLiGuanJian.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    void SetTypeSelection(int selectedType);
    void SetButtonBitmap(NXOpen::BlockStyler::Button* button, const char* bitmapName);
    void ProcessSelectedFacePreview();
    void ConfigureFaceCollector();
    void KeepOnlySelectedFace(NXOpen::Face* selectedFace);
    void ClearHighlightedFaces();
    void HighlightFaces(const std::vector<tag_t>& faceTags);
    void RefreshFinalDisplay(tag_t finalBodyTag);
    NXOpen::Face* JoinSelectedBodyFacesOnSameSurface(NXOpen::Face* selectedFace);
    std::vector<tag_t> FindEndFacesFromSelectedFace(NXOpen::Face* selectedFace);
    std::vector<tag_t> ExtractEndFacesAsFaceChain(const std::vector<tag_t>& faceTags);
    NXOpen::Face* FindSquareTubeInnerFace(NXOpen::Face* selectedFace);
    NXOpen::Face* FindRoundTubeInnerFace(NXOpen::Face* selectedFace);
    NXOpen::Face* FindMatchingOuterFaceOnBody(tag_t bodyTag, NXOpen::Face* referenceFace);
    tag_t CleanUpSquareTubeWithInnerFace(NXOpen::Face* innerFace);
    tag_t TrimBodyWithExtractedSheets(tag_t targetBodyTag, const std::vector<tag_t>& toolBodyTags);
    tag_t ApplySharpCornerBoundingSubtract(
        tag_t finalBodyTag,
        NXOpen::Face* squareTubeFace,
        const std::vector<tag_t>& originalEndFaces,
        std::vector<tag_t>& intermediateBodyTags);
    void DeleteIntermediateBodies(tag_t originalBodyTag, tag_t finalBodyTag, const std::vector<tag_t>& bodyTags);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    NXOpen::BlockStyler::Button* button01;// Block type: Button
    NXOpen::BlockStyler::FaceCollector* face_select0;// Block type: Face Collector
    int selectedMode;
    std::vector<tag_t> highlightedFaceTags;
    
};
#endif //QINLIGUANJIAN_H_INCLUDED
