//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\LPOpenPrint\application\ZiDonCuTu.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: 22738
//              Version: NX 1973
//              Date: 08-23-2021  (Format: mm-dd-yyyy)
//              Time: 22:33
//
//==============================================================================

#ifndef ZIDONCUTU_H_INCLUDED
#define ZIDONCUTU_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_IntegerBlock.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_StringBlock.hxx>
#include <NXOpen/BlockStyler_SelectObject.hxx>
#include <NXOpen/BlockStyler_SpecifyPoint.hxx>
#include <uf_draw.h>
#include <uf_obj.h>
#include <uf_view.h>
#include <NXOpen/Annotations_DimensionCollection.hxx>
#include <NXOpen/SelectDisplayableObject.hxx>
#include <NXOpen/NXObjectManager.hxx>
#include <uf_eval.h>
#include <NXOpen/ListingWindow.hxx>
#include <uf_ui.h>
#include <uf.h>
#include <NXOpen/Annotations_AnnotationManager.hxx>
#include <NXOpen/Annotations_IntersectionSymbolBuilder.hxx>
#include <NXOpen/Annotations_IntersectionSymbolCollection.hxx>
#include <NXOpen/ColorManager.hxx>
#include <NXOpen/ViewCollection.hxx>
#include <NXOpen/Annotations_IntersectionSymbol.hxx>
#include <NXOpen/MeasureDistance.hxx>
#include <NXOpen/MeasureDistanceBuilder.hxx>
#include <NXOpen/MeasureManager.hxx>
#include <NXOpen/ScRuleFactory.hxx>
#include <uf_modl.h>
#include <NXOpen/ScCollectorCollection.hxx>
#include <NXOpen/FaceTangentRule.hxx>
#include <NXOpen/edge.hxx>
#include <NXOpen/MeasureAngle.hxx>
#include <vector>

// Internal+External Includes
#include <NXOpen/Annotations.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/BodyCollection.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Line.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>

// Std C++ Includes
#include <sstream>
#include <NXOpen/Plane.hxx>
#include <NXOpen/PlaneCollection.hxx>
#include <NXOpen/DirectionCollection.hxx>
#include <NXOpen/Point.hxx>
#include <NXOpen/PointCollection.hxx>
#include <NXOpen/Scalar.hxx>
#include <NXOpen/ScalarCollection.hxx>
#include <NXOpen/Xform.hxx>
#include <NXOpen/XformCollection.hxx>
#include <NXOpen/CoordinateSystemCollection.hxx>
#include <NXOpen/CoordinateSystem.hxx>
#include <NXOpen/WCS.hxx>
#include <NXOpen/NXMatrix.hxx>
#include <NXOpen/ModelingView.hxx>
#include <NXOpen/ModelingViewCollection.hxx>
#include <NXOpen/CartesianCoordinateSystem.hxx>

#include <NXOpen/View.hxx>
#include <NXOpen/Layout.hxx>
#include <NXOpen/LayoutCollection.hxx>
#include <NXOpen/Drafting_PreferencesBuilder.hxx>
#include <NXOpen/Drafting_SettingsManager.hxx>
#include <NXOpen/Drawings_BaseView.hxx>
#include <NXOpen/Drawings_DraftingBody.hxx>
#include <NXOpen/Drawings_DraftingBodyCollection.hxx>
#include <NXOpen/Drawings_DraftingCurve.hxx>
#include <NXOpen/Drawings_DraftingCurveCollection.hxx>
#include <NXOpen/Drawings_DraftingView.hxx>
#include <NXOpen/Drawings_DraftingViewCollection.hxx>
#include <NXOpen/Drawings_SelectDraftingView.hxx>
#include <NXOpen/DraftingManager.hxx>
#include <NXOpen/Drawings_DraftingDrawingSheetBuilder.hxx>
#include <NXOpen/Drawings_DraftingDrawingSheetCollection.hxx>
#include <NXOpen/Drawings_DraftingDrawingSheet.hxx>
#include <NXOpen/Drawings_DrawingSheetBuilder.hxx>
#include <NXOpen/Drawings_ViewPlacementBuilder.hxx>
#include <NXOpen/SelectNXObject.hxx>
#include <NXOpen/Layer_LayerManager.hxx>
#include <NXOpen/Drawings_DrawingSheetCollection.hxx>
#include <NXOpen/Annotations_Label.hxx>
#include <NXOpen/Annotations_LabelCollection.hxx>
#include <string>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/Features_SheetMetal_SheetmetalManager.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/EdgeBoundaryRule.hxx>
#include <NXOpen/Features_FlatPattern.hxx>
#include <NXOpen/Features_Feature.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_SheetMetal_CornerTreatmentBuilder.hxx>
#include <NXOpen/Features_SheetMetal_FlatPatternBuilder.hxx>
#include <NXOpen/Features_SheetMetal_HoleTreatmentBuilder.hxx>
#include <NXOpen/SelectFace.hxx>
#include <NXOpen/SelectEdge.hxx>
#include <NXOpen/AttributeManager.hxx>
#include <NXOpen/AttributePropertiesBaseBuilder.hxx>
#include <NXOpen/AttributePropertiesBuilder.hxx>
#include <NXOpen/Annotations_Annotation.hxx>
#include <NXOpen/Annotations_Note.hxx>
#include <NXOpen/Features_ConvertToSheetmetal.hxx>
#include <NXOpen/Assemblies_Component.hxx>
#include <NXOpen/Assemblies_ComponentAssembly.hxx>

//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesEnabled
//------------------------------------------------------------------------------
#define              SnapPointTypesEnabled_UserDefined (1 << 0);
#define                 SnapPointTypesEnabled_Inferred (1 << 1);
#define           SnapPointTypesEnabled_ScreenPosition (1 << 2);
#define                 SnapPointTypesEnabled_EndPoint (1 << 3);
#define                 SnapPointTypesEnabled_MidPoint (1 << 4);
#define             SnapPointTypesEnabled_ControlPoint (1 << 5);
#define             SnapPointTypesEnabled_Intersection (1 << 6);
#define                SnapPointTypesEnabled_ArcCenter (1 << 7);
#define            SnapPointTypesEnabled_QuadrantPoint (1 << 8);
#define            SnapPointTypesEnabled_ExistingPoint (1 << 9);
#define             SnapPointTypesEnabled_PointonCurve (1 <<10);
#define           SnapPointTypesEnabled_PointonSurface (1 <<11);
#define         SnapPointTypesEnabled_PointConstructor (1 <<12);
#define     SnapPointTypesEnabled_TwocurveIntersection (1 <<13);
#define             SnapPointTypesEnabled_TangentPoint (1 <<14);
#define                    SnapPointTypesEnabled_Poles (1 <<15);
#define         SnapPointTypesEnabled_BoundedGridPoint (1 <<16);
#define         SnapPointTypesEnabled_FacetVertexPoint (1 <<17);
#define            SnapPointTypesEnabled_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define             SnapPointTypesOnByDefault_EndPoint (1 << 3);
#define             SnapPointTypesOnByDefault_MidPoint (1 << 4);
#define         SnapPointTypesOnByDefault_ControlPoint (1 << 5);
#define         SnapPointTypesOnByDefault_Intersection (1 << 6);
#define            SnapPointTypesOnByDefault_ArcCenter (1 << 7);
#define        SnapPointTypesOnByDefault_QuadrantPoint (1 << 8);
#define        SnapPointTypesOnByDefault_ExistingPoint (1 << 9);
#define         SnapPointTypesOnByDefault_PointonCurve (1 <<10);
#define       SnapPointTypesOnByDefault_PointonSurface (1 <<11);
#define     SnapPointTypesOnByDefault_PointConstructor (1 <<12);
#define     SnapPointTypesOnByDefault_BoundedGridPoint (1 <<16);
#define     SnapPointTypesOnByDefault_FacetVertexPoint (1 <<17);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define          SnapPointTypesOnByDefault_UserDefined (1 << 0);
#define             SnapPointTypesOnByDefault_Inferred (1 << 1);
#define       SnapPointTypesOnByDefault_ScreenPosition (1 << 2);
#define SnapPointTypesOnByDefault_TwocurveIntersection (1 <<13);
#define         SnapPointTypesOnByDefault_TangentPoint (1 <<14);
#define                SnapPointTypesOnByDefault_Poles (1 <<15);
#define        SnapPointTypesOnByDefault_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

extern NXOpen::Session* theSession;
extern NXOpen::Part* workPart;
extern NXOpen::Part* displayPart;
extern NXString StrZKname;
extern double doubleX;
extern double doubleY;
extern double Scale1A;
extern std::vector<Drawings::BaseView*> BaseViewvector;
extern double douXmax, douYmax;
extern double viewscale;
extern NXOpen::NXObject* ObjSheet;
extern NXOpen::NXObject* ObjZuoView;
extern NXOpen::NXObject* ObjXiaView;
extern NXOpen::NXObject* ObZanKaiView;
extern NXOpen::NXObject* Zen3DView;
extern double numerator, SheelScale, SheelScale1;
extern bool g_hasAutoPlacementOverride;
extern NXOpen::Point3d g_autoPlacementPoint;
extern bool g_hasPageScaleOverride;
extern double g_pageScaleOverride;
extern bool g_deferPageLayout;
extern bool g_reuseExistingViews;

extern NXOpen::Drawings::DrawingSheet* WorkSheet;
//double Scale1A;

class DllExport ZiDonCuTu
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    ZiDonCuTu();
    ~ZiDonCuTu();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();

    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the ZiDonCuTu.cpp file.
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    void UF_MODL_ask_edge_is_outer_boundary(NXOpen::Face* face1, std::vector<Edge*> &AllEdge);
    int Create_Draft_Not(NXOpen::Body* body1, Point3d notPoint3d, Drawings::BaseView* BaseView1A);
    int apply_cb();
    int ok_cb();
    int aaaa_cb();
    int aabb_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    int filter_cb(NXOpen::BlockStyler::UIBlock* block, NXOpen::TaggedObject* selectedObject);
    PropertyList* GetBlockProperties(const char *blockID);

private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Enumeration* enumDrawingMode;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enumSheetLayout;// Block type: Enumeration
    NXOpen::BlockStyler::IntegerBlock* integerSheetPartCount;// Block type: Integer
    NXOpen::BlockStyler::Toggle* toggle0;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle01;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggleHoleCoordinate;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggleHoleAttribute;// Block type: Toggle
    NXOpen::BlockStyler::StringBlock* stringHoleMarker;// Block type: String
    NXOpen::BlockStyler::DoubleBlock* doubleRInnerThreshold;// Block type: Double
    NXOpen::BlockStyler::Button* buttonNoteFormatConfig;// Block type: Button
    NXOpen::BlockStyler::Enumeration* enum01;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enumProjection;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum0;// Block type: Enumeration
    NXOpen::BlockStyler::SelectObject* selection0;// Block type: Selection
    NXOpen::BlockStyler::SpecifyPoint* point0;// Block type: Specify Point

};
#endif //ZIDONCUTU_H_INCLUDED
