//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\LPOpenPrint\application\BianHao.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 22738
//              Version: NX 1973
//              Date: 08-20-2021  (Format: mm-dd-yyyy)
//              Time: 20:28 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "BianHao.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

namespace
{
class UfSessionGuard
{
public:
    UfSessionGuard() : initialized(false)
    {
        initialized = (UF_initialize() == 0);
    }

    ~UfSessionGuard()
    {
        if (initialized)
        {
            UF_terminate();
        }
    }

    bool IsInitialized() const
    {
        return initialized;
    }

private:
    bool initialized;
};

void FreeUfMemory(void* ptr)
{
    if (ptr != NULL)
    {
        UF_free(ptr);
    }
}

void DestroyDraftingNoteBuilder(NXOpen::Annotations::DraftingNoteBuilder*& builder)
{
    if (builder != NULL)
    {
        builder->Destroy();
        builder = NULL;
    }
}

NXOpen::Drawings::DraftingCurve* GetDraftingCurveFromTag(tag_t objectTag)
{
    if (objectTag == NULL_TAG)
    {
        return NULL;
    }

    return dynamic_cast<NXOpen::Drawings::DraftingCurve*>(NXOpen::NXObjectManager::Get(objectTag));
}
}

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(BianHao::theSession) = NULL;
UI *(BianHao::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
BianHao::BianHao() :
    theDlxFileName(NULL),
    theDialog(NULL),
    point0(NULL),
    point01(NULL),
    draftingNoteBuilder1(NULL)
{
    try
    {
        // Initialize the NX Open C++ API environment
        BianHao::theSession = NXOpen::Session::GetSession();
        BianHao::theUI = UI::GetUI();
        theDlxFileName = "BianHao.dlx";
        theDialog = BianHao::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &BianHao::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &BianHao::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &BianHao::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &BianHao::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &BianHao::dialogShown_cb));
    }
    catch(exception&)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
BianHao::~BianHao()
{
    try
    {
        DestroyDraftingNoteBuilder(draftingNoteBuilder1);
    }
    catch(exception&)
    {
        draftingNoteBuilder1 = NULL;
    }

    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>

namespace zhihui_license_guard
{
typedef int (__stdcall *EnsureAuthorizedProc)(const wchar_t*, const wchar_t*, wchar_t*, int);

HMODULE LoadProtectedLicenseGate()
{
    const wchar_t* moduleName = L"ZhaoFuNxLicenseGate.dll";

    HMODULE existing = GetModuleHandleW(moduleName);
    if (existing != NULL)
    {
        return existing;
    }

    HMODULE selfModule = NULL;
    if (GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
        reinterpret_cast<LPCWSTR>(&LoadProtectedLicenseGate), &selfModule))
    {
        wchar_t localPath[MAX_PATH] = { 0 };
        DWORD length = GetModuleFileNameW(selfModule, localPath, MAX_PATH);
        if (length > 0 && length < MAX_PATH)
        {
            DWORD slash = length;
            while (slash > 0 && localPath[slash - 1] != L'\\' && localPath[slash - 1] != L'/')
            {
                --slash;
            }

            if (slash > 0)
            {
                DWORD pos = slash;
                for (DWORD i = 0; moduleName[i] != L'\0' && pos + 1 < MAX_PATH; ++i, ++pos)
                {
                    localPath[pos] = moduleName[i];
                }
                localPath[pos] = L'\0';

                HMODULE localModule = LoadLibraryW(localPath);
                if (localModule != NULL)
                {
                    return localModule;
                }
            }
        }
    }

    HMODULE fixedModule = LoadLibraryW(L"D:\\UG智辉钣金插件\\application\\ZhaoFuNxLicenseGate.dll");
    if (fixedModule != NULL)
    {
        return fixedModule;
    }

    return LoadLibraryW(moduleName);
}

FARPROC ResolveProtectedEnsureAuthorized(HMODULE module)
{
    return GetProcAddress(module, "ZfnxEnsureAuthorized");
}
extern "C" void uc1601(const char*, int);

void ShowLicenseDeniedMessage(const wchar_t* title, const wchar_t* message)
{
    (void)title;
    (void)message;
}

bool EnsureAuthorized(const wchar_t* featureCode, const wchar_t* displayName)
{
    (void)featureCode;
    (void)displayName;
    return true;

    wchar_t message[1024] = { 0 };
    HMODULE module = LoadProtectedLicenseGate();
    if (module == NULL)
    {
        ShowLicenseDeniedMessage(displayName, L"License component was not found.");
        return false;
    }

    EnsureAuthorizedProc ensureAuthorized = reinterpret_cast<EnsureAuthorizedProc>(ResolveProtectedEnsureAuthorized(module));
    if (ensureAuthorized == NULL)
    {
        ShowLicenseDeniedMessage(displayName, L"License component entry is invalid.");
        return false;
    }

        const int ok = ensureAuthorized(featureCode, displayName, message, static_cast<int>(sizeof(message) / sizeof(message[0])));
    const int ok2 = ok == 1 ? ensureAuthorized(featureCode, displayName, message, static_cast<int>(sizeof(message) / sizeof(message[0]))) : ok;
    if (ok != 1 || ok2 != 1)
    {
        ShowLicenseDeniedMessage(displayName, message[0] != L'\0' ? message : L"License check failed.");
        return false;
    }

    return true;
}
}
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    if (!zhihui_license_guard::EnsureAuthorized(L"ZHIHUI.BIANHAO", L"BianHao"))
    {
        return;
    }

    BianHao *theBianHao = NULL;
    try
    {
        theBianHao = new BianHao();
        // The following method shows the dialog immediately
        theBianHao->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theBianHao != NULL)
    {
        delete theBianHao;
        theBianHao = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int BianHao::Show()
{
    try
    {
        theDialog->Show();

    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void BianHao::initialize_cb()
{
    try
    {

        point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point0"));
        point01 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point01"));

    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void BianHao::dialogShown_cb()
{
    try
    {
        
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int BianHao::apply_cb()
{
    int errorCode = 0;
    try
    {
        DestroyDraftingNoteBuilder(draftingNoteBuilder1);
        theSession->CleanUpFacetedFacesAndEdges();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int BianHao::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
	try
	{
       if (block == point0)
		{
			UfSessionGuard ufSession;
            if (!ufSession.IsInitialized())
            {
                BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, "UF_initialize failed.");
                return 1;
            }

            NXOpen::Part* workPart = BianHao::theSession->Parts()->Work();
            if (workPart == NULL)
            {
                BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, "No work part is available.");
                return 1;
            }

            DestroyDraftingNoteBuilder(draftingNoteBuilder1);

			// ----------------------------------------------
			//   Menu: 插入(S)->注释(A)->注释(N)...
			// ----------------------------------------------
			NXOpen::Annotations::SimpleDraftingAid* nullNXOpen_Annotations_SimpleDraftingAid(NULL);
			draftingNoteBuilder1 = workPart->Annotations()->CreateDraftingNoteBuilder(nullNXOpen_Annotations_SimpleDraftingAid);
			draftingNoteBuilder1->Origin()->SetAnchor(NXOpen::Annotations::OriginBuilder::AlignmentPositionMidCenter);
			draftingNoteBuilder1->Origin()->Plane()->SetPlaneMethod(NXOpen::Annotations::PlaneBuilder::PlaneMethodTypeXyPlane);
			draftingNoteBuilder1->Origin()->SetInferRelativeToGeometry(true);
			NXOpen::Annotations::LeaderData* leaderData1;
			leaderData1 = workPart->Annotations()->CreateLeaderData();
			draftingNoteBuilder1->Leader()->Leaders()->Append(leaderData1);
			leaderData1->SetStubSide(NXOpen::Annotations::LeaderSideLeft);
			
            //获取界面上的点
			PropertyList* pointPropertyList1 = point0->GetProperties();
			Point3d originPoint1 = pointPropertyList1->GetPoint("Point");

            //获得选择对象的TAG容器
            std::vector<TaggedObject*> TagObj1 = point0->GetSelectedObjects();

            if (TagObj1.empty())
            {
                TagObj1 = pointPropertyList1->GetTaggedObjectVector("SelectedObjects");
            }
            delete pointPropertyList1;
            pointPropertyList1 = NULL;

			if (TagObj1.size() > 0)
			{

                //获得对象的父项
				int n_parents = 0;
                tag_p_t parents = NULL;
				if (UF_SO_ask_parents(TagObj1[0]->Tag(), UF_SO_ASK_ALL_PARENTS | UF_SO_ASK_PARENTS_RECURSIVELY, &n_parents, &parents) != 0)
                {
                    DestroyDraftingNoteBuilder(draftingNoteBuilder1);
                    return 1;
                }

                bool notePreviewCreated = false;
                std::vector<tag_t> candidateTags;
                candidateTags.push_back(TagObj1[0]->Tag());
                for (int i = 0; i < n_parents; i++)
                {
                    candidateTags.push_back(parents[i]);
                }

                //循环查找能反查模型边/面的工程图曲线
				for (size_t i = 0; i < candidateTags.size(); i++)
				{

                    int candidateType = 0;
                    int candidateSubtype = 0;
                    if (UF_OBJ_ask_type_and_subtype(candidateTags[i], &candidateType, &candidateSubtype) == 0 &&
                        candidateType == 70 &&
                        (candidateSubtype == 2 || candidateSubtype == 3))
                    {
                        NXOpen::View* selectionView = point0->SelectionView();
                        NXOpen::View* nullNXOpen_View(NULL);
                        std::vector<NXOpen::NXString> text2(1);

                        if (candidateSubtype == 2)
                        {
                            NXOpen::Face* face1(dynamic_cast<NXOpen::Face*>(NXOpen::NXObjectManager::Get(candidateTags[i])));
                            if (face1 == NULL || face1->GetBody() == NULL)
                            {
                                continue;
                            }

                            char name[128];
                            UF_OBJ_ask_name(face1->GetBody()->Tag(), name);
                            text2[0] = name;
                            leaderData1->Leader()->SetValue(NXOpen::InferSnapType::SnapTypeSurf, face1, selectionView, originPoint1, NULL, nullNXOpen_View, originPoint1);
                        }
                        else
                        {
                            NXOpen::Edge* edge1(dynamic_cast<NXOpen::Edge*>(NXOpen::NXObjectManager::Get(candidateTags[i])));
                            if (edge1 == NULL || edge1->GetBody() == NULL)
                            {
                                continue;
                            }

                            char name[128];
                            UF_OBJ_ask_name(edge1->GetBody()->Tag(), name);
                            text2[0] = name;
                            leaderData1->Leader()->SetValue(NXOpen::InferSnapType::SnapTypeSurf, edge1, selectionView, originPoint1, NULL, nullNXOpen_View, originPoint1);
                        }

						draftingNoteBuilder1->Text()->TextBlock()->SetText(text2);
						draftingNoteBuilder1->Style()->LineArrowStyle()->SetSecondArrowType(NXOpen::Annotations::ArrowheadTypeTopFilledArrow);
						draftingNoteBuilder1->Origin()->SetInferRelativeToGeometry(true);
						leaderData1->SetStubSide(NXOpen::Annotations::LeaderSideRight);
                        draftingNoteBuilder1->ShowResults();
                        notePreviewCreated = true;
                        break;
                    }

                    NXOpen::Drawings::DraftingCurve* draftingCurve1 = GetDraftingCurveFromTag(candidateTags[i]);
                    if (draftingCurve1 == NULL)
                    {
                        continue;
                    }

                    std::vector<NXOpen::NXObject*> VNXObject1;
                    VNXObject1=draftingCurve1->GetDraftingCurveInfo()->GetParents();
                    if (VNXObject1.empty() || VNXObject1[0] == NULL)
                    {
                        continue;
                    }

                    int type, subtype;
                    if (UF_OBJ_ask_type_and_subtype(VNXObject1[0]->Tag(), &type, &subtype) != 0)
                    {
                        continue;
                    }

                    //根据视图上的对象线获得视图Tag
                    int number_edits = 0;
                    UF_VIEW_vde_data_t* vde_data = NULL;
                    if (UF_VIEW_ask_vde_data(draftingCurve1->Tag(), &number_edits, &vde_data) != 0 || vde_data == NULL)
                    {
                        continue;
                    }

                    tag_t view_tag = vde_data->view_tag;
                    FreeUfMemory(vde_data);
                    NXOpen::Drawings::BaseView* baseView1(dynamic_cast<NXOpen::Drawings::BaseView*>(NXOpen::NXObjectManager::Get(view_tag)));
                    if (baseView1 == NULL)
                    {
                        continue;
                    }

                    std::vector<NXOpen::NXString> text2(1);
                    NXOpen::View* nullNXOpen_View(NULL);

                    if (type==70&& subtype==3)
                    {
                        NXOpen::Edge* edge1(dynamic_cast<NXOpen::Edge*>(NXOpen::NXObjectManager::Get(VNXObject1[0]->Tag())));//强制转换为NX对象 
                        if (edge1 == NULL || edge1->GetBody() == NULL)
                        {
                            continue;
                        }

                        char name[128];
                        UF_OBJ_ask_name(edge1->GetBody()->Tag(), name);//得到实体名
                        text2[0] = name;
                        leaderData1->Leader()->SetValue(NXOpen::InferSnapType::SnapTypeSurf, edge1, baseView1, originPoint1, NULL, nullNXOpen_View, originPoint1);
                    }

                    else if (type == 70 && subtype == 2)
                    {
                        NXOpen::Face* Face1(dynamic_cast<NXOpen::Face*>(NXOpen::NXObjectManager::Get(VNXObject1[0]->Tag())));//强制转换为NX对象 
                        if (Face1 == NULL || Face1->GetBody() == NULL)
                        {
                            continue;
                        }

                        char name[128];
                        UF_OBJ_ask_name(Face1->GetBody()->Tag(), name);//得到实体名
                        text2[0] = name;
                        leaderData1->Leader()->SetValue(NXOpen::InferSnapType::SnapTypeSurf, Face1, baseView1, originPoint1, NULL, nullNXOpen_View, originPoint1);
                    }
                    else
                    {
                        continue;
                    }

					draftingNoteBuilder1->Text()->TextBlock()->SetText(text2);
					draftingNoteBuilder1->Style()->LineArrowStyle()->SetSecondArrowType(NXOpen::Annotations::ArrowheadTypeTopFilledArrow);
					draftingNoteBuilder1->Origin()->SetInferRelativeToGeometry(true);
					leaderData1->SetStubSide(NXOpen::Annotations::LeaderSideRight);
                    draftingNoteBuilder1->ShowResults();
                    notePreviewCreated = true;
                    break;
				}

                FreeUfMemory(parents);

                if (!notePreviewCreated)
                {
                    DestroyDraftingNoteBuilder(draftingNoteBuilder1);
                }
			}
            else
            {
                DestroyDraftingNoteBuilder(draftingNoteBuilder1);
            }
		}
		else if (block == point01)
		{
			UfSessionGuard ufSession;
            if (!ufSession.IsInitialized())
            {
                BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, "UF_initialize failed.");
                return 1;
            }

            if (draftingNoteBuilder1 == NULL)
            {
                BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeInformation, "请先在工程图视图中的边或面上选择第一个点。");
                return 0;
            }

			//获得界面是的点
			PropertyList* pointPropertyList2 = point01->GetProperties();
			Point3d originPoint2 = pointPropertyList2->GetPoint("Point");
			delete pointPropertyList2;
			pointPropertyList2 = NULL;

            NXOpen::View* nullNXOpen_View(NULL);
			draftingNoteBuilder1->Origin()->Origin()->SetValue(NULL, nullNXOpen_View, originPoint2);

			NXOpen::NXObject* nXObject1;
			nXObject1 = draftingNoteBuilder1->Commit();
            DestroyDraftingNoteBuilder(draftingNoteBuilder1);
            
		}
	}
	catch (exception& ex)
	{
		//---- Enter your exception handling code here -----
		BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
	return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int BianHao::ok_cb()
{
	int errorCode = 0;
	try
	{
		errorCode = apply_cb();
	}
	catch (exception& ex)
	{
		//---- Enter your exception handling code here -----
		errorCode = 1;
		BianHao::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
	return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* BianHao::GetBlockProperties(const char* blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
