// Exercises native expression updates in an isolated external NX process.
#include <iostream>
#include "../StandardPartsLibrary.cpp"

void RequireParam(bool value,const char* message)
{ if(!value) throw std::runtime_error(message); }

std::string Bytes(const fs::path& path)
{ std::ifstream input(path,std::ios::binary); return {std::istreambuf_iterator<char>(input),{}}; }

int wmain(int argc,wchar_t** argv)
{
    // Read-only check of the model generated by the native insertion UI.
    if(argc==3 && std::wstring(argv[1])==L"--verify-model3")
    {
        bool active=false;
        try
        {
            CheckPreviewUf(UF_initialize());active=true;
            tag_t part=NULL_TAG,body=NULL_TAG;UF_PART_load_status_t status{};
            const auto path=fs::absolute(argv[2]);const auto before=Bytes(path);
            const int code=UF_PART_open_quiet(ToAnsi(path.wstring()).c_str(),&part,&status);
            UF_PART_free_load_status(&status);CheckPreviewUf(code);
            CheckPreviewUf(UF_OBJ_cycle_objs_in_part(part,UF_solid_type,&body));
            RequireParam(body!=NULL_TAG,"UI-generated model contains a body");
            double box[6]{};CheckPreviewUf(UF_MODL_ask_bounding_box(body,box));
            std::vector<double> size={box[3]-box[0],box[4]-box[1],box[5]-box[2]};std::sort(size.begin(),size.end());
            RequireParam(std::abs(size[0]-20)<1e-4&&std::abs(size[1]-30)<1e-4&&std::abs(size[2]-80)<1e-4,"UI-generated model3 solid must be 80 x 30 x 20");
            CheckPreviewUf(UF_PART_close(part,0,1));RequireParam(Bytes(path)==before,"Read-only model verification preserves PRT bytes");
            UF_terminate();std::cout<<"PASS native insertion UI generated model3: exact solid 80 x 30 x 20; read-only verification\n";return 0;
        }
        catch(const std::exception& ex){std::cerr<<"FAIL: "<<ex.what()<<"\n";}
        if(active)UF_terminate();return 1;
    }
    if((argc!=3&&argc!=4) || fs::exists(argv[1])) {std::cerr<<"Supply new test root, M6 socket family, optional M6 flat family\n"; return 2;}
    bool initialized=false; HWND controls=nullptr;
    try
    {
        CheckPreviewUf(UF_initialize()); initialized=true;
        const auto root=fs::absolute(argv[1]); fs::create_directories(root);
        const auto family=root/L"LibParam"/L"param only"/L"shared";
        fs::create_directories(family); fs::create_directories(root/L"Lib"/L"static only");
        const auto input=fs::absolute(argv[2]);
        for(const auto& file:{L"M6x10.prt",L"parameter-schema.tsv",L"parameters.tsv"})
            fs::copy_file(input/file,family/file);
        fs::copy_file(input/L"M6x10.prt",root/L"Lib"/L"static only"/L"static.prt");
        AppState state; state.libraryRootOverride=root;
        state.items={{L"s",L"shared",L"static only",L"Lib/static only/static.prt",L"M6x10",false},
                     {L"p",L"shared",L"param only",L"LibParam/param only/shared/M6x10.prt",L"M6x10",true}};
        std::wstring error; RequireParam(SaveIndex(&state,error),"Initial index save");
        INITCOMMONCONTROLSEX common{sizeof(common),ICC_LISTVIEW_CLASSES|ICC_TREEVIEW_CLASSES}; InitCommonControlsEx(&common);
        controls=CreateWindowExW(0,L"STATIC",L"Isolated test controls",0,0,0,1,1,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);
        state.window=controls;
        state.list=CreateWindowExW(0,WC_LISTVIEWW,L"",WS_CHILD|LVS_REPORT|LVS_SINGLESEL,0,0,100,100,controls,reinterpret_cast<HMENU>(ID_LIST),nullptr,nullptr);
        state.category=CreateWindowExW(0,WC_TREEVIEWW,L"",WS_CHILD,0,0,100,100,controls,reinterpret_cast<HMENU>(ID_CATEGORY),nullptr,nullptr);
        CreateWindowExW(0,WC_COMBOBOXW,L"",WS_CHILD|CBS_DROPDOWNLIST,0,0,100,100,controls,reinterpret_cast<HMENU>(ID_SPEC),nullptr,nullptr);
        CreateWindowExW(0,L"EDIT",L"",WS_CHILD,0,0,100,100,controls,reinterpret_cast<HMENU>(ID_SEARCH),nullptr,nullptr);
        SelectLibrary(&state,1);
        RequireParam(state.categories==std::vector<std::wstring>{L"static only"} && state.visible==std::vector<std::size_t>{0} && SelectedIndex(&state)==0,"Static category/list/spec isolation");
        state.selectedCategory=L"static only"; SetText(controls,ID_SEARCH,L"static");
        SelectLibrary(&state,2);
        RequireParam(state.categories==std::vector<std::wstring>{L"param only"} && state.visible==std::vector<std::size_t>{1} && SelectedIndex(&state)==1,"Param category/list/spec isolation");
        state.selectedCategory=L"param only"; SetText(controls,ID_SEARCH,L"shared");
        SelectLibrary(&state,1);
        RequireParam(state.selectedCategory==L"static only" && GetText(controls,ID_SEARCH)==L"static","Restore static navigation independently");
        fs::path backup;
        RequireParam(!RemoveLibraryItem(&state,1,backup,error) && fs::exists(family/L"M6x10.prt"),"Cross-library deletion blocked");
        SelectLibrary(&state,2);
        RequireParam(state.selectedCategory==L"param only" && GetText(controls,ID_SEARCH)==L"shared","Restore param navigation independently");
        state.items[0].parameterized=true; state.items[1].parameterized=false;
        RequireParam(SaveIndex(&state,error),"Write legacy wrong flag fixture"); LoadIndex(&state);
        RequireParam(!state.items[0].parameterized && state.items[1].parameterized && state.items.size()==2,"Physical folders override stale metadata without duplicate scan entries");
        std::cout<<"PASS separate categories, families, specs, navigation, delete guards, legacy rescan\n"<<std::flush;

        tag_t work=NULL_TAG; CheckPreviewUf(UF_PART_new(ToAnsi((root/L"Base.prt").wstring()).c_str(),1,&work));
        const auto display=UF_PART_ask_display_part();
        const auto schema=ReadParameterSchema(family/L"M6x10.prt");
        auto values=SpecificationValues(family/L"M6x10.prt",L"M6x10",schema);
        RequireParam(schema.size()==8 && values[1]==L"10", "Eight named dimension controls");
        const auto sourceBytes=Bytes(family/L"M6x10.prt");
        values[1]=L"60";
        auto* session=NXOpen::Session::GetSession();
        const auto undoMark=session->SetUndoMark(NXOpen::Session::MarkVisibilityInvisible,"Parameter save context test");
        SaveParameterVariant(&state,1,schema,values,L"validation_M6x60",true);
        RequireParam(session->DoesUndoMarkExist(undoMark,"Parameter save context test") && !fs::exists(ParameterVariantPath(family,L"validation_M6x60")),"Pre-save validation preserves dialog undo mark and creates no files");
        const auto saved=SaveParameterVariant(&state,1,schema,values,L"validation_M6x60");
        RequireParam(saved==2 && Bytes(family/L"M6x10.prt")==sourceBytes,"Save-as preserves original PRT");
        RequireParam(UF_ASSEM_ask_work_part()==work && UF_PART_ask_display_part()==display,"Save-as preserves work/display context");
        const auto target=ParameterVariantPath(family,L"validation_M6x60");
        const auto result=SpecificationValues(target,L"validation_M6x60",schema);
        RequireParam(result[1]==L"60" && result[7]==L"24","Derived B updates from full length to partial thread");
        tag_t opened=NULL_TAG; UF_PART_load_status_t status{};
        const int code=UF_PART_open_quiet(ToAnsi(target.wstring()).c_str(),&opened,&status); UF_PART_free_load_status(&status); CheckPreviewUf(code);
        tag_t body=NULL_TAG; CheckPreviewUf(UF_OBJ_cycle_objs_in_part(opened,UF_solid_type,&body));
        double box[6]{}; CheckPreviewUf(UF_MODL_ask_bounding_box(body,box));
        RequireParam(std::abs(box[2]+60)<1e-4 && std::abs(box[5]-6)<1e-4 && std::abs(box[3]-5)<1e-4,"Updated screw solid envelope: L=60 K=6 DK=10");
        CheckPreviewUf(UF_PART_close(opened,0,2));
        auto shortValues=result; shortValues[1]=L"12";
        SaveParameterVariant(&state,saved,schema,shortValues,L"validation_M6x12");
        RequireParam(SpecificationValues(ParameterVariantPath(family,L"validation_M6x12"),L"validation_M6x12",schema)[7]==L"12","Derived B updates back to full thread");
        std::cout<<"PASS save new PRT, immutable source, linked solid length, B formula in both directions, restored NX context\n"<<std::flush;

        const auto rejected=[&](std::vector<std::wstring> bad,const std::wstring& name)
        { bool failed=false; try{SaveParameterVariant(&state,1,schema,bad,name);}catch(...){failed=true;} RequireParam(failed,"Invalid parameter must be rejected"); };
        auto bad=values; bad[0]=L"7"; rejected(bad,L"bad_fixed");
        bad=values; bad[1]=L"61"; rejected(bad,L"bad_list");
        bad=values; bad[1]=L"NaN"; rejected(bad,L"bad_number");
        rejected(values,L"../escape"); rejected(values,L"validation_M6x60");
        const auto beforeTable=Bytes(family/L"parameters.tsv"),beforeIndex=Bytes(root/L"library.tsv");
        const auto beforeCount=state.items.size();
        const HANDLE lock=CreateFileW((root/L"library.tsv.tmp").c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);
        RequireParam(lock!=INVALID_HANDLE_VALUE,"Lock isolated test index");
        rejected(values,L"rollback"); CloseHandle(lock);
        RequireParam(state.items.size()==beforeCount && !fs::exists(ParameterVariantPath(family,L"rollback")) && Bytes(family/L"parameters.tsv")==beforeTable && Bytes(root/L"library.tsv")==beforeIndex,"Index failure rolls back part, table, memory and preserves index");
        RequireParam(UF_ASSEM_ask_work_part()==work && UF_PART_ask_display_part()==display,"Failure preserves NX context");
        std::cout<<"PASS fixed/list/finite/path/collision validation and failure rollback\n";

        // User-created family: automatic expression discovery, editable schema,
        // copied template + image, first row, and later native parameter save.
        const auto authorSource=input/L"M6x10.prt";
        fs::create_directories(root/L"same-name");
        fs::copy_file(authorSource,root/L"same-name"/L"Base.prt");
        bool wrongPart=false;
        try{ReadTemplateExpressions(root/L"same-name"/L"Base.prt");}catch(...){wrongPart=true;}
        RequireParam(wrongPart&&UF_ASSEM_ask_work_part()==work,"Reject loaded basename collision without reading or closing user part");
        const auto sourceBefore=Bytes(authorSource);
        const auto expressions=ReadTemplateExpressions(authorSource);
        RequireParam(std::any_of(expressions.begin(),expressions.end(),[](const auto& e){return e.name==L"L"&&e.editable;}),"Discover editable model expression");
        RequireParam(std::any_of(expressions.begin(),expressions.end(),[](const auto& e){return e.name==L"B"&&!e.editable;}),"Discover dependent expression without flattening");
        auto userSchema=schema;userSchema[1].label=L"自定义长度";
        const auto newIndex=AddParameterTemplate(&state,authorSource,L"User created",L"Own screw",L"Base",userSchema);
        const auto newPart=ParameterVariantPath(root/L"LibParam"/L"User created"/L"Own screw",L"Base");
        RequireParam(Bytes(newPart)==sourceBefore && Bytes(authorSource)==sourceBefore,"User family copies original bytes");
        RequireParam(ReadParameterSchema(newPart)[1].label==L"自定义长度"&&SpecificationValues(newPart,L"Base",userSchema)[1]==L"10","User family writes first row and labels");
        auto userValues=SpecificationValues(newPart,L"Base",userSchema);userValues[1]=L"60";
        const auto ownVariant=SaveParameterVariant(&state,newIndex,userSchema,userValues,L"Custom60");
        RequireParam(SpecificationValues(root/state.items[ownVariant].relativePath,L"Custom60",userSchema)[7]==L"24","New user family can create linked native variants");
        userSchema[1].label=L"长度选择";SaveTemplateDefinition(&state,newIndex,userSchema);
        RequireParam(ReadParameterSchema(newPart)[1].label==L"长度选择"&&SpecificationValues(root/state.items[ownVariant].relativePath,L"Custom60",userSchema)[1]==L"60","Definition update preserves every specification value");
        bool invalid=false;auto brokenSchema=userSchema;brokenSchema[7].mode=L"number";
        try{AddParameterTemplate(&state,authorSource,L"User created",L"Invalid",L"Base",brokenSchema);}catch(...){invalid=true;}
        RequireParam(invalid&&!fs::exists(root/L"LibParam"/L"User created"/L"Invalid"),"Formula cannot become editable constant");
        invalid=false;try{AddParameterTemplate(&state,authorSource,L"..",L"Escape",L"Base",userSchema);}catch(...){invalid=true;}
        RequireParam(invalid,"Authoring rejects path traversal");
        const auto locked=CreateFileW((root/L"library.tsv.tmp").c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,OPEN_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);
        RequireParam(locked!=INVALID_HANDLE_VALUE,"Lock authoring index");
        const auto beforeAuthorCount=state.items.size();invalid=false;
        try{AddParameterTemplate(&state,authorSource,L"User created",L"Rollback",L"Base",userSchema);}catch(...){invalid=true;}
        CloseHandle(locked);
        RequireParam(invalid&&state.items.size()==beforeAuthorCount&&!fs::exists(root/L"LibParam"/L"User created"/L"Rollback"),"Failed authoring rolls back own directory and index");
        RequireParam(UF_ASSEM_ask_work_part()==work&&UF_PART_ask_display_part()==display&&Bytes(authorSource)==sourceBefore,"Authoring preserves user source and NX context");
        std::cout<<"PASS user template creation, definition editor data, linked variants, invalid formulas/paths and atomic rollback\n";
        const auto matchCount=state.items.size();
        const auto matchTable=Bytes(newPart.parent_path()/L"parameters.tsv");
        const auto matchMark=session->SetUndoMark(NXOpen::Session::MarkVisibilityInvisible,"Insertion match");
        RequireParam(ResolveInsertionParameters(&state,newIndex,userSchema,userValues,true)==ownVariant &&
            ResolveInsertionParameters(&state,newIndex,userSchema,userValues)==ownVariant &&
            state.items.size()==matchCount && Bytes(newPart.parent_path()/L"parameters.tsv")==matchTable &&
            session->DoesUndoMarkExist(matchMark,"Insertion match"),"Existing dimensions reuse PRT without saving or clearing dialog undo");
        userValues[1]=L"30";
        RequireParam(ResolveInsertionParameters(&state,newIndex,userSchema,userValues,true)==SIZE_MAX &&
            state.items.size()==matchCount && session->DoesUndoMarkExist(matchMark,"Insertion match"),"New input preflight is read-only");
        const auto autoVariant=ResolveInsertionParameters(&state,newIndex,userSchema,userValues);
        RequireParam(state.items.size()==matchCount+1 && ResolveInsertionParameters(&state,newIndex,userSchema,userValues)==autoVariant &&
            SpecificationValues(root/state.items[autoVariant].relativePath,state.items[autoVariant].specification,userSchema)[1]==L"30", "New insertion combination is generated once and reusable");
        std::cout<<"PASS insertion matches existing specification, preserves undo, generates missing combination once\n"<<std::flush;

        // Generic, non-screw model with arbitrary NX names and a linked height.
        tag_t blockPart=NULL_TAG,expression=NULL_TAG,blockFeature=NULL_TAG;
        const auto blockSource=root/L"BlockTemplate.prt";
        CheckPreviewUf(UF_PART_new(ToAnsi(blockSource.wstring()).c_str(),1,&blockPart));
        CheckPreviewUf(UF_MODL_create_exp_tag("WIDTH=20",&expression));
        CheckPreviewUf(UF_MODL_create_exp_tag("LENGTH=40",&expression));
        CheckPreviewUf(UF_MODL_create_exp_tag("HEIGHT=LENGTH/4",&expression));
        char blockX[]="LENGTH",blockY[]="WIDTH",blockZ[]="HEIGHT";char* blockLengths[]={blockX,blockY,blockZ};double blockOrigin[3]{};
        CheckPreviewUf(UF_MODL_create_block1(UF_NULLSIGN,blockOrigin,blockLengths,&blockFeature));
        CheckPreviewUf(UF_PART_save());
        CheckPreviewUf(UF_PART_set_display_part(work));CheckPreviewUf(UF_ASSEM_set_work_part(work));
        CheckPreviewUf(UF_PART_close(blockPart,0,1));
        const auto blockBytes=Bytes(blockSource);
        const std::vector<LibraryParameter> blockSchema={{L"LENGTH",L"总长",L"number",{}},{L"WIDTH",L"宽度",L"list",{L"20",L"35"}},{L"HEIGHT",L"联动高度",L"derived",{}}};
        const auto blockIndex=AddParameterTemplate(&state,blockSource,L"User created",L"Custom block",L"Base",blockSchema);
        const std::vector<std::wstring> blockInputs={L"80",L"35",L"10"};
        RequireParam(ResolveInsertionParameters(&state,blockIndex,blockSchema,blockInputs,true)==SIZE_MAX,"Generic new dimensions validate");
        const auto blockVariant=ResolveInsertionParameters(&state,blockIndex,blockSchema,blockInputs);
        RequireParam(Bytes(blockSource)==blockBytes && ResolveInsertionParameters(&state,blockIndex,blockSchema,blockInputs)==blockVariant,"Generic original preserved and combination reused");
        const auto blockModel=root/state.items[blockVariant].relativePath;
        RequireParam(SpecificationValues(blockModel,state.items[blockVariant].specification,blockSchema)==std::vector<std::wstring>({L"80",L"35",L"20"}),"Generic formula remains linked");
        UF_PART_load_status_t blockStatus{};CheckPreviewUf(UF_PART_open_quiet(ToAnsi(blockModel.wstring()).c_str(),&blockPart,&blockStatus));UF_PART_free_load_status(&blockStatus);
        tag_t blockBody=NULL_TAG;CheckPreviewUf(UF_OBJ_cycle_objs_in_part(blockPart,UF_solid_type,&blockBody));double blockBox[6]{};CheckPreviewUf(UF_MODL_ask_bounding_box(blockBody,blockBox));
        RequireParam(std::abs(blockBox[3]-blockBox[0]-80)<1e-4 && std::abs(blockBox[4]-blockBox[1]-35)<1e-4 && std::abs(blockBox[5]-blockBox[2]-20)<1e-4,"Generated generic solid is 80 x 35 x 20");
        CheckPreviewUf(UF_PART_close(blockPart,0,1));
        std::cout<<"PASS generic non-screw parameter insertion: numeric/list controls, derived dimension and 80 x 35 x 20 native solid\n"<<std::flush;
        const auto groupsBeforeIndex=Bytes(root/L"library.tsv");
        const auto groupsBeforeTable=Bytes(blockModel.parent_path()/L"parameters.tsv");
        const auto groupMark=session->SetUndoMark(NXOpen::Session::MarkVisibilityInvisible,"Parameter groups metadata");
        SaveParameterGroup(&state,blockIndex,L"A组",blockSchema,{L"40",L"20",L"10"});
        SaveParameterGroup(&state,blockIndex,L"B组",blockSchema,blockInputs);
        auto groups=ReadParameterGroups(blockModel);
        RequireParam(groups.size()==2 && groups[0].name==L"A组" && groups[1].name==L"B组" &&
            groups[1].inputs.size()==2 && groups[1].inputs.count(L"HEIGHT")==0,"Groups persist independent editable values without flattening formula");
        RequireParam(ParameterGroupValues(groups[1],blockSchema,{L"40",L"20",L"10"})==blockInputs,"B group loads complete dimension set");
        auto reordered=blockSchema;std::swap(reordered[0],reordered[1]);reordered[0].label=L"新的中文宽度";
        RequireParam(ParameterGroupValues(groups[1],reordered,{L"20",L"40",L"10"})==std::vector<std::wstring>{L"35",L"80",L"10"},"Group binding survives display labels and ordering");
        SaveParameterGroup(&state,blockIndex,L"B组",blockSchema,{L"120",L"35",L"10"});
        groups=ReadParameterGroups(blockModel);
        RequireParam(groups.size()==2 && groups[1].inputs.at(L"LENGTH")==L"120","Same group name updates without duplication");
        const auto groupFile=blockModel.parent_path()/L"parameter-groups.tsv";
        const auto savedGroups=Bytes(groupFile);
        const auto rejectGroup=[&](const std::wstring& name,const std::vector<std::wstring>& input)
        {bool failed=false;try{SaveParameterGroup(&state,blockIndex,name,blockSchema,input);}catch(...){failed=true;}RequireParam(failed&&Bytes(groupFile)==savedGroups,"Invalid group must leave metadata intact");};
        rejectGroup(L"",blockInputs);rejectGroup(L"bad\tname",blockInputs);
        rejectGroup(L"invalid",{L"80",L"NaN",L"10"});rejectGroup(L"outside list",{L"80",L"25",L"10"});
        const auto groupLock=CreateFileW((groupFile.wstring()+L".tmp").c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);
        RequireParam(groupLock!=INVALID_HANDLE_VALUE,"Lock own group staging file");
        rejectGroup(L"C组",blockInputs);CloseHandle(groupLock);
        RequireParam(Bytes(root/L"library.tsv")==groupsBeforeIndex && Bytes(blockModel.parent_path()/L"parameters.tsv")==groupsBeforeTable &&
            session->DoesUndoMarkExist(groupMark,"Parameter groups metadata") && Bytes(blockSource)==blockBytes,
            "Saving groups must not create PRTs, alter index/table, clear NX undo or edit source");
        const auto groupedInputs=ParameterGroupValues(groups[1],blockSchema,{L"40",L"20",L"10"});
        const auto groupedVariant=ResolveInsertionParameters(&state,blockIndex,blockSchema,groupedInputs);
        RequireParam(SpecificationValues(root/state.items[groupedVariant].relativePath,state.items[groupedVariant].specification,blockSchema)==
            std::vector<std::wstring>{L"120",L"35",L"30"},"Selecting a group must generate a native variant with linked formula");
        DeleteParameterGroup(&state,blockIndex,L"A组");
        RequireParam(ReadParameterGroups(blockModel).size()==1 && fs::exists(root/state.items[groupedVariant].relativePath),"Delete group preserves generated PRT");
        DeleteParameterGroup(&state,blockIndex,L"B组");
        RequireParam(ReadParameterGroups(blockModel).empty(),"Empty group file is valid");
        std::cout<<"PASS parameter groups: A/B persistence, whole-set switching, expression binding, edit/delete, validation, atomic failure, undo/source preservation, formula variant\n"<<std::flush;

        // Independent length/width/height, matching the user's cuboid example.
        const auto cuboidSource=root/L"CuboidTemplate.prt";
        CheckPreviewUf(UF_PART_new(ToAnsi(cuboidSource.wstring()).c_str(),1,&blockPart));
        CheckPreviewUf(UF_MODL_create_exp_tag("LENGTH=100",&expression));
        CheckPreviewUf(UF_MODL_create_exp_tag("WIDTH=50",&expression));
        CheckPreviewUf(UF_MODL_create_exp_tag("HEIGHT=30",&expression));
        CheckPreviewUf(UF_MODL_create_block1(UF_NULLSIGN,blockOrigin,blockLengths,&blockFeature));
        CheckPreviewUf(UF_PART_save());CheckPreviewUf(UF_PART_set_display_part(work));CheckPreviewUf(UF_ASSEM_set_work_part(work));
        CheckPreviewUf(UF_PART_close(blockPart,0,1));
        const std::vector<LibraryParameter> cuboidSchema={{L"LENGTH",L"长",L"number",{}},{L"WIDTH",L"宽",L"number",{}},{L"HEIGHT",L"高",L"number",{}}};
        const auto cuboidIndex=AddParameterTemplate(&state,cuboidSource,L"User created",L"Grouped cuboid",L"Base",cuboidSchema);
        const auto cuboidModel=root/state.items[cuboidIndex].relativePath;
        SaveParameterGroup(&state,cuboidIndex,L"A组",cuboidSchema,{L"100",L"50",L"30"});
        SaveParameterGroup(&state,cuboidIndex,L"B组",cuboidSchema,{L"80",L"40",L"20"});
        const auto cuboidGroups=ReadParameterGroups(cuboidModel);
        RequireParam(ResolveInsertionParameters(&state,cuboidIndex,cuboidSchema,ParameterGroupValues(cuboidGroups[0],cuboidSchema,{L"100",L"50",L"30"}))==cuboidIndex,"A group reuses 100x50x30 original");
        const auto cuboidVariant=ResolveInsertionParameters(&state,cuboidIndex,cuboidSchema,ParameterGroupValues(cuboidGroups[1],cuboidSchema,{L"100",L"50",L"30"}));
        CheckPreviewUf(UF_PART_open_quiet(ToAnsi((root/state.items[cuboidVariant].relativePath).wstring()).c_str(),&blockPart,&blockStatus));UF_PART_free_load_status(&blockStatus);
        blockBody=NULL_TAG;CheckPreviewUf(UF_OBJ_cycle_objs_in_part(blockPart,UF_solid_type,&blockBody));CheckPreviewUf(UF_MODL_ask_bounding_box(blockBody,blockBox));
        RequireParam(std::abs(blockBox[3]-blockBox[0]-80)<1e-4 && std::abs(blockBox[4]-blockBox[1]-40)<1e-4 && std::abs(blockBox[5]-blockBox[2]-20)<1e-4,"B group generates exact 80x40x20 cuboid");
        CheckPreviewUf(UF_PART_close(blockPart,0,1));
        std::cout<<"PASS cuboid A/B groups: 100 x 50 x 30 reuse, 80 x 40 x 20 exact generated native solid\n"<<std::flush;
        // Exercise the actual main-dialog combo, not just the group data helpers.
        for(int id=ID_PARAM_VALUE1;id<=ID_PARAM_VALUE4;++id)
            CreateWindowExW(0,L"STATIC",L"",WS_CHILD,0,0,100,20,controls,reinterpret_cast<HMENU>(static_cast<INT_PTR>(id)),nullptr,nullptr);
        SelectLibrarySpecification(&state,cuboidIndex);
        const auto mainCombo=GetDlgItem(controls,ID_SPEC);
        RequireParam(SendMessageW(mainCombo,CB_GETCOUNT,0,0)==2 && GetText(controls,ID_SPEC)==L"A组" &&
            SelectedIndex(&state)==cuboidIndex,"Main combo shows A/B names and maps A to the real PRT");
        SendMessageW(mainCombo,CB_SETCURSEL,1,0);HandleSpecificationSelection(&state);
        RequireParam(GetText(controls,ID_SPEC)==L"B组" && SelectedIndex(&state)==cuboidVariant &&
            GetText(controls,ID_PARAM_VALUE1)==L"80" && GetText(controls,ID_PARAM_VALUE2)==L"40" &&
            GetText(controls,ID_PARAM_VALUE3)==L"20","Main group selection updates model and all summary dimensions");
        RefreshSpecifications(&state);
        RequireParam(GetText(controls,ID_SPEC)==L"B组" && SelectedIndex(&state)==cuboidVariant,"Refresh retains resolved B group");
        SendMessageW(mainCombo,CB_SETCURSEL,0,0);HandleSpecificationSelection(&state);
        RequireParam(GetText(controls,ID_SPEC)==L"A组" && SelectedIndex(&state)==cuboidIndex,"Main combo switches back to A");
        SaveParameterGroup(&state,cuboidIndex,L"C组",cuboidSchema,{L"60",L"30",L"15"});
        RefreshSpecifications(&state);
        SendMessageW(mainCombo,CB_SETCURSEL,2,0);SelectMainParameterGroup(&state,L"C组");
        const auto cIndex=SelectedIndex(&state);
        RequireParam(cIndex!=cuboidIndex && cIndex!=cuboidVariant && GetText(controls,ID_SPEC)==L"C组" &&
            SpecificationValues(root/state.items[cIndex].relativePath,state.items[cIndex].specification,cuboidSchema)==
            std::vector<std::wstring>{L"60",L"30",L"15"},"Main group can resolve a previously unbuilt combination");
        DeleteParameterGroup(&state,cIndex,L"C组");RefreshSpecifications(&state);
        RequireParam(GetText(controls,ID_SPEC)==L"当前尺寸（自定义）" && SelectedIndex(&state)==cIndex,"Deleted group keeps real custom model selected");
        SelectLibrarySpecification(&state,1);
        RequireParam(SelectedParameterGroup(&state).empty() && GetText(controls,ID_SPEC)==L"M6x10","Ungrouped family keeps specification combo without leaking cuboid groups");
        SelectLibrary(&state,1);
        RequireParam(SelectedParameterGroup(&state).empty() && SelectedIndex(&state)==0,"Static family remains isolated");
        SelectLibrary(&state,2);SelectLibrarySpecification(&state,cuboidIndex);
        // Kept unbuilt for native modal save/reopen verification.
        SaveParameterGroup(&state,cuboidIndex,L"D组",cuboidSchema,{L"70",L"35",L"25"});
        std::cout<<"PASS main combo: named groups, A/B model and dimension switching, refresh, new variant, deleted-group fallback, family/static isolation\n"<<std::flush;
        if(argc==4)
        {
            const auto flatSource=fs::absolute(argv[3])/L"GB70_3_M6x20.prt";
            const auto flatSchema=ReadParameterSchema(flatSource);
            tag_t socket=NULL_TAG;UF_PART_load_status_t loadStatus{};
            CheckPreviewUf(UF_PART_open_quiet(ToAnsi((input/L"M6x20.prt").wstring()).c_str(),&socket,&loadStatus));UF_PART_free_load_status(&loadStatus);
            const auto flatIndex=AddParameterTemplate(&state,flatSource,L"User created",L"Flat screw",L"M6x20",flatSchema);
            const auto flatPart=root/state.items[flatIndex].relativePath;
            auto flatValues=SpecificationValues(flatPart,L"M6x20",flatSchema);
            for(std::size_t i=0;i<flatSchema.size();++i)if(flatSchema[i].expression==L"L")flatValues[i]=L"60";
            const auto flatNew=SaveParameterVariant(&state,flatIndex,flatSchema,flatValues,L"M6x60");
            const auto flatResult=root/state.items[flatNew].relativePath;
            const auto derived=SpecificationValues(flatResult,L"M6x60",flatSchema);
            for(std::size_t i=0;i<flatSchema.size();++i)if(flatSchema[i].expression==L"B")RequireParam(derived[i]==L"24","Flat partial thread B=24");
            tag_t flatLoaded=NULL_TAG;CheckPreviewUf(UF_PART_open_quiet(ToAnsi(flatResult.wstring()).c_str(),&flatLoaded,&loadStatus));UF_PART_free_load_status(&loadStatus);
            tag_t flatBody=NULL_TAG;CheckPreviewUf(UF_OBJ_cycle_objs_in_part(flatLoaded,UF_solid_type,&flatBody));double flatBox[6]{};CheckPreviewUf(UF_MODL_ask_bounding_box(flatBody,flatBox));
            RequireParam(std::abs(flatBox[2]+60)<1e-4&&std::abs(flatBox[5])<1e-4&&std::abs(flatBox[3]-6.08)<1e-4,"Flat native envelope: overall L=60, top Z=0, actual DK=12.16");
            CheckPreviewUf(UF_PART_close(flatLoaded,0,1));CheckPreviewUf(UF_PART_close(socket,0,1));
            RequireParam(UF_ASSEM_ask_work_part()==work&&UF_PART_ask_display_part()==display,"Flat creation preserves work/display context");
            std::cout<<"PASS flat/socket coexistence, user family, linked flat L=60 B=24 and exact native solid envelope\n";
        }
        DestroyWindow(controls); UF_terminate(); return 0;
    }
    catch(const NXOpen::NXException& ex){std::cerr<<"FAIL NX: "<<ex.Message()<<"\n";}
    catch(const std::exception& ex){std::cerr<<"FAIL: "<<ex.what()<<"\n";}
    if(controls) DestroyWindow(controls); if(initialized)UF_terminate(); return 1;
}
