//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\LPOpenPrint\application\MenBanSiBian.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Mechrevo
//              Version: NX 2306
//              Date: 01-20-2025  (Format: mm-dd-yyyy)
//              Time: 10:26
//
//==============================================================================

#ifndef MENBANSIBIAN_H_INCLUDED
#define MENBANSIBIAN_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_SelectObject.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>

#include <uf_obj.h>
#include <NXOpen/BasePart.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <UF.h>
#include <NXOpen/CoordinateSystem.hxx>
#include <NXOpen/Edge.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Features_Feature.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/NXObjectManager.hxx>
#include <NXOpen/ScalarCollection.hxx>
#include <NXOpen/Point.hxx>
#include <NXOpen/PointCollection.hxx>
#include <NXOpen/DirectionCollection.hxx>
#include <NXOpen/XformCollection.hxx>
#include <NXOpen/CoordinateSystemCollection.hxx>
#include <NXOpen/WCS.hxx>
#include <NXOpen/CartesianCoordinateSystem.hxx>
#include <NXOpen/NXMatrix.hxx>
#include <uf_modl.h>
#include <uf_ui.h>
#include <NXOpen/Xform.hxx>
#include <uf_csys.h>
#include <NXOpen/Body.hxx>
#include <NXOpen/BodyCollection.hxx>
#include <NXOpen/MeasureDistance.hxx>
#include <NXOpen/MeasureDistanceBuilder.hxx>
#include <NXOpen/MeasureManager.hxx>
#include <NXOpen/MeasureFaces.hxx>
#include <NXOpen/Unit.hxx>
#include <NXOpen/UnitCollection.hxx>
#include <NXOpen/IParameterizedSurface.hxx>
#include <NXOpen/Features_ToolingBoxBuilder.hxx>
#include <NXOpen/Features_ToolingFeatureCollection.hxx>
#include <NXOpen/Features_BooleanBuilder.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/ScCollectorCollection.hxx>
#include <NXOpen/SelectionIntentRule.hxx>
#include <NXOpen/SelectionIntentRuleOptions.hxx>
#include <NXOpen/ScRuleFactory.hxx>
#include <NXOpen/BodyDumbRule.hxx>




//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesEnabled
//------------------------------------------------------------------------------
#define              SnapPointTypesEnabled_UserDefined (1 << 0);
#define                 SnapPointTypesEnabled_Inferred (1 << 1);
#define           SnapPointTypesEnabled_ScreenPosition (1 << 2);
#define                 SnapPointTypesEnabled_EndPoint (1 << 3);
#define                 SnapPointTypesEnabled_MidPoint (1 << 4);
#define             SnapPointTypesEnabled_ControlPoint (1 << 5);
#define             SnapPointTypesEnabled_Intersection (1 << 6);
#define                SnapPointTypesEnabled_ArcCenter (1 << 7);
#define            SnapPointTypesEnabled_QuadrantPoint (1 << 8);
#define            SnapPointTypesEnabled_ExistingPoint (1 << 9);
#define             SnapPointTypesEnabled_PointonCurve (1 <<10);
#define           SnapPointTypesEnabled_PointonSurface (1 <<11);
#define         SnapPointTypesEnabled_PointConstructor (1 <<12);
#define     SnapPointTypesEnabled_TwocurveIntersection (1 <<13);
#define             SnapPointTypesEnabled_TangentPoint (1 <<14);
#define                    SnapPointTypesEnabled_Poles (1 <<15);
#define         SnapPointTypesEnabled_BoundedGridPoint (1 <<16);
#define         SnapPointTypesEnabled_FacetVertexPoint (1 <<17);
#define            SnapPointTypesEnabled_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define             SnapPointTypesOnByDefault_EndPoint (1 << 3);
#define             SnapPointTypesOnByDefault_MidPoint (1 << 4);
#define         SnapPointTypesOnByDefault_ControlPoint (1 << 5);
#define         SnapPointTypesOnByDefault_Intersection (1 << 6);
#define            SnapPointTypesOnByDefault_ArcCenter (1 << 7);
#define        SnapPointTypesOnByDefault_QuadrantPoint (1 << 8);
#define        SnapPointTypesOnByDefault_ExistingPoint (1 << 9);
#define         SnapPointTypesOnByDefault_PointonCurve (1 <<10);
#define       SnapPointTypesOnByDefault_PointonSurface (1 <<11);
#define     SnapPointTypesOnByDefault_PointConstructor (1 <<12);
#define     SnapPointTypesOnByDefault_BoundedGridPoint (1 <<16);
#define     SnapPointTypesOnByDefault_FacetVertexPoint (1 <<17);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport MenBanSiBian
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    MenBanSiBian();
    ~MenBanSiBian();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the MenBanSiBian.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    void Create_DuiJiao_Box(Edge* JiaoEdge, Edge* BanHouEdge, double tearGap, NXObject* &nXObject);
    void Create_DinDian_Box(Point3d DuanDian1, double BanHou, double bendInnerR, CartesianCoordinateSystem* cartesianCoordinateSystem1, NXObject* &nXObject);
    void Create_JiaoBian_Box(Point3d position1, double BanHou, Edge* JiaoEdge, CartesianCoordinateSystem* cartesianCoordinateSystem1, int cornerType, int forceDirection, double tearGap, NXObject* &nXObject, double cutThroughHeight = 0.0, double cutThroughSideLength = 0.0);
    void Create_ZiJiao_Box(Edge* JiaoEdge, Edge* BanHouEdge, double tearGap, NXObject*& nXObject, NXObject*& nXObject1);
    void Convertpoint_acs_to_wcs(Point3d in_Point3d1, Point3d &out_Point3d1);
    void ask_edge_wcs_Vertices(Edge* BodyEdge,Point3d & Ver_Point3d1, Point3d& Ver_Point3d2);
    void Create_DanBian_Box(Edge* JiaoEdge, Edge* BanHouEdge, double tearGap, NXObject*& nXObject);


    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    int filter_cb(NXOpen::BlockStyler::UIBlock* block, NXOpen::TaggedObject* selectedObject);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Enumeration* enumCreateMode;// Block type: Enumeration
    NXOpen::BlockStyler::SelectObject* selection0;// Block type: Selection
    NXOpen::BlockStyler::SelectObject* selectionEdge;// Block type: Selection
    NXOpen::BlockStyler::Enumeration* enum0;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum01;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* bendInnerR;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* tearGap;// Block type: Double
    
};
#endif //MENBANSIBIAN_H_INCLUDED
