//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\LPOpenPrint\application\DaoCuDWG.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: CHENHUI
//              Version: NX 2007
//              Date: 12-15-2021  (Format: mm-dd-yyyy)
//              Time: 23:14 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "DaoCuDWG.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session* (DaoCuDWG::theSession) = NULL;
UI* (DaoCuDWG::theUI) = NULL;

namespace zhihui_license_guard
{
typedef int (__stdcall *EnsureAuthorizedProc)(const wchar_t*, const wchar_t*, wchar_t*, int);

bool EnsureAuthorized(const wchar_t* featureCode, const wchar_t* displayName)
{
    wchar_t message[512] = {0};
    HMODULE module = LoadLibraryW(L"ZhaoFuNxLicenseGate.dll");
    if (!module)
    {
        module = LoadLibraryW(L"D:\\智辉\\application\\ZhaoFuNxLicenseGate.dll");
    }
    if (!module)
    {
        return false;
    }

    EnsureAuthorizedProc ensureAuthorized =
        reinterpret_cast<EnsureAuthorizedProc>(GetProcAddress(module, "ZfnxEnsureAuthorized"));
    if (!ensureAuthorized)
    {
        return false;
    }

    const int ok = ensureAuthorized(featureCode, displayName, message, static_cast<int>(sizeof(message) / sizeof(message[0])));
    const int ok2 = ok == 1 ? ensureAuthorized(featureCode, displayName, message, static_cast<int>(sizeof(message) / sizeof(message[0]))) : ok;
    if (ok2 != 1)
    {
        return false;
    }
    return true;
}
}
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
DaoCuDWG::DaoCuDWG()
{
    try
    {
        // Initialize the NX Open C++ API environment
        DaoCuDWG::theSession = NXOpen::Session::GetSession();
        DaoCuDWG::theUI = UI::GetUI();
        theDlxFileName = "DaoCuDWG.dlx";
        theDialog = DaoCuDWG::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &DaoCuDWG::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &DaoCuDWG::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &DaoCuDWG::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &DaoCuDWG::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &DaoCuDWG::dialogShown_cb));
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
DaoCuDWG::~DaoCuDWG()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char* param, int* retcod, int param_len)
{
    if (!zhihui_license_guard::EnsureAuthorized(L"ZHIHUI.DAOCUDWG", L"DaoCuDWG"))
    {
        return;
    }

    DaoCuDWG* theDaoCuDWG = NULL;
    try
    {
        theDaoCuDWG = new DaoCuDWG();
        // The following method shows the dialog immediately
        theDaoCuDWG->Show();
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        DaoCuDWG::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if (theDaoCuDWG != NULL)
    {
        delete theDaoCuDWG;
        theDaoCuDWG = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    volatile int unloadOption = (int)Session::LibraryUnloadOptionImmediately;
    return unloadOption;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        DaoCuDWG::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int DaoCuDWG::Show()
{
    try
    {
        theDialog->Show();
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        DaoCuDWG::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void DaoCuDWG::initialize_cb()
{
    try
    {
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        toggle0 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle0"));
        toggle01 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle01"));
        toggle02 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle02"));
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        nativeFolderBrowser0 = dynamic_cast<NXOpen::BlockStyler::FolderSelection*>(theDialog->TopBlock()->FindBlock("nativeFolderBrowser0"));
        string0 = dynamic_cast<NXOpen::BlockStyler::StringBlock*>(theDialog->TopBlock()->FindBlock("string0"));
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        DaoCuDWG::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}
NXOpen::Session* theSession = NXOpen::Session::GetSession();
NXOpen::Part* workPart(theSession->Parts()->Work());
NXOpen::Part* displayPart(theSession->Parts()->Display());
string StrWorkPathQ;
std::vector<NXOpen::Part*> VecPart;
string StrName;
string StrFullPath;
NXString WorkName1;
tag_t AssTag;

void DaoCuDWG::getchildren(Assemblies::Component* root)
{

    //用户代码
    std::vector<Assemblies::Component*> children = root->GetChildren();//获取第一层Component
    for (int i = 0; i < children.size(); i++)

    {   

        Assemblies::Component* component = children[i];//获取第一层第i个Component
        NXOpen::Part* part1(dynamic_cast<NXOpen::Part*>(theSession->Parts()->FindObject(component->DisplayName())));
        VecPart.push_back(part1);
        getchildren(component);
        UF_ASSEM_set_work_part(part1->Tag());
    }



}
//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void DaoCuDWG::dialogShown_cb()
{
    try
    {
        WorkName1 = workPart->Name();//提取工作部件的文件名
        StrName = WorkName1.GetLocaleText();
        NXString WorkFullPath = workPart->FullPath();//提取工作部件的路径跟名称
        StrFullPath = WorkFullPath.GetLocaleText();
        StrWorkPathQ = StrFullPath.substr(0, StrFullPath.length() - StrName.size() - 4) + "\\DWG";//删除后面的4个字符
        CString AAAA = StrWorkPathQ.c_str();
        if (!PathIsDirectory(AAAA))
        {
             CreateDirectory(AAAA, 0);
        }

        //string command;
        //command = "mkdir -p " + StrWorkPathQ;//新建目录
        //system(command.c_str());
        //获取零件编号
        PropertyList* nativeFolderBrowser0Props = nativeFolderBrowser0->GetProperties();
        nativeFolderBrowser0Props->SetString("Path", StrWorkPathQ.c_str());
        delete nativeFolderBrowser0Props;
        nativeFolderBrowser0Props = NULL;

        PropertyList* string0Props = string0->GetProperties();
        string0Props->SetString("Value", WorkName1.GetLocaleText());
        delete string0Props;
        string0Props = NULL;
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        DaoCuDWG::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int DaoCuDWG::apply_cb()
{
    int errorCode = 0;
    try
    {
		UF_initialize();
		AssTag = workPart->Tag();

		//遍历实例
		Assemblies::ComponentAssembly* componentassembly = workPart->ComponentAssembly();//获取装配底层（BaseWork为当前工作装配，basedisplaypart为当前显示的装配 两种结果是不一样的）
		Assemblies::Component* rootcomponent = componentassembly->RootComponent();//获取rootcomponent
		if (rootcomponent == NULL)//判断rootcomponent是否为空，空即提示不是装配，是就执行遍历
		{
			//弹出消息框（四种消息框 错误：DialogTypeError 警告：DialogTypeWarning 提示：DialogTypeInformation 询问：DialogTypeQuestion
			theUI->NXMessageBox()->Show("提示", NXOpen::NXMessageBox::DialogTypeWarning, "当前没在装配环境!"); //弹出消息框提示
		}
		else//
		{
			NXOpen::Part* part1(dynamic_cast<NXOpen::Part*>(theSession->Parts()->FindObject(rootcomponent->DisplayName())));
			VecPart.push_back(part1);
			getchildren(rootcomponent);
			UF_ASSEM_set_work_part(part1->Tag());
		}
		//获取零件编号
		PropertyList* nativeFolderBrowser0Props = nativeFolderBrowser0->GetProperties();
		NXString ThenativeFolderBrowser0 = nativeFolderBrowser0Props->GetString("Path");
		delete nativeFolderBrowser0Props;
		nativeFolderBrowser0Props = NULL;

		for (size_t i = 0; i < VecPart.size(); i++)
		{
			for (size_t b = i + 1; b < VecPart.size(); )
			{
				if (VecPart[i]->Tag() == VecPart[b]->Tag())
				{
					VecPart.erase(VecPart.begin() + b);
				}
				else
				{
					b++;

				}
			}
		}




		//获取零件编号
		PropertyList* string0Props = string0->GetProperties();
		NXString Thestring0 = string0Props->GetString("Value");
		delete string0Props;
		string0Props = NULL;

		int Thetoggle0 = true;
		int Thetoggle01 = false;
		int Thetoggle02 = false;
		if (toggle0 != NULL)
		{
			PropertyList* toggle0Props = toggle0->GetProperties();
			Thetoggle0 = toggle0Props->GetLogical("Value");
			delete toggle0Props;
			toggle0Props = NULL;
		}
		if (toggle01 != NULL)
		{
			PropertyList* toggle01Props = toggle01->GetProperties();
			Thetoggle01 = toggle01Props->GetLogical("Value");
			delete toggle01Props;
			toggle01Props = NULL;
		}
		if (toggle02 != NULL)
		{
			PropertyList* toggle02Props = toggle02->GetProperties();
			Thetoggle02 = toggle02Props->GetLogical("Value");
			delete toggle02Props;
			toggle02Props = NULL;
		}




		NXOpen::PrintPDFBuilder* printPDFBuilder1;
		printPDFBuilder1 = workPart->PlotManager()->CreatePrintPdfbuilder();
		if (Thetoggle01 == true)
		{
			printPDFBuilder1->SetScale(1.0);
			printPDFBuilder1->SetAppend(true);
			printPDFBuilder1->SetColors(NXOpen::PrintPDFBuilder::ColorBlackOnWhite);
			printPDFBuilder1->SetWidths(NXOpen::PrintPDFBuilder::WidthCustomThreeWidths);
			printPDFBuilder1->SetSize(NXOpen::PrintPDFBuilder::SizeOptionScaleFactor);
			printPDFBuilder1->SetXDimension(215.90000000000001);
			printPDFBuilder1->SetYDimension(279.39999999999998);
			printPDFBuilder1->SetOutputText(NXOpen::PrintPDFBuilder::OutputTextOptionPolylines);
			printPDFBuilder1->SetRasterImages(true);
			string StrWorkPathQ1 = StrFullPath.substr(0, StrFullPath.length() - StrName.size() - 4) + Thestring0.GetLocaleText() + ".pdf";//删除后面的4个字符
			printPDFBuilder1->SetFilename(StrWorkPathQ1);
		}


		int c = 1, d = 0;

		for (size_t i = 0; i < VecPart.size(); i++)
		{

			NXOpen::Drawings::DrawingSheet* theDrawingsSheets;//定义类型
			Drawings::DrawingSheetCollection* DrawingSheet = VecPart[i]->DrawingSheets();
			Drawings::DrawingSheetCollection::iterator Ite = VecPart[i]->DrawingSheets()->begin();//定义迭代器
			std::vector<NXOpen::NXObject*> AllSheetsVector;//存到vector  

			if (Ite != DrawingSheet->end())
			{
				d++;
               
				UF_PART_set_display_part(VecPart[i]->Tag());
				theSession->ApplicationSwitchImmediate("UG_APP_DRAFTING");
				workPart->Drafting()->EnterDraftingApplication();
				for (; Ite != DrawingSheet->end(); ++Ite) //循环获得所有图纸页
				{

					theDrawingsSheets = (*Ite); //获得图纸页
                    theDrawingsSheets->Open();
					AllSheetsVector.push_back(theDrawingsSheets);
					if (Thetoggle0 == true)
					{
                        NXOpen::DxfdwgCreator* dxfdwgCreator1;
                        dxfdwgCreator1 = theSession->DexManager()->CreateDxfdwgCreator();
                        dxfdwgCreator1->SetExportData(NXOpen::DxfdwgCreator::ExportDataOptionDrawing);
                        dxfdwgCreator1->SetAutoCADRevision(NXOpen::DxfdwgCreator::AutoCADRevisionOptionsR2004);
                        dxfdwgCreator1->SetOutputFileType(NXOpen::DxfdwgCreator::OutputFileTypeOptionDwg);
                        dxfdwgCreator1->SetProcessHoldFlag(false);
                        dxfdwgCreator1->SetFileSaveFlag(false);
                        dxfdwgCreator1->SetViewEditMode(true);
                        dxfdwgCreator1->ObjectTypes()->SetCurves(true);
                        dxfdwgCreator1->ObjectTypes()->SetAnnotations(true);
                        dxfdwgCreator1->ObjectTypes()->SetStructures(true);
                        dxfdwgCreator1->SetExportScaleOption(NXOpen::DxfdwgCreator::ExportScaleOptionsBaseView);
                        dxfdwgCreator1->SetFlattenAssembly(false);
                        dxfdwgCreator1->SetWidthFactorMode(NXOpen::DxfdwgCreator::WidthfactorMethodOptionsAutomaticCalculation);
                        dxfdwgCreator1->SetLayerMask("1-256");

						dxfdwgCreator1->SetInputFile(VecPart[i]->FullPath());
						double a, b;
						theDrawingsSheets->GetScale(&a, &b);
						dxfdwgCreator1->SetExportScaleValue(b / a);

                        NXString folderPath = ThenativeFolderBrowser0 + "\\" + VecPart[i]->Name() + "_" + theDrawingsSheets->Name() + ".dwg";
						dxfdwgCreator1->SetOutputFile(folderPath);
						dxfdwgCreator1->SetDrawingList(theDrawingsSheets->Name());

						NXOpen::NXObject* nXObject1;
						nXObject1 = dxfdwgCreator1->Commit();

                        dxfdwgCreator1->Destroy();
                        theSession->CleanUpFacetedFacesAndEdges();
						char ShuLiang[256];
						sprintf(ShuLiang, "%d %s\n", c++, folderPath.GetLocaleText());
						UF_UI_open_listing_window();
						UF_UI_write_listing_window(ShuLiang);
					}
					else
					{
						c++;
					}


				}
				if (Thetoggle01 == true)
				{
					printPDFBuilder1->SourceBuilder()->SetSheets(AllSheetsVector);
					NXOpen::NXObject* nXObject2;
					nXObject2 = printPDFBuilder1->Commit();
				}

			}

		}

		char ShuLiang[256];
		sprintf(ShuLiang, "图纸共%d页  零件共%d个", c - 1, d);
		UF_UI_open_listing_window();
		UF_UI_write_listing_window(ShuLiang);

		printPDFBuilder1->Destroy();
		UF_PART_set_display_part(AssTag);
		UF_ASSEM_set_work_part(AssTag);

		UF_terminate();
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        DaoCuDWG::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int DaoCuDWG::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if (block == toggle0)
        {
            //---------Enter your code here-----------
        }
        else if (block == toggle01)
        {
            //---------Enter your code here-----------
        }
        else if (block == toggle02)
        {
            //---------Enter your code here-----------
        }
        else if (block == nativeFolderBrowser0)
        {
            //---------Enter your code here-----------
        }
        else if (block == string0)
        {
            //---------Enter your code here-----------
        }
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        DaoCuDWG::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int DaoCuDWG::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        DaoCuDWG::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* DaoCuDWG::GetBlockProperties(const char* blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
