//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\LPOpenPrint\application\SetAttr.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: Administrator
//              Version: NX 1992
//              Date: 10-23-2021  (Format: mm-dd-yyyy)
//              Time: 08:26 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "SetAttr.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(SetAttr::theSession) = NULL;
UI *(SetAttr::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
SetAttr::SetAttr()
{
    try
    {
        // Initialize the NX Open C++ API environment
        SetAttr::theSession = NXOpen::Session::GetSession();
        SetAttr::theUI = UI::GetUI();
        theDlxFileName = "SetAttr.dlx";
        theDialog = SetAttr::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &SetAttr::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &SetAttr::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &SetAttr::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &SetAttr::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &SetAttr::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
SetAttr::~SetAttr()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>

namespace zhihui_license_guard
{
typedef int (__stdcall *EnsureAuthorizedProc)(const wchar_t*, const wchar_t*, wchar_t*, int);

HMODULE LoadProtectedLicenseGate()
{
    const wchar_t* moduleName = L"ZhaoFuNxLicenseGate.dll";

    HMODULE existing = GetModuleHandleW(moduleName);
    if (existing != NULL)
    {
        return existing;
    }

    HMODULE selfModule = NULL;
    if (GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
        reinterpret_cast<LPCWSTR>(&LoadProtectedLicenseGate), &selfModule))
    {
        wchar_t localPath[MAX_PATH] = { 0 };
        DWORD length = GetModuleFileNameW(selfModule, localPath, MAX_PATH);
        if (length > 0 && length < MAX_PATH)
        {
            DWORD slash = length;
            while (slash > 0 && localPath[slash - 1] != L'\\' && localPath[slash - 1] != L'/')
            {
                --slash;
            }

            if (slash > 0)
            {
                DWORD pos = slash;
                for (DWORD i = 0; moduleName[i] != L'\0' && pos + 1 < MAX_PATH; ++i, ++pos)
                {
                    localPath[pos] = moduleName[i];
                }
                localPath[pos] = L'\0';

                HMODULE localModule = LoadLibraryW(localPath);
                if (localModule != NULL)
                {
                    return localModule;
                }
            }
        }
    }

    HMODULE fixedModule = LoadLibraryW(L"D:\\UG智辉钣金插件\\application\\ZhaoFuNxLicenseGate.dll");
    if (fixedModule != NULL)
    {
        return fixedModule;
    }

    return LoadLibraryW(moduleName);
}

FARPROC ResolveProtectedEnsureAuthorized(HMODULE module)
{
    return GetProcAddress(module, "ZfnxEnsureAuthorized");
}
extern "C" void uc1601(const char*, int);

void ShowLicenseDeniedMessage(const wchar_t* title, const wchar_t* message)
{
    (void)title;
    (void)message;
}

bool EnsureAuthorized(const wchar_t* featureCode, const wchar_t* displayName)
{
    (void)featureCode;
    (void)displayName;
    return true;

    wchar_t message[1024] = { 0 };
    HMODULE module = LoadProtectedLicenseGate();
    if (module == NULL)
    {
        ShowLicenseDeniedMessage(displayName, L"License component was not found.");
        return false;
    }

    EnsureAuthorizedProc ensureAuthorized = reinterpret_cast<EnsureAuthorizedProc>(ResolveProtectedEnsureAuthorized(module));
    if (ensureAuthorized == NULL)
    {
        ShowLicenseDeniedMessage(displayName, L"License component entry is invalid.");
        return false;
    }

        const int ok = ensureAuthorized(featureCode, displayName, message, static_cast<int>(sizeof(message) / sizeof(message[0])));
    const int ok2 = ok == 1 ? ensureAuthorized(featureCode, displayName, message, static_cast<int>(sizeof(message) / sizeof(message[0]))) : ok;
    if (ok != 1 || ok2 != 1)
    {
        ShowLicenseDeniedMessage(displayName, message[0] != L'\0' ? message : L"License check failed.");
        return false;
    }

    return true;
}
}
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    if (!zhihui_license_guard::EnsureAuthorized(L"ZHIHUI.SOUDONZUANBANJIN", L"SouDonZuanBanJin"))
    {
        return;
    }

    SetAttr *theSetAttr = NULL;
    try
    {
        theSetAttr = new SetAttr();
        // The following method shows the dialog immediately
        theSetAttr->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SetAttr::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theSetAttr != NULL)
    {
        delete theSetAttr;
        theSetAttr = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SetAttr::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int SetAttr::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SetAttr::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void SetAttr::initialize_cb()
{
    try
    {
        toggle01 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle01"));
        group4 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group4"));
        string04 = dynamic_cast<NXOpen::BlockStyler::StringBlock*>(theDialog->TopBlock()->FindBlock("string04"));
        string05 = dynamic_cast<NXOpen::BlockStyler::StringBlock*>(theDialog->TopBlock()->FindBlock("string05"));
        toggle02 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle02"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        toggle0 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle0"));
        string0 = dynamic_cast<NXOpen::BlockStyler::StringBlock*>(theDialog->TopBlock()->FindBlock("string0"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        vector0 = dynamic_cast<NXOpen::BlockStyler::SpecifyVector*>(theDialog->TopBlock()->FindBlock("vector0"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        CaiLiao = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("CaiLiao"));
        SuLian = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("SuLian"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        JianBan = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("JianBan"));
        ConCuan = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("ConCuan"));
        JiGuan = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("JiGuan"));
        ZeWan = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("ZeWan"));
        HanJie = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("HanJie"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        string01 = dynamic_cast<NXOpen::BlockStyler::StringBlock*>(theDialog->TopBlock()->FindBlock("string01"));
        string02 = dynamic_cast<NXOpen::BlockStyler::StringBlock*>(theDialog->TopBlock()->FindBlock("string02"));
        string03 = dynamic_cast<NXOpen::BlockStyler::StringBlock*>(theDialog->TopBlock()->FindBlock("string03"));

        //设置过滤
        Selection::SelectionAction action = Selection::SelectionActionClearAndEnableSpecific;
        std::vector<Selection::MaskTriple> maskArray(1);
        maskArray[0] = Selection::MaskTriple(UF_solid_type, UF_solid_body_subtype, UF_UI_SEL_FEATURE_ANY_FACE); // 面
        selection0->GetProperties()->SetSelectionFilter("SelectionFilter", action, maskArray);

        //------------------------------------------------------------------------------
        //Registration of StringBlock specific callbacks
        //------------------------------------------------------------------------------
        //string04->SetKeystrokeCallback(make_callback(this, &SetAttr::KeystrokeCallback));
        
        //------------------------------------------------------------------------------
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SetAttr::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}
//初始化
NXOpen::Session* theSession = NXOpen::Session::GetSession();
NXOpen::Part* workPart(theSession->Parts()->Work());
NXOpen::Part* displayPart(theSession->Parts()->Display());
NXOpen::Features::Feature* feature1;
NXOpen::Body* Body1;
NXOpen::Features::Feature* feature3;

std::vector<NXOpen::TaggedObject*> objects1a;
//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void SetAttr::dialogShown_cb()
{
    try
    {
        //获取编号开关值

        PropertyList* toggle0Props = toggle0->GetProperties();
        int Thetoggle0 = toggle0Props->GetLogical("Value");
        delete toggle0Props;
        toggle0Props = NULL;
        if (Thetoggle0 == true)
        {
            string0->SetShow(true);
        }
        else
        {
            string0->SetShow(false);
        }

        //获取编号开关值
        PropertyList* toggle01Props = toggle01->GetProperties();
        int Thetoggle01 = toggle01Props->GetLogical("Value");
        delete toggle01Props;
        toggle01Props = NULL;
        if (Thetoggle01 == true)
        {
            group1->SetShow(false);
            group4->SetShow(true);

        }
        else
        {
            group1->SetShow(true);
            group4->SetShow(false);

        }
        std::vector<NXObject::AttributeInformation>VAttr;
        VAttr=workPart->GetAttributeTitlesByType(NXObject::AttributeType::AttributeTypeString);
        
        for (size_t i = 0; i < VAttr.size(); i++)
        {
            if (strcmp(VAttr[i].Title.GetLocaleText(), "材料") == 0)
            {
                NXString CaiZi = workPart->GetStringAttribute("材料");
                PropertyList* string04Props = string04->GetProperties();
                string04Props->SetString("Value", CaiZi);
                delete string04Props;
                string04Props = NULL;
            }
            if (strcmp(VAttr[i].Title.GetLocaleText(), "数量") == 0)
            {
                NXString SuLian = workPart->GetStringAttribute("数量");
                PropertyList* string05Props = string05->GetProperties();
                string05Props->SetString("Value", "1");
                delete string05Props;
                string05Props = NULL;
            }

        }  

        toggle02->SetValue(false);
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SetAttr::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int SetAttr::apply_cb()
{
    int errorCode = 0;
    try
    {
        UF_initialize();

        //获取零件编号
        PropertyList* string0Props = string0->GetProperties();
        NXString Thestring0 = string0Props->GetString("Value");
        delete string0Props;
        string0Props = NULL;

        //获取材料
        PropertyList* CaiLiaoProps = CaiLiao->GetProperties();
        NXString TheCaiLiao = CaiLiaoProps->GetEnumAsString("Value");
        delete CaiLiaoProps;
        CaiLiaoProps = NULL;

        //获取数量
        PropertyList* SuLianProps = SuLian->GetProperties();
        NXString TheSuLian = SuLianProps->GetEnumAsString("Value");
        delete SuLianProps;
        CaiLiaoProps = NULL;


        //获取剪板开关值
        PropertyList* JianBanProps = JianBan->GetProperties();
        int TheJianBan = JianBanProps->GetLogical("Value");
        delete JianBanProps;
        JianBanProps = NULL;

        //获取冲床开关值
        PropertyList* ConCuanProps = ConCuan->GetProperties();
        int TheConCuan = ConCuanProps->GetLogical("Value");
        delete ConCuanProps;
        ConCuanProps = NULL;


        //获取激光开关值
        PropertyList* JiGuanProps = JiGuan->GetProperties();
        int TheJiGuan = JiGuanProps->GetLogical("Value");
        delete JiGuanProps;
        JiGuanProps = NULL;


        //获取折弯开关值
        PropertyList* ZeWanProps = ZeWan->GetProperties();
        int TheZeWan = ZeWanProps->GetLogical("Value");
        delete ZeWanProps;
        ZeWanProps = NULL;


        //获取焊接开关值
        PropertyList* HanJieProps = HanJie->GetProperties();
        int TheHanJie = HanJieProps->GetLogical("Value");
        delete HanJieProps;
        HanJieProps = NULL;

        //获取编号开关值
        PropertyList* toggle0Props = toggle0->GetProperties();
        int Thetoggle0 = toggle0Props->GetLogical("Value");
        delete toggle0Props;
        toggle0Props = NULL;

        //设置零件名称
        if (Thetoggle0 == true&& Body1->HasUserAttribute("bianhao", NXObject::AttributeType::AttributeTypeString, -1) == false)
        {
            UF_OBJ_set_name(bodytag, Thestring0.GetLocaleText());

            char* charbianhao = (char*)Thestring0.GetLocaleText();//nxchar*转换为ufchar*
            string strbianhao = charbianhao;//char*转换为string
            //const char* ab = strbianhao.c_str();//string转换为char*

            string strbianhao1 = strbianhao;

            string strbianhaotwo, strbianhaoone;
            strbianhaotwo = strbianhao.erase(0, strbianhao.length() - 2);//删除最后两位字符串前面的字符
            strbianhaoone = strbianhao.erase(0, strbianhao.length() - 1);//删除最后1位字符串前面的字符
           // double or = stod(strbianhaotwo, 0);//string转double
            //double or1 = stod(strbianhaoone, 0);//string转double
            int ot = stoi(strbianhaotwo, 0, 10);//string转int
            int ot1 = stoi(strbianhaoone, 0, 10);//string转int
            if (ot > 8)
            {
                int ca = ot + 1;
                char cb[25];
                itoa(ca, cb, 10);//int转char*
                string dd = cb;
                strbianhao1.erase(strbianhao1.length() - 2, 2);
                string newbianhao = strbianhao1 + dd;
                //string转换为char*
                const char* ab = newbianhao.c_str();

                PropertyList* string0Props = string0->GetProperties();
                string0Props->SetString("Value", ab);
                delete string0Props;
                string0Props = NULL;

                //  UF_UI_open_listing_window();
                //  UF_UI_write_listing_window(ab);
            }
            else
            {
                int ca = ot1 + 1;
                char cb[25];
                itoa(ca, cb, 10);
                string dd = cb;
                strbianhao1.erase(strbianhao1.length() - 1, 1);
                string newbianhao = strbianhao1 + dd;
                //string转换为char*
                const char* ab = newbianhao.c_str();

                PropertyList* string0Props = string0->GetProperties();
                string0Props->SetString("Value", ab);
                delete string0Props;
                string0Props = NULL;
            }

        }

        //获得展开Z
        PropertyList* string03Props1 = string03->GetProperties();
        NXString Thestring03 = string03Props1->GetString("Value");
        delete string03Props1;
        string03Props1 = NULL;




        //设置零件属性
        //设置材料属性

        //获取编号开关值
        PropertyList* toggle01Props = toggle01->GetProperties();
        int Thetoggle01 = toggle01Props->GetLogical("Value");
        delete toggle01Props;
        toggle01Props = NULL;
        if (Thetoggle01 == true)
        {
            PropertyList* string04Props = string04->GetProperties();
            NXString Thestring04 = string04Props->GetString("Value");
            delete string04Props;
            string04Props = NULL;

            PropertyList* string05Props = string05->GetProperties();
            NXString Thestring05 = string05Props->GetString("Value");
            delete string05Props;
            string05Props = NULL;

            UF_ATTR_value_t value;
            value.type = UF_ATTR_string;

            //设置材料属性
            value.value.string = (char*)(Thestring04.GetLocaleText());
            UF_ATTR_assign(bodytag, "cailiao", value);
            value.type = UF_ATTR_integer;
            //设置数量属性
            if (Body1->HasUserAttribute("sulian", NXObject::AttributeType::AttributeTypeInteger, -1)==false)
            {
                value.value.integer = atoi((char*)(Thestring05.GetLocaleText()));//char*转int
                UF_ATTR_assign(bodytag, "sulian", value);
            }


        }
        else
        {
            UF_ATTR_value_t value;
            value.type = UF_ATTR_string;

            //设置材料属性

            value.value.string = (char*)(TheCaiLiao.GetLocaleText());
            UF_ATTR_assign(bodytag, "cailiao", value);

            //设置数量属性
            if (Body1->HasUserAttribute("sulian", NXObject::AttributeType::AttributeTypeInteger, -1) == false)
            {
                value.value.string = (char*)(TheSuLian.GetLocaleText());
                UF_ATTR_assign(bodytag, "sulian", value);
            }
        }

        UF_ATTR_value_t value;
        value.type = UF_ATTR_string;

        //设置编号属性
        if (Thetoggle0 == true && Body1->HasUserAttribute("bianhao", NXObject::AttributeType::AttributeTypeString, -1) == false)
        {
            value.value.string = (char*)(Thestring0.GetLocaleText());
            UF_ATTR_assign(bodytag, "bianhao", value);
        }

        //设置展开Z
        value.value.string = (char*)(Thestring03.GetLocaleText());
        UF_ATTR_assign(bodytag, "Z", value);

        //设置剪板属性

        if (TheJianBan == true)
        {
            UF_ATTR_value_t value1;
            value1.type = UF_ATTR_string;
            value1.value.string = "Y";
            UF_ATTR_assign(bodytag, "jianban", value1);

        }
        else
        {
            UF_ATTR_value_t value1;
            value1.type = UF_ATTR_string;
            value1.value.string = "";
            UF_ATTR_assign(bodytag, "jianban", value1);
        }

        //设置冲床属性

        if (TheConCuan == true)
        {
            UF_ATTR_value_t value2;
            value2.type = UF_ATTR_string;
            value2.value.string = "Y";
            UF_ATTR_assign(bodytag, "concuan", value2);

        }
        else
        {
            UF_ATTR_value_t value2;
            value2.type = UF_ATTR_string;
            value2.value.string = "";
            UF_ATTR_assign(bodytag, "concuan", value2);
        }


        //设置激光属性

        if (TheJiGuan == true)
        {
            UF_ATTR_value_t value3;
            value3.type = UF_ATTR_string;
            value3.value.string = "Y";
            UF_ATTR_assign(bodytag, "jiguan", value3);

        }
        else
        {
            UF_ATTR_value_t value3;
            value3.type = UF_ATTR_string;
            value3.value.string = "";
            UF_ATTR_assign(bodytag, "jiguan", value3);
        }

        //设置折弯属性

        if (TheZeWan == true)
        {
            UF_ATTR_value_t value4;
            value4.type = UF_ATTR_string;
            value4.value.string = "Y";
            UF_ATTR_assign(bodytag, "折弯", value4);

        }
        else
        {
            UF_ATTR_value_t value4;
            value4.type = UF_ATTR_string;
            value4.value.string = "";
            UF_ATTR_assign(bodytag, "zewan", value4);
        }


        //设置焊接属性

        if (TheHanJie == true)
        {
            UF_ATTR_value_t value5;
            value5.type = UF_ATTR_string;
            value5.value.string = "Y";
            UF_ATTR_assign(bodytag, "zewan", value5);

        }
        else
        {
            UF_ATTR_value_t value5;
            value5.type = UF_ATTR_string;
            value5.value.string = "";
            UF_ATTR_assign(bodytag, "hanjie", value5);
        }

        PropertyList* toggle02Props = toggle02->GetProperties();
        int Thetoggle02 = toggle02Props->GetLogical("Value");
        delete toggle02Props;
        toggle02Props = NULL;

        if (Thetoggle02 == true)
        {
            UF_ATTR_value_t value6;
            value6.type = UF_ATTR_string;
            value6.value.string = "对称折";
            UF_ATTR_assign(bodytag, "MIRR", value6);
        }
        else
        {
            UF_ATTR_value_t value6;
            value6.type = UF_ATTR_string;
            value6.value.string = "";
            UF_ATTR_assign(bodytag, "MIRR", value6);
        }

        PropertyList* string01Props = string01->GetProperties();
        string01Props->SetString("Value", NULL);
        delete string01Props;
        string01Props = NULL;

        PropertyList* string02Props = string02->GetProperties();
        string02Props->SetString("Value", NULL);
        delete string02Props;
        string02Props = NULL;

        PropertyList* string03Props = string03->GetProperties();
        string03Props->SetString("Value", NULL);
        delete string02Props;
        string03Props = NULL;

       // UF_OBJ_delete_object(bodytag2);
       // UF_OBJ_delete_object(feature2->Tag());

        int Body1ID = 0;
        //Body1->GetReferenceAttribute("BodyID");

        char ExName1Y[256];
        char ExName1YY[256];
        char ExName1[256];
        char ExName1X[256];
        char ExName1XX[256];
        char ExName2[256];
        char SuLian[256];
        char ZSuLian[256];
        int ddd = 0;
        vector<Expression*> VExp = workPart->Expressions()->GetVisibleExpressions();
        vector <NXObject::AttributeInformation> AADD = Body1->GetAttributeTitlesByType(NXObject::AttributeType::AttributeTypeInteger);
        for (size_t i = 0; i < AADD.size(); i++)
        {
            if (strcmp(AADD[i].Title.GetLocaleText(), "BodyID") == 0)
            {
                i = AADD.size();
                Body1ID = Body1->GetIntegerAttribute("BodyID");

                sprintf(ExName1Y, "Y_%d", Body1ID);
                sprintf(ExName1YY, "YY_%d", Body1ID);
                sprintf(ExName1X, "X_%d", Body1ID);
                sprintf(ExName1XX, "XX_%d", Body1ID);
                sprintf(SuLian, "SuLian_%d", Body1ID);
                sprintf(ZSuLian, "ZSuLian_%d", Body1ID);

                for (size_t iq = 0; iq < VExp.size(); iq++)
                {
                    if (strcmp(VExp[iq]->Name().GetLocaleText(), ExName1Y) == 0)
                    {
                        iq = VExp.size();
                        NXOpen::Expression* expression1(dynamic_cast<NXOpen::Expression*>(workPart->Expressions()->FindObject(ExName1YY)));
                        workPart->Expressions()->Delete(expression1);
                        NXOpen::Expression* expression2(dynamic_cast<NXOpen::Expression*>(workPart->Expressions()->FindObject(ExName1Y)));
                        workPart->Expressions()->Delete(expression2);
                        NXOpen::Expression* expression3(dynamic_cast<NXOpen::Expression*>(workPart->Expressions()->FindObject(ExName1XX)));
                        workPart->Expressions()->Delete(expression3);
                        NXOpen::Expression* expression4(dynamic_cast<NXOpen::Expression*>(workPart->Expressions()->FindObject(ExName1X)));
                        workPart->Expressions()->Delete(expression4);
                        NXOpen::Expression* expression5(dynamic_cast<NXOpen::Expression*>(workPart->Expressions()->FindObject(ZSuLian)));
                        workPart->Expressions()->Delete(expression5);
                        NXOpen::Expression* expression6(dynamic_cast<NXOpen::Expression*>(workPart->Expressions()->FindObject(SuLian)));
                        workPart->Expressions()->Delete(expression6);

                    }

                }

            }

        }



            srand(time(0));
            Body1ID = (rand() % 9001) + 999;//生成4位随机数
            char CharBody1ID[256];
            itoa(Body1ID, CharBody1ID, 10);//int转char*
            NXOpen::AttributePropertiesBuilder* attributePropertiesBuilder1;
            std::vector<NXOpen::NXObject*> objects1(1);
            objects1[0] = Body1;
            attributePropertiesBuilder1 = theSession->AttributeManager()->CreateAttributePropertiesBuilder(workPart, objects1, NXOpen::AttributePropertiesBuilder::OperationTypeNone);
            attributePropertiesBuilder1->SetTitle("BodyID");

            attributePropertiesBuilder1->SetDataType(NXOpen::AttributePropertiesBaseBuilder::DataTypeOptionsInteger);
            attributePropertiesBuilder1->SetIntegerValue(Body1ID);
            NXOpen::NXObject* nXObject1;
            nXObject1 = attributePropertiesBuilder1->Commit();
            attributePropertiesBuilder1->Destroy();

        NXOpen::Expression* expression1Y;
        NXOpen::Expression* expression1YY;
        NXOpen::Expression* expression1X;
        NXOpen::Expression* expression1XX;
        NXOpen::Expression* expsuLian;
        NXOpen::Expression* expZsuLian;
        NXOpen::Unit* nullNXOpen_Unit(NULL);

        sprintf(ExName1Y, "Y_%d", Body1ID);
        sprintf(ExName1YY, "YY_%d", Body1ID);
        sprintf(ExName1X, "X_%d", Body1ID);
        sprintf(ExName1XX, "XX_%d", Body1ID);
        sprintf(SuLian, "SuLian_%d", Body1ID);

        expression1Y = workPart->Expressions()->GetAttributeExpression(feature3, "Minimum Y", NXOpen::NXObject::AttributeTypeReal, -1);
        sprintf(ExName1, "YY_%d=ROUND(%s)", Body1ID, ExName1Y);
        expression1Y->SetName(ExName1Y);
        expression1YY = workPart->Expressions()->CreateExpressionWithUnit("Integer", ExName1, nullNXOpen_Unit);

        expression1X = workPart->Expressions()->GetAttributeExpression(feature3, "Minimum X", NXOpen::NXObject::AttributeTypeReal, -1);
        sprintf(ExName2, "XX_%d=ROUND(%s)", Body1ID, ExName1X);
        expression1X->SetName(ExName1X);
        expression1XX = workPart->Expressions()->CreateExpressionWithUnit("Integer", ExName2, nullNXOpen_Unit);
        expsuLian = workPart->Expressions()->GetAttributeExpression(Body1, "sulian", NXOpen::NXObject::AttributeTypeInteger, -1);
        expsuLian->SetName(SuLian);
        sprintf(ZSuLian, "ZSuLian_%d=数量*%s", Body1ID, SuLian);
        expZsuLian = workPart->Expressions()->CreateExpressionWithUnit("Integer", ZSuLian, nullNXOpen_Unit);


        UF_terminate();

    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        SetAttr::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int SetAttr::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == toggle01)
        {
            //获取编号开关值
            PropertyList* toggle01Props = toggle01->GetProperties();
            int Thetoggle01 = toggle01Props->GetLogical("Value");
            delete toggle01Props;
            toggle01Props = NULL;
            if (Thetoggle01 == true)
            {
                group1->SetShow(false);
                group4->SetShow(true);

            }
            else
            {
                group1->SetShow(true);
                group4->SetShow(false);

            }

        }
        else if(block == string04)
        {
        //---------Enter your code here-----------
        }
        else if(block == string05)
        {
        //---------Enter your code here-----------
        }
        else if (block == toggle02)
        {
        //---------Enter your code here-----------
        }
        else if(block == toggle0)
        {
            //获取编号开关值
            PropertyList* toggle0Props = toggle0->GetProperties();
            int Thetoggle0 = toggle0Props->GetLogical("Value");
            delete toggle0Props;
            toggle0Props = NULL;
            if (Thetoggle0 == true)
            {
                string0->SetShow(true);
            }
            else
            {

                string0->SetShow(false);
            }        

        }
        else if(block == string0)
        {
        //---------Enter your code here-----------
        }
        else if(block == selection0)
        {
            UF_initialize();

            PropertyList* selection0Props = selection0->GetProperties();
            std::vector<NXOpen::TaggedObject*> face = selection0Props->GetTaggedObjectVector("SelectedObjects");
            delete selection0Props;
            selection0Props = NULL;

            facetag = face[0]->Tag();
            UF_MODL_ask_face_body(facetag, &bodytag);

            Body1 = (dynamic_cast<NXOpen::Body*>(NXOpen::NXObjectManager::Get(bodytag)));

            if (Body1->HasUserAttribute("sulian", NXObject::AttributeType::AttributeTypeInteger,-1))
            {
                int SuLian = Body1->GetIntegerAttribute("sulian");
                std::string strsulian = std::to_string(SuLian);
                PropertyList* string05Props = string05->GetProperties();
                string05Props->SetString("Value", strsulian);//int转string
                delete string05Props;
                string05Props = NULL;
            }

            if (Body1->HasUserAttribute("bianhao", NXObject::AttributeType::AttributeTypeString, -1))
            {
                NXString strbianhao = Body1->GetStringAttribute("bianhao");           
                PropertyList* string0Props = string0->GetProperties();
                string0Props->SetString("Value", strbianhao);//int转string
                delete string0Props;
                string0Props = NULL;
            }

            int layer1=Body1->Layer();
            if (layer1==1)
            {
                std::vector<NXOpen::DisplayableObject*> objectArray1(1);
                objectArray1[0] = Body1;
                workPart->Layers()->MoveDisplayableObjects(10, objectArray1);
            }


            //实体转换钣金
           
            workPart->Preferences()->PartSheetmetal()->SetBendRadius(false, "0.2");

            NXOpen::Features::Feature* nullNXOpen_Features_Feature(NULL);
            NXOpen::Features::SheetMetal::ConvertToSheetmetalBuilder* convertToSheetmetalBuilder1;
            convertToSheetmetalBuilder1 = workPart->Features()->SheetmetalManager()->CreateConvertToSheetmetalFeatureBuilder(nullNXOpen_Features_Feature);
            convertToSheetmetalBuilder1->SetApplicationContext(NXOpen::Features::SheetMetal::ApplicationContextNxSheetMetal);
            convertToSheetmetalBuilder1->SetBendReliefType(NXOpen::Features::SheetMetal::ConvertToSheetmetalBuilder::BendReliefTypeOptionsSquare);
            NXOpen::Expression* expression1;
            expression1 = convertToSheetmetalBuilder1->BendReliefDepth();
            expression1->SetRightHandSide("0.2");
            NXOpen::Expression* expression2;
            expression2 = convertToSheetmetalBuilder1->BendReliefWidth();
            expression2->SetRightHandSide("0.2");
            NXOpen::Face* nullNXOpen_Face(NULL);
            convertToSheetmetalBuilder1->SetBaseFace(nullNXOpen_Face);
            NXOpen::Face* face2(dynamic_cast<NXOpen::Face*>(NXOpen::NXObjectManager::Get(facetag)));//强制转换为NX对象
            convertToSheetmetalBuilder1->SetBaseFace(face2);
            feature1 = convertToSheetmetalBuilder1->CommitFeature();
            convertToSheetmetalBuilder1->Destroy();
            theSession->CleanUpFacetedFacesAndEdges();
            
            std::vector<Face*> feature1Face;
           double z = workPart->Features()->SheetmetalManager()->GetBodyThickness(face2->GetBody());//获得钣金厚度
           char charZ[256];
           sprintf(charZ, "%.1f", z);

           PropertyList* string03Props = string03->GetProperties();
           string03Props->SetString("Value", charZ);
           delete string03Props;
           string03Props = NULL;

            std::vector<NXOpen::Features::SheetMetal::SheetmetalBendState> cdcd;
            workPart->Features()->SheetmetalManager()->GetInnerBendFaces(face2->GetBody(), feature1Face, cdcd);//获得弯曲的内R面


           std::vector<Face*> feature1Face1;
           for (size_t i = 0; i < feature1Face.size(); i++)
           {
               int type1, norm_dir;
               double point[3], dir[3], box[6], radius, rad_data;
               UF_MODL_ask_face_data(feature1Face[i]->Tag(), &type1, point, dir, box, &radius, &rad_data, &norm_dir);//查询面的数据

               if (radius>2.5)
               {

                   feature1Face1.push_back(feature1Face[i]);
               }
               else
               {
                   std::vector<Edge*> VEdge11;
                   VEdge11 = feature1Face[i]->GetEdges();
                   int len = 0;
                   int len1 = 0;
                   for (size_t CC = 0; CC < VEdge11.size(); CC++)
                   {
                       //曲线初始化
                       UF_EVAL_p_t evaluator1;
                       bool is_arc;

                       UF_EVAL_initialize(VEdge11[CC]->Tag(), &evaluator1);
                       UF_EVAL_is_arc(evaluator1, &is_arc);//判断曲线是否为直线

                       if (is_arc)
                       {
                           if (fabs(VEdge11[CC]->GetLength() - radius * 3.1415926) < 0.001)
                           {
                               feature1Face1.push_back(feature1Face[i]);
                               CC = VEdge11.size();
                               len = 1;
                           }
                       }

                   }
                   for (size_t CC = 0; CC < VEdge11.size(); CC++)
                   {
                       if (VEdge11[CC]->GetLength() > 1650)
                       {
                           len1 = 1;
                       }
                       if (VEdge11[CC]->GetLength() > 2000&& fabs(z-3)<0.001)
                       {
                           char ShuLiang[256];
                           sprintf(ShuLiang, "%s\n", "3.0厚折弯长度不可大于2000");
                           UF_UI_open_listing_window();
                           UF_UI_write_listing_window(ShuLiang);
                       }
                       if (VEdge11[CC]->GetLength() > 1200 && fabs(z - 5) < 0.001)
                       {
                           char ShuLiang[256];
                           sprintf(ShuLiang, "%s\n", "5.0厚折弯长度不可大于1200");
                           UF_UI_open_listing_window();
                           UF_UI_write_listing_window(ShuLiang);
                       }

                       NXString CaiZi = workPart->GetStringAttribute("材料");//获取材料
                       if (VEdge11[CC]->GetLength() > 1550 && fabs(z - 3) < 0.001 &&(strcmp(CaiZi.GetLocaleText(), "201不锈钢") == 0|| strcmp(CaiZi.GetLocaleText(), "202不锈钢") == 0|| strcmp(CaiZi.GetLocaleText(), "304不锈钢") == 0
                           || strcmp(CaiZi.GetLocaleText(), "304拉丝不锈钢") == 0|| strcmp(CaiZi.GetLocaleText(), "201拉丝不锈钢") == 0|| strcmp(CaiZi.GetLocaleText(), "202拉丝不锈钢") == 0|| strcmp(CaiZi.GetLocaleText(), "镜面304不锈钢") == 0))
                       {
                           char ShuLiang[256];
                           sprintf(ShuLiang, "%s\n", "3.0厚不锈钢折弯长度不可大于1550");
                           UF_UI_open_listing_window();
                           UF_UI_write_listing_window(ShuLiang);
                       }


                       if (VEdge11[CC]->GetLength() > 600 && z>3.5&&( strcmp(CaiZi.GetLocaleText(), "201不锈钢") == 0 || strcmp(CaiZi.GetLocaleText(), "202不锈钢") == 0 || strcmp(CaiZi.GetLocaleText(), "304不锈钢") == 0
                           || strcmp(CaiZi.GetLocaleText(), "304拉丝不锈钢") == 0 || strcmp(CaiZi.GetLocaleText(), "201拉丝不锈钢") == 0 || strcmp(CaiZi.GetLocaleText(), "202拉丝不锈钢") == 0 || strcmp(CaiZi.GetLocaleText(), "镜面304不锈钢") == 0))
                       {
                           char ShuLiang[256];
                           sprintf(ShuLiang, "%s\n", "厚度>4.0的不锈钢长度超过600问折弯是否可以折得动");
                           UF_UI_open_listing_window();
                           UF_UI_write_listing_window(ShuLiang);
                       }

                   }
                   if (len==1&&len1 == 1)
                   {
                       char ShuLiang[256];
                       sprintf(ShuLiang, "%s\n", "压死边长度不可大于1650");
                       UF_UI_open_listing_window();
                       UF_UI_write_listing_window(ShuLiang);
                   }
               }
           }
           if (feature1Face1.size()>0)
           {

           NXOpen::Features::SheetMetal::ResizeNeutralFactorBuilder* resizeNeutralFactorBuilder1;
           resizeNeutralFactorBuilder1 = workPart->Features()->SheetmetalManager()->CreateResizeNeutralFactorBuilder(nullNXOpen_Features_Feature);
           resizeNeutralFactorBuilder1->NeutralFactor()->SetFormula("0.5");

           NXOpen::SelectionIntentRuleOptions* selectionIntentRuleOptions1;
           selectionIntentRuleOptions1 = workPart->ScRuleFactory()->CreateRuleOptions();
           selectionIntentRuleOptions1->SetSelectedFromInactive(false);

           NXOpen::FaceDumbRule* faceDumbRule1;
           faceDumbRule1 = workPart->ScRuleFactory()->CreateRuleFaceDumb(feature1Face1, selectionIntentRuleOptions1);
           delete selectionIntentRuleOptions1;

           std::vector<NXOpen::SelectionIntentRule*> rules1(1);
           rules1[0] = faceDumbRule1;
           resizeNeutralFactorBuilder1->BendFaces()->ReplaceRules(rules1, false);

           NXOpen::Features::Feature* feature1aa;
           feature1aa = resizeNeutralFactorBuilder1->CommitFeature();
           theSession->CleanUpFacetedFacesAndEdges();
           }
            //获取剪板开关值
            PropertyList* JianBanProps = JianBan->GetProperties();
            int TheJianBan = JianBanProps->GetLogical("Value");
            delete JianBanProps;
            JianBanProps = NULL;

            if (TheJianBan)
            {
                baobian();
            }
            UF_terminate();

        }
        else if(block == vector0)
        {
            UF_initialize();
            //初始化
            NXOpen::Session* theSession = NXOpen::Session::GetSession();
            NXOpen::Part* workPart(theSession->Parts()->Work());
            NXOpen::Part* displayPart(theSession->Parts()->Display());

            //获取UI界面的值
            PropertyList* selection01Props = vector0->GetProperties();
            std::vector<NXOpen::TaggedObject*> vect = selection01Props->GetTaggedObjectVector("SelectedObjects");
            delete selection01Props;
            selection01Props = NULL;
            //获取TGA
            tag_t vecttag = vect[0]->Tag();
            NXOpen::Face* face1(dynamic_cast<NXOpen::Face*>(NXOpen::NXObjectManager::Get(facetag)));
            NXOpen::Direction* direction1(dynamic_cast<NXOpen::Direction*>(NXOpen::NXObjectManager::Get(vecttag)));

            NXOpen::Scalar* scalar1, * scalar2;
            scalar1 = workPart->Scalars()->CreateScalar(0.5, NXOpen::Scalar::DimensionalityTypeNone, NXOpen::SmartObject::UpdateOptionAfterModeling);
            scalar2 = workPart->Scalars()->CreateScalar(0.5, NXOpen::Scalar::DimensionalityTypeNone, NXOpen::SmartObject::UpdateOptionAfterModeling);

            NXOpen::Point* point1;
            point1 = workPart->Points()->CreatePoint(face1, scalar1, scalar2, NXOpen::SmartObject::UpdateOptionAfterModeling);

            NXOpen::Point3d origin5 = point1->Coordinates();

            int Type, NormDir;
            double Point[3], Dir[3], Box[6], Radius[3], RadData[3];
            UF_MODL_ask_face_data(facetag, &Type, Point, Dir, Box, Radius, RadData, &NormDir);

            NXOpen::Vector3d normal5;
            if (Type != 16)//判断面是否是圆柱面
            {
              normal5 = { Dir[0],Dir[1],Dir[2] };
            }
            else
            {
                double uvs[4];
                UF_MODL_ask_face_uv_minmax(facetag, uvs);
                double param[2]; //输入U,V方向值
                param[0] = (uvs[0] + uvs[1]) / 2;
                param[1] = (uvs[2] + uvs[3]) / 2;
                double point[3]; //输出点坐标
                double u1[3]; //输出 输出一阶导数在U位置
                double v1[3]; //输出 输出一阶导数在V位置
                double u2[3]; //输出 输出二阶导数在U位置
                double v2[3]; //输出 输出二阶导数在V位置
                double unit_norm[3]; //输出面上该点的矢量方向
                double radii[2]; //输出，双半径，输出主曲率半径
                UF_MODL_ask_face_props(facetag, param, point, u1, v1, u2, v2, unit_norm, radii);
                normal5 = { unit_norm[0] ,unit_norm[1],unit_norm[2] };
            }
            NXOpen::Plane* plane1;
            plane1 = workPart->Planes()->CreatePlane(origin5, normal5, NXOpen::SmartObject::UpdateOptionAfterModeling);



            NXOpen::Xform* xform1;
            xform1 = workPart->Xforms()->CreateXformByPlaneXDirPoint(plane1, direction1, point1, NXOpen::SmartObject::UpdateOptionAfterModeling, 1.0, false, false);

            NXOpen::CartesianCoordinateSystem* cartesianCoordinateSystem1;
            cartesianCoordinateSystem1 = workPart->CoordinateSystems()->CreateCoordinateSystem(xform1, NXOpen::SmartObject::UpdateOptionAfterModeling);
            workPart->WCS()->SetCoordinateSystemCartesianAtCsys(cartesianCoordinateSystem1);
            NXOpen::CartesianCoordinateSystem* OriginalWcsData = workPart->WCS()->CoordinateSystem();

            //钣金实体展开
			NXOpen::Features::Feature* nullNXOpen_Features_Feature(NULL);


            NXOpen::Features::SheetMetal::FlatPatternBuilder* flatPatternBuilder1;
            flatPatternBuilder1 = workPart->Features()->SheetmetalManager()->CreateFlatPatternBuilder(nullNXOpen_Features_Feature);
            flatPatternBuilder1->SetApplicationContext(NXOpen::Features::SheetMetal::ApplicationContextNxSheetMetal);
            flatPatternBuilder1->SetOrientation(NXOpen::Features::SheetMetal::FlatSolidBuilder::OrientationTypeCsys);
            flatPatternBuilder1->OuterCornerTreatment()->SetTreatmentType(NXOpen::Features::SheetMetal::CornerTreatmentBuilder::CornerTreatmentTypeRadius);
            flatPatternBuilder1->OuterCornerTreatment()->Value()->SetFormula("1");
            flatPatternBuilder1->UpwardFace()->SetValue(face1);
            flatPatternBuilder1->SetOrientationCsys(workPart->WCS()->CoordinateSystem());

            feature3 = flatPatternBuilder1->CommitFeature();
            NXString ZanKaiViewName = flatPatternBuilder1->FlatPatternViewName();
            const char* ZKname = (char*)ZanKaiViewName.GetLocaleText();
            flatPatternBuilder1->Destroy();
            theSession->CleanUpFacetedFacesAndEdges();
            double x=feature3->GetRealAttribute("Minimum X");
            double y = feature3->GetRealAttribute("Minimum Y");



            char charX[256], charY[256],CharFaceTag[256], CharEdgeTag[256], CharZKname[256];
            sprintf(charX, "%.5f", x);
            sprintf(charY, "%.5f", y);

            sprintf(CharFaceTag, "%d", facetag);
            sprintf(CharEdgeTag, "%d", vecttag);
            sprintf(CharZKname, "%s", ZKname);
            PropertyList* string01Props = string01->GetProperties();
            string01Props->SetString("Value", charX);
            delete string01Props;
            string01Props = NULL;

            PropertyList* string02Props = string02->GetProperties();
            string02Props->SetString("Value", charY);
            delete string02Props;
            string02Props = NULL;




            UF_terminate();

        }
        else if(block == CaiLiao)
        {
        //---------Enter your code here-----------
        }
        else if(block == SuLian)
        {
        //---------Enter your code here-----------
        }
        else if (block == JianBan)
        {
        //获取剪板开关值
        PropertyList* JianBanProps = JianBan->GetProperties();
        int TheJianBan = JianBanProps->GetLogical("Value");
        delete JianBanProps;
        JianBanProps = NULL;

        if (TheJianBan)
        {
            if (facetag != NULL_TAG)
            {
                baobian();
            }
        }
        else
        {

            if (objects1a.size() > 0)
            {
                NXOpen::Session::UndoMarkId markId1;
                markId1 = theSession->SetUndoMark(NXOpen::Session::MarkVisibilityInvisible, "Delete");
                theSession->UpdateManager()->ClearErrorList();

                int nErrs1;
                nErrs1 = theSession->UpdateManager()->AddObjectsToDeleteList(objects1a);

                NXOpen::Session::UndoMarkId id1;
                id1 = theSession->NewestVisibleUndoMark();

                int nErrs2;
                nErrs2 = theSession->UpdateManager()->DoUpdate(id1);

                theSession->DeleteUndoMark(markId1, NULL);

            }
        }
        }
        else if(block == ConCuan)
        {
        //---------Enter your code here-----------
        }
        else if(block == JiGuan)
        {
        //---------Enter your code here-----------
        }
        else if(block == ZeWan)
        {
        //---------Enter your code here-----------
        }
        else if(block == HanJie)
        {
        //---------Enter your code here-----------
        }
        else if(block == string01)
        {
        //---------Enter your code here-----------
        }
        else if(block == string02)
        {
        //---------Enter your code here-----------
        }
        else if(block == string03)
        {
        //---------Enter your code here-----------
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SetAttr::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int SetAttr::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        SetAttr::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}


//------------------------------------------------------------------------------
//StringBlock specific callbacks
//------------------------------------------------------------------------------
//int SetAttr::KeystrokeCallback (NXOpen::BlockStyler::StringBlock* string_block, NXString uncommitted_value)
//{
//}

//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* SetAttr::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
void SetAttr::baobian()
{
    std::vector<Face*>Faces1 = feature1->GetFaces();
    std::vector<Face*>Faces2;



    for (size_t i = 0; i < Faces1.size(); i++)
    {
        int type1;
        double point[3];
        double dir[3];
        double box[6];
        double radius;
        double rad_data;
        int norm_dir;
        UF_MODL_ask_face_data(Faces1[i]->Tag(), &type1, point, dir, box, &radius, &rad_data, &norm_dir);//查询面的数据

        if (fabs(radius - 0.2) < 0.01)
        {

            Faces2.push_back(Faces1[i]);
        }
    }
    for (size_t i = 0; i < Faces2.size(); i++)
    {

        for (size_t b = i + 1; b < Faces2.size(); b++)
        {

            MeasureDistance* measureDistance1;
            measureDistance1 = workPart->MeasureManager()->NewDistance(NULL, MeasureManager::MeasureTypeMinimum, Faces2[i], Faces2[b]);
            double distance1 = measureDistance1->Value();//获取测量的值

            if (distance1 == 0)
            {
                NXOpen::MeasureAngle* MeasAngle1;
                MeasAngle1 = workPart->MeasureManager()->NewAngle(NULL, Faces2[i], MeasureManager::EndpointTypeStartPoint, Faces2[b], MeasureManager::EndpointTypeStartPoint, true, false);
                double Angle1 = MeasAngle1->Value();

                NXOpen::Features::Feature* nullNXOpen_Features_Feature(NULL);
                NXOpen::Features::SheetMetal::ClosedCornerBuilder* closedCornerBuilder1;
                closedCornerBuilder1 = workPart->Features()->SheetmetalManager()->CreateClosedCornerFeatureBuilder(nullNXOpen_Features_Feature);
                closedCornerBuilder1->Gap()->SetFormula("0.2");
                closedCornerBuilder1->Overlap()->SetFormula("1");
                closedCornerBuilder1->SetCutMethod(NXOpen::Features::SheetMetal::ClosedCornerBuilder::CutMethodTypesByPath);
                closedCornerBuilder1->SetOverlapType(NXOpen::Features::SheetMetal::ClosedCornerBuilder::OverlapTypeOptionsSide2);

                NXObject* nullNXObject(NULL);
                NXOpen::MeasureFaceBuilder* measureFaceBuilder1;
                measureFaceBuilder1 = workPart->MeasureManager()->CreateMeasureFaceBuilder(nullNXObject);
                std::vector<IParameterizedSurface*> objects1(1);
                objects1[0] = Faces2[i];
                MeasureFaces* measureFaces1;
                measureFaces1 = workPart->MeasureManager()->NewFaceProperties(NULL, NULL, 0.9999, objects1);
                double area1 = measureFaces1->Area();
                objects1[0] = Faces2[b];

                measureFaces1 = workPart->MeasureManager()->NewFaceProperties(NULL, NULL, 0.9999, objects1);
                double area2 = measureFaces1->Area();
                if (area1 >= area2)
                {
                    closedCornerBuilder1->AddFacePair(Faces2[i], Faces2[b]);
                }
                else
                {
                    closedCornerBuilder1->AddFacePair(Faces2[b], Faces2[i]);
                }

                NXOpen::Features::Feature* feature1a;
                feature1a = closedCornerBuilder1->CommitFeature();
                objects1a.push_back(feature1a);
            }
        }
    }

}