//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\LPOpenPrint\application\SouDonZuanBanJin.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: Administrator
//              Version: NX 1992
//              Date: 10-23-2021  (Format: mm-dd-yyyy)
//              Time: 08:26 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "SouDonZuanBanJin.hpp"
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#ifdef CreateDialog
#undef CreateDialog
#endif
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <map>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string>
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//初始化
NXOpen::Session* theSession = NXOpen::Session::GetSession();
NXOpen::Part* workPart(NULL);
NXOpen::Part* displayPart(NULL);
NXOpen::Features::Feature* feature1(NULL);
NXOpen::Body* Body1(NULL);
NXOpen::Features::Feature* feature3(NULL);
std::vector<NXOpen::TaggedObject*> objects1a;
int intVal[3] = { 0,0,0 };
std::string unfoldThickness;
bool directionEdgeRequired(false);

namespace
{
    const char* BendFactorConfigFileName = "PiLianZuanBanJin_bend_factor_config.json";

    struct BendRule
    {
        bool enabled;
        bool fallback;
        std::string name;
        std::string method;
        std::string note;
        double value;
        bool hasAngleMin;
        bool hasAngleMax;
        bool hasThicknessMin;
        bool hasThicknessMax;
        bool hasRadiusMin;
        bool hasRadiusMax;
        bool hasRadiusOverride;
        double angleMin;
        double angleMax;
        double thicknessMin;
        double thicknessMax;
        double radiusMin;
        double radiusMax;
        double radiusOverride;

        BendRule()
            : enabled(true), fallback(false), method("KFactor"), value(0.5),
              hasAngleMin(false), hasAngleMax(false), hasThicknessMin(false), hasThicknessMax(false),
              hasRadiusMin(false), hasRadiusMax(false), hasRadiusOverride(false),
              angleMin(0.0), angleMax(0.0), thicknessMin(0.0), thicknessMax(0.0),
              radiusMin(0.0), radiusMax(0.0), radiusOverride(0.0)
        {
        }
    };

    struct RuleConfig
    {
        std::vector<BendRule> rules;
        bool useAbsoluteLargeArc;
        double absoluteLargeArcRadius;
        bool useRatioLargeArc;
        double ratioLargeArc;

        RuleConfig()
            : useAbsoluteLargeArc(true), absoluteLargeArcRadius(7.0),
              useRatioLargeArc(false), ratioLargeArc(5.0)
        {
        }
    };

    struct BendFaceRecord
    {
        NXOpen::Face* face;
        double thickness;
        double innerRadius;
        double angleDeg;
        double currentK;
        double targetK;
        double targetRadius;

        BendFaceRecord()
            : face(NULL), thickness(0.0), innerRadius(0.0), angleDeg(0.0),
              currentK(0.0), targetK(0.5), targetRadius(0.0)
        {
        }
    };

    void RefreshNxContext()
    {
        theSession = NXOpen::Session::GetSession();
        workPart = theSession->Parts()->Work();
        displayPart = theSession->Parts()->Display();
        if (workPart == NULL)
        {
            throw std::runtime_error("请先打开一个工作部件。");
        }
    }

    class UfSessionGuard
    {
    public:
        UfSessionGuard()
        {
            int error = UF_initialize();
            if (error != 0)
            {
                throw std::runtime_error("UF_initialize failed: " + std::to_string(error));
            }
        }

        ~UfSessionGuard()
        {
            UF_terminate();
        }

    private:
        UfSessionGuard(const UfSessionGuard&);
        UfSessionGuard& operator=(const UfSessionGuard&);
    };

    bool GetToggleValue(NXOpen::BlockStyler::Toggle* toggle)
    {
        if (toggle == NULL)
        {
            return false;
        }
        PropertyList* props = toggle->GetProperties();
        bool value = props->GetLogical("Value");
        delete props;
        return value;
    }

    double GetDoubleValue(NXOpen::BlockStyler::DoubleBlock* block, double defaultValue)
    {
        if (block == NULL)
        {
            return defaultValue;
        }

        PropertyList* props = block->GetProperties();
        double value = props->GetDouble("Value");
        delete props;
        return value;
    }

    std::string ReadAllText(const std::string& path)
    {
        std::ifstream input(path.c_str(), std::ios::in | std::ios::binary);
        if (!input)
        {
            return std::string();
        }

        std::ostringstream buffer;
        buffer << input.rdbuf();
        return buffer.str();
    }

    std::string DirectoryName2(const std::string& fullPath)
    {
        size_t slash = fullPath.find_last_of("\\/");
        return slash == std::string::npos ? std::string(".") : fullPath.substr(0, slash);
    }

    std::string CombinePath2(const std::string& left, const std::string& right)
    {
        if (left.empty())
        {
            return right;
        }

        char tail = left[left.size() - 1];
        return (tail == '\\' || tail == '/') ? left + right : left + "\\" + right;
    }

    bool FileExists2(const std::string& path)
    {
        DWORD attrs = GetFileAttributesA(path.c_str());
        return attrs != INVALID_FILE_ATTRIBUTES && (attrs & FILE_ATTRIBUTE_DIRECTORY) == 0;
    }

    std::string ModuleDirectory2()
    {
        HMODULE selfModule = NULL;
        if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
            reinterpret_cast<LPCSTR>(&ModuleDirectory2), &selfModule))
        {
            char path[MAX_PATH] = { 0 };
            DWORD length = GetModuleFileNameA(selfModule, path, MAX_PATH);
            if (length > 0 && length < MAX_PATH)
            {
                return DirectoryName2(path);
            }
        }

        return std::string(".");
    }

    std::string FindBendFactorConfigPath()
    {
        std::string moduleDir = ModuleDirectory2();
        std::vector<std::string> paths;
        paths.push_back(CombinePath2(moduleDir, std::string("..\\config\\") + BendFactorConfigFileName));
        paths.push_back(CombinePath2(moduleDir, BendFactorConfigFileName));
        paths.push_back(std::string("D:\\UG智辉钣金插件\\config\\") + BendFactorConfigFileName);
        paths.push_back(std::string("D:\\UG智辉钣金插件\\application\\") + BendFactorConfigFileName);
        for (size_t i = 0; i < paths.size(); ++i)
        {
            if (FileExists2(paths[i]))
            {
                return paths[i];
            }
        }

        return std::string();
    }

    bool ExtractJsonBool(const std::string& text, const std::string& name, bool defaultValue)
    {
        std::regex pattern("\"" + name + "\"\\s*:\\s*(true|false)", std::regex_constants::icase);
        std::smatch match;
        if (std::regex_search(text, match, pattern))
        {
            return _stricmp(match[1].str().c_str(), "true") == 0;
        }

        return defaultValue;
    }

    double ExtractJsonNumber(const std::string& text, const std::string& name, double defaultValue)
    {
        std::regex pattern("\"" + name + "\"\\s*:\\s*(-?\\d+(?:\\.\\d+)?(?:[eE][+-]?\\d+)?|null)");
        std::smatch match;
        if (std::regex_search(text, match, pattern))
        {
            std::string value = match[1].str();
            if (value != "null" && value != "NULL")
            {
                return std::atof(value.c_str());
            }
        }

        return defaultValue;
    }

    bool TryExtractJsonNumber(const std::string& text, const std::string& name, double* value)
    {
        std::regex pattern("\"" + name + "\"\\s*:\\s*(-?\\d+(?:\\.\\d+)?(?:[eE][+-]?\\d+)?|null)");
        std::smatch match;
        if (std::regex_search(text, match, pattern))
        {
            std::string raw = match[1].str();
            if (raw != "null" && raw != "NULL")
            {
                *value = std::atof(raw.c_str());
                return true;
            }
        }

        return false;
    }

    std::string ExtractJsonString(const std::string& text, const std::string& name, const std::string& defaultValue)
    {
        std::regex pattern("\"" + name + "\"\\s*:\\s*\"([^\"]*)\"");
        std::smatch match;
        return std::regex_search(text, match, pattern) ? match[1].str() : defaultValue;
    }

    std::string ExtractArrayBody(const std::string& text, const std::string& name)
    {
        std::string token = "\"" + name + "\"";
        size_t pos = text.find(token);
        if (pos == std::string::npos)
        {
            return std::string();
        }

        size_t start = text.find('[', pos);
        if (start == std::string::npos)
        {
            return std::string();
        }

        int depth = 0;
        bool inString = false;
        bool escape = false;
        for (size_t i = start; i < text.size(); ++i)
        {
            char c = text[i];
            if (escape)
            {
                escape = false;
                continue;
            }
            if (c == '\\' && inString)
            {
                escape = true;
                continue;
            }
            if (c == '"')
            {
                inString = !inString;
                continue;
            }
            if (inString)
            {
                continue;
            }
            if (c == '[')
            {
                ++depth;
            }
            else if (c == ']')
            {
                --depth;
                if (depth == 0)
                {
                    return text.substr(start + 1, i - start - 1);
                }
            }
        }

        return std::string();
    }

    std::vector<std::string> ExtractObjectBodies(const std::string& arrayBody)
    {
        std::vector<std::string> objects;
        int depth = 0;
        bool inString = false;
        bool escape = false;
        size_t start = std::string::npos;
        for (size_t i = 0; i < arrayBody.size(); ++i)
        {
            char c = arrayBody[i];
            if (escape)
            {
                escape = false;
                continue;
            }
            if (c == '\\' && inString)
            {
                escape = true;
                continue;
            }
            if (c == '"')
            {
                inString = !inString;
                continue;
            }
            if (inString)
            {
                continue;
            }
            if (c == '{')
            {
                if (depth == 0)
                {
                    start = i;
                }
                ++depth;
            }
            else if (c == '}')
            {
                --depth;
                if (depth == 0 && start != std::string::npos)
                {
                    objects.push_back(arrayBody.substr(start, i - start + 1));
                    start = std::string::npos;
                }
            }
        }

        return objects;
    }

    bool ContainsTextNoCase(const std::string& text, const char* token)
    {
        std::string left = text;
        std::string right = token == NULL ? std::string() : std::string(token);
        std::transform(left.begin(), left.end(), left.begin(), ::tolower);
        std::transform(right.begin(), right.end(), right.begin(), ::tolower);
        return left.find(right) != std::string::npos;
    }

    bool IsAlive(tag_t tag)
    {
        return tag != NULL_TAG && UF_OBJ_ask_status(tag) == UF_OBJ_ALIVE;
    }

    std::string FormatDouble(double value, int precision)
    {
        std::ostringstream stream;
        stream << std::fixed << std::setprecision(precision) << value;
        return stream.str();
    }

    RuleConfig LoadRuleConfig()
    {
        RuleConfig config;
        std::string path = FindBendFactorConfigPath();
        std::string json = path.empty() ? std::string() : ReadAllText(path);
        if (json.empty())
        {
            return config;
        }

        config.useAbsoluteLargeArc = ExtractJsonBool(json, "UseAbsoluteRadiusThreshold", true);
        config.absoluteLargeArcRadius = ExtractJsonNumber(json, "AbsoluteRadiusThreshold", 7.0);
        config.useRatioLargeArc = ExtractJsonBool(json, "UseRadiusThicknessRatio", false);
        config.ratioLargeArc = ExtractJsonNumber(json, "RadiusThicknessRatioThreshold", 5.0);

        std::vector<std::string> ruleObjects = ExtractObjectBodies(ExtractArrayBody(json, "Rules"));
        for (size_t i = 0; i < ruleObjects.size(); ++i)
        {
            BendRule rule;
            const std::string& item = ruleObjects[i];
            rule.enabled = ExtractJsonBool(item, "Enabled", true);
            rule.fallback = ExtractJsonBool(item, "IsFallback", false);
            rule.name = ExtractJsonString(item, "RuleName", std::string());
            rule.method = ExtractJsonString(item, "Method", "KFactor");
            rule.note = ExtractJsonString(item, "Note", std::string());
            rule.value = ExtractJsonNumber(item, "Value", 0.5);
            rule.hasAngleMin = TryExtractJsonNumber(item, "AngleMinDeg", &rule.angleMin);
            rule.hasAngleMax = TryExtractJsonNumber(item, "AngleMaxDeg", &rule.angleMax);
            rule.hasThicknessMin = TryExtractJsonNumber(item, "ThicknessMin", &rule.thicknessMin);
            rule.hasThicknessMax = TryExtractJsonNumber(item, "ThicknessMax", &rule.thicknessMax);
            rule.hasRadiusMin = TryExtractJsonNumber(item, "InnerRadiusMin", &rule.radiusMin);
            rule.hasRadiusMax = TryExtractJsonNumber(item, "InnerRadiusMax", &rule.radiusMax);
            rule.hasRadiusOverride = TryExtractJsonNumber(item, "RadiusOverride", &rule.radiusOverride);
            if (rule.enabled)
            {
                config.rules.push_back(rule);
            }
        }

        return config;
    }

    bool WithinRange(double value, bool hasMin, double minValue, bool hasMax, double maxValue)
    {
        if (hasMin && value < minValue)
        {
            return false;
        }
        if (hasMax && value > maxValue)
        {
            return false;
        }
        return true;
    }

    bool IsLargeArcBend(const BendFaceRecord& record, const RuleConfig& config)
    {
        bool byAbsolute = config.useAbsoluteLargeArc &&
            config.absoluteLargeArcRadius > 0.0 &&
            record.innerRadius >= config.absoluteLargeArcRadius;
        bool byRatio = config.useRatioLargeArc &&
            config.ratioLargeArc > 0.0 &&
            record.thickness > 1e-9 &&
            record.innerRadius / record.thickness >= config.ratioLargeArc;
        return byAbsolute || byRatio;
    }

    const BendRule* MatchRule(const RuleConfig& config, const BendFaceRecord& record)
    {
        const BendRule* fallback = NULL;
        bool largeArc = IsLargeArcBend(record, config);
        for (size_t i = 0; i < config.rules.size(); ++i)
        {
            const BendRule& rule = config.rules[i];
            if (!rule.enabled)
            {
                continue;
            }
            if (rule.fallback)
            {
                fallback = &rule;
                continue;
            }

            bool pressEdgeRule = ContainsTextNoCase(rule.note, "[PressEdge]");
            bool largeArcRule = ContainsTextNoCase(rule.note, "[LargeArc]");
            bool smallArcRule = ContainsTextNoCase(rule.note, "[SmallArc]");
            if (pressEdgeRule)
            {
                continue;
            }
            if (largeArc && !largeArcRule)
            {
                continue;
            }
            if (!largeArc && largeArcRule)
            {
                continue;
            }
            if (smallArcRule && largeArc)
            {
                continue;
            }
            if (!WithinRange(record.angleDeg, rule.hasAngleMin, rule.angleMin, rule.hasAngleMax, rule.angleMax) ||
                !WithinRange(record.thickness, rule.hasThicknessMin, rule.thicknessMin, rule.hasThicknessMax, rule.thicknessMax) ||
                !WithinRange(record.innerRadius, rule.hasRadiusMin, rule.radiusMin, rule.hasRadiusMax, rule.radiusMax))
            {
                continue;
            }

            return &rule;
        }

        return fallback;
    }

    bool SafeAngleRadians(double angleDeg, double* radians)
    {
        if (radians == NULL || angleDeg <= 0.001 || angleDeg >= 179.999)
        {
            return false;
        }

        *radians = angleDeg * 3.14159265358979323846 / 180.0;
        return true;
    }

    bool CalculateTargetK(const BendRule& rule, BendFaceRecord* record)
    {
        if (record == NULL)
        {
            return false;
        }

        double effectiveRadius = rule.hasRadiusOverride ? rule.radiusOverride : record->innerRadius;
        record->targetRadius = effectiveRadius;
        if (ContainsTextNoCase(rule.method, "KFactor"))
        {
            record->targetK = rule.value;
            return record->targetK >= 0.0 && record->targetK <= 1.0;
        }

        if (!ContainsTextNoCase(rule.method, "Deduction") || record->thickness <= 0.0)
        {
            return false;
        }

        double angleRad = 0.0;
        if (!SafeAngleRadians(record->angleDeg, &angleRad))
        {
            return false;
        }

        double bendAllowance = 2.0 * (effectiveRadius + record->thickness) * std::tan(angleRad / 2.0) - rule.value;
        record->targetK = (bendAllowance / angleRad - effectiveRadius) / record->thickness;
        return !std::isnan(record->targetK) && !std::isinf(record->targetK) &&
            record->targetK >= 0.0 && record->targetK <= 1.0;
    }

    struct SheetmetalDialogOptions
    {
        double reliefDepth;
        double reliefWidth;
        double innerRadius;
        SheetmetalDialogOptions()
            : reliefDepth(0.2), reliefWidth(0.2), innerRadius(0.0)
        {
        }
    };

    void InitializeDoubleBlock(NXOpen::BlockStyler::DoubleBlock* block, double value)
    {
        if (block != NULL)
        {
            block->SetValue(value);
        }
    }

    SheetmetalDialogOptions CollectSheetmetalDialogOptions(
        NXOpen::BlockStyler::DoubleBlock* reliefDepthBlock,
        NXOpen::BlockStyler::DoubleBlock* reliefWidthBlock,
        NXOpen::BlockStyler::DoubleBlock* innerRadiusBlock)
    {
        SheetmetalDialogOptions options;
        options.reliefDepth = std::max(0.0, GetDoubleValue(reliefDepthBlock, 0.2));
        options.reliefWidth = std::max(0.0, GetDoubleValue(reliefWidthBlock, 0.2));
        options.innerRadius = std::max(0.0, GetDoubleValue(innerRadiusBlock, 0.0));
        return options;
    }

    void ApplySheetmetalPreferencesBeforeConvert(NXOpen::Part* part, const SheetmetalDialogOptions& options)
    {
        if (part == NULL)
        {
            return;
        }

        NXOpen::Preferences::SheetMetalPreferencesBuilder* prefsBuilder = NULL;
        try
        {
            NXOpen::Preferences::SheetMetalPreferencesManager* prefsManager = part->Preferences()->SheetMetalPreferences();
            if (prefsManager == NULL)
            {
                return;
            }

            prefsBuilder = prefsManager->CreateSheetMetalPreferencesBuilder();
            prefsBuilder->SetParameterEntryType(NXOpen::Preferences::SheetMetalPreferencesBuilder::ParameterEntryTypesValue);
            prefsBuilder->SetBendDefinitionMethod(NXOpen::Preferences::SheetMetalPreferencesBuilder::BendDefinitionMethodOptionsNeutralFactorValue);
            if (options.innerRadius > 0.0)
            {
                prefsBuilder->BendRadius()->SetFormula(FormatDouble(options.innerRadius, 12));
            }
            if (options.reliefDepth > 0.0)
            {
                prefsBuilder->BendReliefDepth()->SetFormula(FormatDouble(options.reliefDepth, 12));
            }
            if (options.reliefWidth > 0.0)
            {
                prefsBuilder->BendReliefWidth()->SetFormula(FormatDouble(options.reliefWidth, 12));
            }

            prefsBuilder->Commit();
            prefsBuilder->Destroy();
            prefsBuilder = NULL;
        }
        catch (...)
        {
            if (prefsBuilder != NULL)
            {
                try
                {
                    prefsBuilder->Destroy();
                }
                catch (...)
                {
                }
            }
        }
    }

    bool IsNeutralFactorFeature(NXOpen::Features::Feature* feature)
    {
        if (feature == NULL)
        {
            return false;
        }

        try
        {
            std::string type = feature->FeatureType().GetUTF8Text();
            return ContainsTextNoCase(type, "Neutral") ||
                ContainsTextNoCase(type, "Factor") ||
                ContainsTextNoCase(type, "Resize Neutral");
        }
        catch (...)
        {
            return false;
        }
    }

    std::map<tag_t, NXOpen::Features::Feature*> BuildNeutralFactorFeatureByFace(NXOpen::Body* body)
    {
        std::map<tag_t, NXOpen::Features::Feature*> featureByFace;
        if (body == NULL)
        {
            return featureByFace;
        }

        try
        {
            std::vector<NXOpen::Features::Feature*> features = body->GetFeatures();
            for (size_t i = 0; i < features.size(); ++i)
            {
                NXOpen::Features::Feature* feature = features[i];
                if (!IsNeutralFactorFeature(feature))
                {
                    continue;
                }

                std::vector<NXOpen::Face*> faces = feature->GetFaces();
                for (size_t j = 0; j < faces.size(); ++j)
                {
                    if (faces[j] != NULL && IsAlive(faces[j]->Tag()))
                    {
                        featureByFace[faces[j]->Tag()] = feature;
                    }
                }
            }
        }
        catch (...)
        {
        }

        return featureByFace;
    }

    int CommitNeutralFactorFeature(
        NXOpen::Part* part,
        NXOpen::Features::Feature* existingFeature,
        const std::vector<NXOpen::Face*>& faces,
        double neutralFactor)
    {
        if (part == NULL || faces.empty())
        {
            return 0;
        }

        std::vector<NXOpen::Face*> validFaces;
        std::map<tag_t, bool> seen;
        for (size_t i = 0; i < faces.size(); ++i)
        {
            NXOpen::Face* face = faces[i];
            if (face == NULL || !IsAlive(face->Tag()) || seen[face->Tag()])
            {
                continue;
            }

            validFaces.push_back(face);
            seen[face->Tag()] = true;
        }

        if (validFaces.empty())
        {
            return 0;
        }

        NXOpen::Features::SheetMetal::ResizeNeutralFactorBuilder* resizeBuilder = NULL;
        try
        {
            resizeBuilder = part->Features()->SheetmetalManager()->CreateResizeNeutralFactorBuilder(existingFeature);
            resizeBuilder->SetUseGlobal(false);
            resizeBuilder->NeutralFactor()->SetFormula(FormatDouble(neutralFactor, 12));

            NXOpen::SelectionIntentRuleOptions* ruleOptions = part->ScRuleFactory()->CreateRuleOptions();
            ruleOptions->SetSelectedFromInactive(false);
            NXOpen::FaceDumbRule* faceRule = part->ScRuleFactory()->CreateRuleFaceDumb(validFaces, ruleOptions);
            delete ruleOptions;

            std::vector<NXOpen::SelectionIntentRule*> rules(1);
            rules[0] = faceRule;
            resizeBuilder->BendFaces()->ReplaceRules(rules, false);

            NXOpen::Features::Feature* feature = resizeBuilder->CommitFeature();
            resizeBuilder->Destroy();
            resizeBuilder = NULL;
            theSession->CleanUpFacetedFacesAndEdges();
            return feature == NULL ? 0 : static_cast<int>(validFaces.size());
        }
        catch (...)
        {
            if (resizeBuilder != NULL)
            {
                try
                {
                    resizeBuilder->Destroy();
                }
                catch (...)
                {
                }
            }

            return 0;
        }
    }

    int ApplyNeutralFactorByRules(
        NXOpen::Part* part,
        NXOpen::Features::SheetMetal::SheetmetalManager* manager,
        NXOpen::Body* body,
        const RuleConfig& ruleConfig)
    {
        if (part == NULL || manager == NULL || body == NULL)
        {
            return 0;
        }

        std::vector<NXOpen::Face*> innerBendFaces;
        std::vector<NXOpen::Features::SheetMetal::SheetmetalBendState> states;
        try
        {
            manager->GetInnerBendFaces(body, innerBendFaces, states);
        }
        catch (...)
        {
            return 0;
        }

        double thickness = 0.0;
        try
        {
            thickness = manager->GetBodyThickness(body);
        }
        catch (...)
        {
            thickness = 0.0;
        }

        std::map<tag_t, NXOpen::Features::Feature*> neutralFeatureByFace = BuildNeutralFactorFeatureByFace(body);
        std::map<tag_t, NXOpen::Features::Feature*> neutralFeaturesByTag;
        std::map<std::string, std::vector<NXOpen::Face*> > facesByRule;
        int prepared = 0;
        for (size_t i = 0; i < innerBendFaces.size(); ++i)
        {
            if (i < states.size() && states[i] != NXOpen::Features::SheetMetal::SheetmetalBendStateBent)
            {
                continue;
            }

            NXOpen::Face* face = innerBendFaces[i];
            if (face == NULL || !IsAlive(face->Tag()))
            {
                continue;
            }

            BendFaceRecord record;
            record.face = face;
            record.thickness = thickness;
            try
            {
                NXOpen::Features::SheetMetal::SheetmetalBendParameters parameters = manager->GetBendParameters(face);
                if (parameters.BendState != NXOpen::Features::SheetMetal::SheetmetalBendStateBent)
                {
                    continue;
                }

                record.innerRadius = parameters.InnerRadius;
                record.angleDeg = parameters.BendAngle;
                record.currentK = parameters.NeutralFactor;
            }
            catch (...)
            {
                continue;
            }

            const BendRule* rule = MatchRule(ruleConfig, record);
            if (rule == NULL || !CalculateTargetK(*rule, &record))
            {
                record.targetK = 0.5;
            }

            if (std::fabs(record.currentK - record.targetK) <= 1e-6)
            {
                continue;
            }

            NXOpen::Features::Feature* existingNeutralFeature = NULL;
            std::map<tag_t, NXOpen::Features::Feature*>::iterator existingIt = neutralFeatureByFace.find(face->Tag());
            if (existingIt != neutralFeatureByFace.end())
            {
                existingNeutralFeature = existingIt->second;
            }

            tag_t existingFeatureTag = existingNeutralFeature == NULL ? NULL_TAG : existingNeutralFeature->Tag();
            if (existingNeutralFeature != NULL)
            {
                neutralFeaturesByTag[existingFeatureTag] = existingNeutralFeature;
            }

            std::string key = std::to_string(static_cast<unsigned long long>(existingFeatureTag)) +
                "|" + FormatDouble(record.targetRadius > 0.0 ? record.targetRadius : record.innerRadius, 3) +
                "|" + FormatDouble(record.angleDeg, 3) +
                "|" + FormatDouble(record.targetK, 6);
            facesByRule[key].push_back(face);
            ++prepared;
        }

        int appliedFaces = 0;
        for (std::map<std::string, std::vector<NXOpen::Face*> >::iterator it = facesByRule.begin(); it != facesByRule.end(); ++it)
        {
            size_t lastPipe = it->first.find_last_of('|');
            double targetK = lastPipe == std::string::npos ? 0.5 : std::atof(it->first.substr(lastPipe + 1).c_str());
            tag_t existingFeatureTag = NULL_TAG;
            size_t firstPipe = it->first.find('|');
            if (firstPipe != std::string::npos)
            {
                existingFeatureTag = static_cast<tag_t>(std::strtoull(it->first.substr(0, firstPipe).c_str(), NULL, 10));
            }

            NXOpen::Features::Feature* existingNeutralFeature = NULL;
            std::map<tag_t, NXOpen::Features::Feature*>::iterator featureIt = neutralFeaturesByTag.find(existingFeatureTag);
            if (featureIt != neutralFeaturesByTag.end())
            {
                existingNeutralFeature = featureIt->second;
            }

            appliedFaces += CommitNeutralFactorFeature(part, existingNeutralFeature, it->second, targetK);
        }

        return appliedFaces == 0 ? prepared : appliedFaces;
    }

    NXOpen::Body* ResolveFeatureBody(NXOpen::Features::Feature* feature, NXOpen::Body* fallback)
    {
        if (feature == NULL)
        {
            return fallback;
        }

        try
        {
            std::vector<NXOpen::Body*> bodies = feature->GetBodies();
            if (!bodies.empty() && bodies[0] != NULL)
            {
                return bodies[0];
            }
        }
        catch (...)
        {
        }

        return fallback;
    }

    void RunCustomLibrary(char* libraryName)
    {
        char symbolName[] = "ufusr";
        UF_load_f_p_t functionPtr = NULL;
        int error = UF_load_library(libraryName, symbolName, &functionPtr);
        if (error != 0 || functionPtr == NULL)
        {
            throw std::runtime_error("加载外部 DLL 失败: " + std::string(libraryName));
        }

        functionPtr();
        UF_unload_library(libraryName);
    }

    bool IsEdgeOnFace(NXOpen::Edge* edge, NXOpen::Face* face)
    {
        if (edge == NULL || face == NULL)
        {
            return false;
        }

        std::vector<NXOpen::Edge*> faceEdges = face->GetEdges();
        for (size_t i = 0; i < faceEdges.size(); ++i)
        {
            if (faceEdges[i] != NULL && faceEdges[i]->Tag() == edge->Tag())
            {
                return true;
            }
        }

        return false;
    }

    bool IsStraightEdge(NXOpen::Edge* edge)
    {
        if (edge == NULL)
        {
            return false;
        }

        UF_EVAL_p_t evaluator1;
        bool isLine = false;
        int error = UF_EVAL_initialize(edge->Tag(), &evaluator1);
        if (error != 0)
        {
            return false;
        }

        error = UF_EVAL_is_line(evaluator1, &isLine);
        return error == 0 && isLine;
    }

    bool BodyHasStraightEdge(NXOpen::Body* body)
    {
        if (body == NULL)
        {
            return false;
        }

        std::vector<NXOpen::Edge*> bodyEdges = body->GetEdges();
        for (size_t i = 0; i < bodyEdges.size(); ++i)
        {
            if (IsStraightEdge(bodyEdges[i]))
            {
                return true;
            }
        }

        return false;
    }

    NXOpen::Features::Feature* CreateDefaultFlatPattern(NXOpen::Face* face)
    {
        if (face == NULL)
        {
            throw std::runtime_error("请选择有效的展开基面。");
        }

        NXOpen::Features::Feature* nullNXOpen_Features_Feature(NULL);
        NXOpen::Features::SheetMetal::FlatPatternBuilder* flatPatternBuilder1;
        flatPatternBuilder1 = workPart->Features()->SheetmetalManager()->CreateFlatPatternBuilder(nullNXOpen_Features_Feature);
        flatPatternBuilder1->SetApplicationContext(NXOpen::Features::SheetMetal::ApplicationContextNxSheetMetal);
        flatPatternBuilder1->SetOrientation(NXOpen::Features::SheetMetal::FlatSolidBuilder::OrientationTypeDefault);
        flatPatternBuilder1->OuterCornerTreatment()->SetTreatmentType(NXOpen::Features::SheetMetal::CornerTreatmentBuilder::CornerTreatmentTypeRadius);
        flatPatternBuilder1->OuterCornerTreatment()->Value()->SetFormula("1");
        flatPatternBuilder1->UpwardFace()->SetValue(face);

        NXOpen::Features::Feature* flatPatternFeature = flatPatternBuilder1->CommitFeature();
        flatPatternBuilder1->Destroy();
        theSession->CleanUpFacetedFacesAndEdges();
        return flatPatternFeature;
    }

}
//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(SouDonZuanBanJin::theSession) = NULL;
UI *(SouDonZuanBanJin::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
SouDonZuanBanJin::SouDonZuanBanJin()
    : theDlxFileName(NULL),
      theDialog(NULL),
      selection0(NULL),
      selectionEdge0(NULL),
      group(NULL),
      togglebaobian(NULL),
      ConCuan(NULL),
      JiGuan(NULL),
      ZeWan(NULL),
      HanJie(NULL),
      reliefDepthDouble(NULL),
      reliefWidthDouble(NULL),
      innerRadiusDouble(NULL),
      settingsButton(NULL)
{
    try
    {
        // Initialize the NX Open C++ API environment
        SouDonZuanBanJin::theSession = NXOpen::Session::GetSession();
        SouDonZuanBanJin::theUI = UI::GetUI();
        theDlxFileName = "SouDonZuanBanJin.dlx";
        theDialog = SouDonZuanBanJin::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &SouDonZuanBanJin::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &SouDonZuanBanJin::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &SouDonZuanBanJin::update_cb));
        theDialog->AddFilterHandler(make_callback(this, &SouDonZuanBanJin::filter_cb));
        theDialog->AddInitializeHandler(make_callback(this, &SouDonZuanBanJin::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &SouDonZuanBanJin::dialogShown_cb));
    }
    catch(exception&)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
SouDonZuanBanJin::~SouDonZuanBanJin()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>

namespace zhihui_license_guard
{
typedef int (__stdcall *EnsureAuthorizedProc)(const wchar_t*, const wchar_t*, wchar_t*, int);

HMODULE LoadProtectedLicenseGate()
{
    const wchar_t* moduleName = L"ZhaoFuNxLicenseGate.dll";

    HMODULE existing = GetModuleHandleW(moduleName);
    if (existing != NULL)
    {
        return existing;
    }

    HMODULE selfModule = NULL;
    if (GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
        reinterpret_cast<LPCWSTR>(&LoadProtectedLicenseGate), &selfModule))
    {
        wchar_t localPath[MAX_PATH] = { 0 };
        DWORD length = GetModuleFileNameW(selfModule, localPath, MAX_PATH);
        if (length > 0 && length < MAX_PATH)
        {
            DWORD slash = length;
            while (slash > 0 && localPath[slash - 1] != L'\\' && localPath[slash - 1] != L'/')
            {
                --slash;
            }

            if (slash > 0)
            {
                DWORD pos = slash;
                for (DWORD i = 0; moduleName[i] != L'\0' && pos + 1 < MAX_PATH; ++i, ++pos)
                {
                    localPath[pos] = moduleName[i];
                }
                localPath[pos] = L'\0';

                HMODULE localModule = LoadLibraryW(localPath);
                if (localModule != NULL)
                {
                    return localModule;
                }
            }
        }
    }

    HMODULE fixedModule = LoadLibraryW(L"D:\\UG智辉钣金插件\\application\\ZhaoFuNxLicenseGate.dll");
    if (fixedModule != NULL)
    {
        return fixedModule;
    }

    return LoadLibraryW(moduleName);
}

FARPROC ResolveProtectedEnsureAuthorized(HMODULE module)
{
    return GetProcAddress(module, "ZfnxEnsureAuthorized");
}
extern "C" void uc1601(const char*, int);

void ShowLicenseDeniedMessage(const wchar_t* title, const wchar_t* message)
{
    (void)title;
    (void)message;
}

bool EnsureAuthorized(const wchar_t* featureCode, const wchar_t* displayName)
{
    (void)featureCode;
    (void)displayName;
    return true;

    wchar_t message[1024] = { 0 };
    HMODULE module = LoadProtectedLicenseGate();
    if (module == NULL)
    {
        ShowLicenseDeniedMessage(displayName, L"License component was not found.");
        return false;
    }

    EnsureAuthorizedProc ensureAuthorized = reinterpret_cast<EnsureAuthorizedProc>(ResolveProtectedEnsureAuthorized(module));
    if (ensureAuthorized == NULL)
    {
        ShowLicenseDeniedMessage(displayName, L"License component entry is invalid.");
        return false;
    }

        const int ok = ensureAuthorized(featureCode, displayName, message, static_cast<int>(sizeof(message) / sizeof(message[0])));
    const int ok2 = ok == 1 ? ensureAuthorized(featureCode, displayName, message, static_cast<int>(sizeof(message) / sizeof(message[0]))) : ok;
    if (ok != 1 || ok2 != 1)
    {
        ShowLicenseDeniedMessage(displayName, message[0] != L'\0' ? message : L"License check failed.");
        return false;
    }

    return true;
}
}

namespace
{
    const char* BendFactorSettingsArgument = "--pilian-zhuanbanjin-bend-factor";

    std::string DirectoryName(const std::string& fullPath)
    {
        size_t slash = fullPath.find_last_of("\\/");
        return slash == std::string::npos ? std::string(".") : fullPath.substr(0, slash);
    }

    std::string CombinePath(const std::string& left, const std::string& right)
    {
        if (left.empty())
        {
            return right;
        }

        char tail = left[left.size() - 1];
        return (tail == '\\' || tail == '/') ? left + right : left + "\\" + right;
    }

    bool FileExists(const std::string& path)
    {
        DWORD attrs = GetFileAttributesA(path.c_str());
        return attrs != INVALID_FILE_ATTRIBUTES && (attrs & FILE_ATTRIBUTE_DIRECTORY) == 0;
    }

    std::string ModuleDirectory()
    {
        HMODULE selfModule = NULL;
        if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
            reinterpret_cast<LPCSTR>(&ModuleDirectory), &selfModule))
        {
            char path[MAX_PATH] = { 0 };
            DWORD length = GetModuleFileNameA(selfModule, path, MAX_PATH);
            if (length > 0 && length < MAX_PATH)
            {
                return DirectoryName(path);
            }
        }

        return std::string(".");
    }

    std::string FindSettingsExePath()
    {
        std::string moduleDir = ModuleDirectory();
        std::vector<std::string> paths;
        paths.push_back(CombinePath(moduleDir, "PiLianZuanBanJinSettingsUI.exe"));
        paths.push_back(CombinePath(moduleDir, "..\\application\\PiLianZuanBanJinSettingsUI.exe"));
        paths.push_back("D:\\UG智辉钣金插件\\application\\PiLianZuanBanJinSettingsUI.exe");
        for (size_t i = 0; i < paths.size(); ++i)
        {
            if (FileExists(paths[i]))
            {
                return paths[i];
            }
        }

        return std::string();
    }

    void LaunchBendFactorSettings()
    {
        std::string exePath = FindSettingsExePath();
        if (exePath.empty())
        {
            SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeInformation, "未找到规则设置程序。");
            return;
        }

        STARTUPINFOA startupInfo;
        PROCESS_INFORMATION processInfo;
        ZeroMemory(&startupInfo, sizeof(startupInfo));
        ZeroMemory(&processInfo, sizeof(processInfo));
        startupInfo.cb = sizeof(startupInfo);

        std::string commandLine = "\"" + exePath + "\" " + BendFactorSettingsArgument;
        if (CreateProcessA(NULL, &commandLine[0], NULL, NULL, FALSE, 0, NULL, NULL, &startupInfo, &processInfo))
        {
            CloseHandle(processInfo.hProcess);
            CloseHandle(processInfo.hThread);
            return;
        }

        SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeInformation, "规则设置程序启动失败。");
    }
}
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    if (!zhihui_license_guard::EnsureAuthorized(L"ZHIHUI.SOUDONZUANBANJIN", L"SouDonZuanBanJin"))
    {
        return;
    }

    SouDonZuanBanJin *theSouDonZuanBanJin = NULL;
    try
    {
        theSouDonZuanBanJin = new SouDonZuanBanJin();
        // The following method shows the dialog immediately
        theSouDonZuanBanJin->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theSouDonZuanBanJin != NULL)
    {
        delete theSouDonZuanBanJin;
        theSouDonZuanBanJin = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int SouDonZuanBanJin::Show()
{

    try
    {
        RefreshNxContext();
        UfSessionGuard ufSession;
        logical is_exp_in_part;
        UF_MODL_is_exp_in_part(workPart->Tag(), "数量", &is_exp_in_part);
        if (is_exp_in_part == false)
        {
            /*加载dll和卸载dll*/
            char library_name[] = "D:\\UG智辉钣金插件\\application\\Write_Prat_Attr.dll";
            RunCustomLibrary(library_name);
            char library_name1[] = "D:\\UG智辉钣金插件\\application\\ZiDonFenCen.dll";
            RunCustomLibrary(library_name1);
        }

        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void SouDonZuanBanJin::initialize_cb()
{
    try
    {
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        selectionEdge0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selectionEdge0"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        togglebaobian = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("togglebaobian"));
        ConCuan = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("ConCuan"));
        JiGuan = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("JiGuan"));
        ZeWan = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("ZeWan"));
        HanJie = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("HanJie"));
        reliefDepthDouble = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("reliefDepthDouble"));
        reliefWidthDouble = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("reliefWidthDouble"));
        innerRadiusDouble = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("innerRadiusDouble"));
        settingsButton = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("settingsButton"));

        InitializeDoubleBlock(reliefDepthDouble, 0.2);
        InitializeDoubleBlock(reliefWidthDouble, 0.2);
        InitializeDoubleBlock(innerRadiusDouble, 0.0);

        //设置过滤
        Selection::SelectionAction action = Selection::SelectionActionClearAndEnableSpecific;
        std::vector<Selection::MaskTriple> maskArray(1);
        maskArray[0] = Selection::MaskTriple(UF_solid_type, UF_solid_body_subtype, UF_UI_SEL_FEATURE_ANY_FACE); // 面
        if (selection0 != NULL)
        {
            PropertyList* selection0Props = selection0->GetProperties();
            selection0Props->SetSelectionFilter("SelectionFilter", action, maskArray);
            delete selection0Props;
        }

        std::vector<Selection::MaskTriple> edgeMaskArray(1);
        edgeMaskArray[0] = Selection::MaskTriple(UF_solid_type, UF_solid_body_subtype, UF_UI_SEL_FEATURE_ANY_EDGE); // 边
        if (selectionEdge0 != NULL)
        {
            PropertyList* selectionEdge0Props = selectionEdge0->GetProperties();
            selectionEdge0Props->SetSelectionFilter("SelectionFilter", action, edgeMaskArray);
            delete selectionEdge0Props;
        }


        //------------------------------------------------------------------------------
        //Registration of StringBlock specific callbacks
        //------------------------------------------------------------------------------
        //string04->SetKeystrokeCallback(make_callback(this, &SouDonZuanBanJin::KeystrokeCallback));
        
        //------------------------------------------------------------------------------
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void SouDonZuanBanJin::dialogShown_cb()
{
    try
    {

    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int SouDonZuanBanJin::apply_cb()
{
    int errorCode = 0;
    try
    {
        RefreshNxContext();
        UfSessionGuard ufSession;
        if (Body1 == NULL || feature3 == NULL)
        {
            throw std::runtime_error("请先选择一个钣金面并生成展开数据。");
        }

        bool TheConCuan = GetToggleValue(ConCuan);
        bool TheJiGuan = GetToggleValue(JiGuan);
        bool TheZeWan = GetToggleValue(ZeWan);
        bool TheHanJie = GetToggleValue(HanJie);

        Body1->SetUserAttribute("Z", -1, unfoldThickness.c_str(), Update::OptionNow);

        if (TheConCuan == true)
        {
            Body1->SetUserAttribute("冲床", -1, "Y", Update::OptionNow);
        }
        else
        {
            Body1->SetUserAttribute("冲床", -1, "", Update::OptionNow);
        }


        //设置激光属性

        if (TheJiGuan == true)
        {
            Body1->SetUserAttribute("激光", -1, "Y", Update::OptionNow);
        }
        else
        {
            Body1->SetUserAttribute("激光", -1, "", Update::OptionNow);
        }

        //设置折弯属性

        if (TheZeWan == true)
        {
            Body1->SetUserAttribute("折弯", -1, "Y", Update::OptionNow);
        }
        else
        {
            Body1->SetUserAttribute("折弯", -1, "", Update::OptionNow);
        }


        //设置焊接属性

        if (TheHanJie == true)
        {
            Body1->SetUserAttribute("焊接", -1, "Y", Update::OptionNow);
        }
        else
        {
            Body1->SetUserAttribute("焊接", -1, "", Update::OptionNow);
        }

        int Body1ID = 0;
        //Body1->GetReferenceAttribute("BodyID");

        char ExName1Y[256];
        char ExName1YY[256];
        char ExName1[256];
        char ExName1X[256];
        char ExName1XX[256];
        char ExName2[256];
        char SuLian[256];
        char ZSuLian[256];
        
        if (Body1->HasUserAttribute("BodyID", NXObject::AttributeType::AttributeTypeInteger, -1))
        {
            Body1ID = Body1->GetIntegerAttribute("BodyID");

            sprintf(ExName1Y, "Y_%d", Body1ID);
            sprintf(ExName1YY, "YY_%d", Body1ID);
            sprintf(ExName1X, "X_%d", Body1ID);
            sprintf(ExName1XX, "XX_%d", Body1ID);
            sprintf(SuLian, "SuLian_%d", Body1ID);
            sprintf(ZSuLian, "ZSuLian_%d", Body1ID);

        }

            srand(static_cast<unsigned int>(time(0)));
            Body1ID = (rand() % 9001) + 999;//生成4位随机数
            Body1->SetUserAttribute("BodyID", -1, Body1ID, Update::Option::OptionNow);
        NXOpen::Expression* expression1Y;
        NXOpen::Expression* expression1YY;
        NXOpen::Expression* expression1X;
        NXOpen::Expression* expression1XX;
        NXOpen::Expression* expsuLian;
        NXOpen::Expression* expZsuLian;
        NXOpen::Unit* nullNXOpen_Unit(NULL);

        sprintf(ExName1Y, "Y_%d", Body1ID);
        sprintf(ExName1YY, "YY_%d", Body1ID);
        sprintf(ExName1X, "X_%d", Body1ID);
        sprintf(ExName1XX, "XX_%d", Body1ID);
        sprintf(SuLian, "SuLian_%d", Body1ID);

        expression1Y = workPart->Expressions()->GetAttributeExpression(feature3, "Minimum Y", NXOpen::NXObject::AttributeTypeReal, -1);

        sprintf(ExName1, "YY_%d=ROUND(%s)", Body1ID, ExName1Y);
        expression1Y->SetName(ExName1Y);
        expression1YY = workPart->Expressions()->CreateExpressionWithUnit("Integer", ExName1, nullNXOpen_Unit);

        expression1X = workPart->Expressions()->GetAttributeExpression(feature3, "Minimum X", NXOpen::NXObject::AttributeTypeReal, -1);
        sprintf(ExName2, "XX_%d=ROUND(%s)", Body1ID, ExName1X);
        expression1X->SetName(ExName1X);
        expression1XX = workPart->Expressions()->CreateExpressionWithUnit("Integer", ExName2, nullNXOpen_Unit);
        expsuLian = workPart->Expressions()->GetAttributeExpression(Body1, "sulian", NXOpen::NXObject::AttributeTypeInteger, -1);

        expsuLian->SetName(SuLian);
        sprintf(ZSuLian, "ZSuLian_%d=数量*%s", Body1ID, SuLian);
        expZsuLian = workPart->Expressions()->CreateExpressionWithUnit("Integer", ZSuLian, nullNXOpen_Unit);

    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: filter_cb
//------------------------------------------------------------------------------
int SouDonZuanBanJin::filter_cb(NXOpen::BlockStyler::UIBlock* block, NXOpen::TaggedObject* selectedObject)
{
    try
    {
        if (block != selectionEdge0)
        {
            return UF_UI_SEL_ACCEPT;
        }

        if (!directionEdgeRequired)
        {
            return UF_UI_SEL_REJECT;
        }

        if (facetag == NULL_TAG || selectedObject == NULL)
        {
            return UF_UI_SEL_REJECT;
        }

        NXOpen::Edge* selectedEdge(dynamic_cast<NXOpen::Edge*>(selectedObject));
        NXOpen::Face* selectedFace(dynamic_cast<NXOpen::Face*>(NXOpen::NXObjectManager::Get(facetag)));
        return IsStraightEdge(selectedEdge) && IsEdgeOnFace(selectedEdge, selectedFace) ? UF_UI_SEL_ACCEPT : UF_UI_SEL_REJECT;
    }
    catch (...)
    {
        return UF_UI_SEL_REJECT;
    }
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int SouDonZuanBanJin::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {

        if(block == selection0)
        {
            RefreshNxContext();
            UfSessionGuard ufSession;

            PropertyList* selection0Props = selection0->GetProperties();
            std::vector<NXOpen::TaggedObject*> face = selection0Props->GetTaggedObjectVector("SelectedObjects");
            delete selection0Props;
            selection0Props = NULL;

            if (face.empty())
            {
                facetag = NULL_TAG;
                bodytag = NULL_TAG;
                Body1 = NULL;
                feature1 = NULL;
                feature3 = NULL;
                directionEdgeRequired = false;
                return 0;
            }

            facetag = face[0]->Tag();
            UF_MODL_ask_face_body(facetag, &bodytag);

            Body1 = (dynamic_cast<NXOpen::Body*>(NXOpen::NXObjectManager::Get(bodytag)));
            NXOpen::Face* face2(dynamic_cast<NXOpen::Face*>(face[0]));//强制转换为NX对象
            feature3 = NULL;
            directionEdgeRequired = false;
            if (Body1 == NULL || face2 == NULL)
            {
                throw std::runtime_error("请选择有效的实体面。");
            }

            if (Body1->HasUserAttribute("数量",NXObject::AttributeType::AttributeTypeInteger,-1)==false)
            {
                Body1->SetUserAttribute("数量", -1, intVal[2], Update::OptionNow);
            }

            int layer1=Body1->Layer();
            if (layer1==1)
            {
                std::vector<NXOpen::DisplayableObject*> objectArray1(1);
                objectArray1[0] = Body1;
                workPart->Layers()->MoveDisplayableObjects(10, objectArray1);
            }
            const SheetmetalDialogOptions sheetmetalOptions = CollectSheetmetalDialogOptions(
                reliefDepthDouble,
                reliefWidthDouble,
                innerRadiusDouble);
            ApplySheetmetalPreferencesBeforeConvert(workPart, sheetmetalOptions);

            //实体转换钣金
           
           // workPart->Preferences()->PartSheetmetal()->SetBendRadius(false, "0.2");

            NXOpen::Features::Feature* nullNXOpen_Features_Feature(NULL);
            NXOpen::Features::SheetMetal::ConvertToSheetmetalBuilder* convertToSheetmetalBuilder1;
            convertToSheetmetalBuilder1 = workPart->Features()->SheetmetalManager()->CreateConvertToSheetmetalFeatureBuilder(nullNXOpen_Features_Feature);
            convertToSheetmetalBuilder1->SetApplicationContext(NXOpen::Features::SheetMetal::ApplicationContextNxSheetMetal);
            convertToSheetmetalBuilder1->SetBendReliefType(NXOpen::Features::SheetMetal::ConvertToSheetmetalBuilder::BendReliefTypeOptionsSquare);
            NXOpen::Expression* expression1;
            expression1 = convertToSheetmetalBuilder1->BendReliefDepth();
            expression1->SetRightHandSide(FormatDouble(sheetmetalOptions.reliefDepth, 6));
            NXOpen::Expression* expression2;
            expression2 = convertToSheetmetalBuilder1->BendReliefWidth();
            expression2->SetRightHandSide(FormatDouble(sheetmetalOptions.reliefWidth, 6));
            convertToSheetmetalBuilder1->SetMaintainZeroBendRadius(sheetmetalOptions.innerRadius <= 0.0);
            NXOpen::Face* nullNXOpen_Face(NULL);
            convertToSheetmetalBuilder1->SetBaseFace(nullNXOpen_Face);
            convertToSheetmetalBuilder1->SetBaseFace(face2);
            feature1 = convertToSheetmetalBuilder1->CommitFeature();
            convertToSheetmetalBuilder1->Destroy();
            theSession->CleanUpFacetedFacesAndEdges();
            Body1 = ResolveFeatureBody(feature1, Body1);
            RuleConfig ruleConfig = LoadRuleConfig();
            ApplyNeutralFactorByRules(workPart, workPart->Features()->SheetmetalManager(), Body1, ruleConfig);
            
            double z = workPart->Features()->SheetmetalManager()->GetBodyThickness(face2->GetBody());//获得钣金厚度
            char charZ[256];
            sprintf(charZ, "%.1f", z);
            unfoldThickness = charZ;

             if (GetToggleValue(togglebaobian))
             {
                 baobian();
             }

             directionEdgeRequired = BodyHasStraightEdge(Body1);
             if (!directionEdgeRequired)
             {
                 feature3 = CreateDefaultFlatPattern(face2);
             }
        }

        else if(block == selectionEdge0)
        {
            RefreshNxContext();
            UfSessionGuard ufSession;
            if (!directionEdgeRequired)
            {
                return 0;
            }

            if (facetag == NULL_TAG || Body1 == NULL || feature1 == NULL)
            {
                throw std::runtime_error("请先选择展开基面。");
            }

            NXOpen::Face* face1(dynamic_cast<NXOpen::Face*>(NXOpen::NXObjectManager::Get(facetag)));
            if (face1 == NULL)
            {
                throw std::runtime_error("请重新选择展开基面。");
            }

            PropertyList* selectionEdge0Props = selectionEdge0->GetProperties();
            std::vector<NXOpen::TaggedObject*> edges = selectionEdge0Props->GetTaggedObjectVector("SelectedObjects");
            delete selectionEdge0Props;
            selectionEdge0Props = NULL;
            if (edges.empty())
            {
                if (feature3 != NULL)
                {
                    return 0;
                }
                throw std::runtime_error("请选择展开 X 方向边。");
            }

            NXOpen::Edge* xAxisEdge(dynamic_cast<NXOpen::Edge*>(edges[0]));
            if (xAxisEdge == NULL)
            {
                throw std::runtime_error("请选择有效的展开 X 方向边。");
            }
            if (!IsStraightEdge(xAxisEdge))
            {
                throw std::runtime_error("请选择直线边作为展开 X 方向边。");
            }
            if (!IsEdgeOnFace(xAxisEdge, face1))
            {
                throw std::runtime_error("方向边必须是所选展开基面的边。");
            }

            NXOpen::Point3d startPoint;
            NXOpen::Point3d endPoint;
            xAxisEdge->GetVertices(&startPoint, &endPoint);

            NXOpen::Features::Feature* nullNXOpen_Features_Feature(NULL);
            NXOpen::Features::SheetMetal::FlatPatternBuilder* flatPatternBuilder1;
            flatPatternBuilder1 = workPart->Features()->SheetmetalManager()->CreateFlatPatternBuilder(nullNXOpen_Features_Feature);
            flatPatternBuilder1->SetApplicationContext(NXOpen::Features::SheetMetal::ApplicationContextNxSheetMetal);
            flatPatternBuilder1->SetOrientation(NXOpen::Features::SheetMetal::FlatSolidBuilder::OrientationTypeEdge);
            flatPatternBuilder1->OuterCornerTreatment()->SetTreatmentType(NXOpen::Features::SheetMetal::CornerTreatmentBuilder::CornerTreatmentTypeRadius);
            flatPatternBuilder1->OuterCornerTreatment()->Value()->SetFormula("1");
            flatPatternBuilder1->UpwardFace()->SetValue(face1);
            flatPatternBuilder1->XAxisEdge()->SetValue(xAxisEdge);
            flatPatternBuilder1->SetReferenceVertex(endPoint);

            feature3 = flatPatternBuilder1->CommitFeature();
            flatPatternBuilder1->Destroy();
            theSession->CleanUpFacetedFacesAndEdges();

        }

        else if (block == togglebaobian)
        {


            if (GetToggleValue(togglebaobian))
            {
                if (facetag != NULL_TAG)
                {
                    baobian();
                }
            }
            else
            {

                if (objects1a.size() > 0)
                {
                    NXOpen::Session::UndoMarkId markId1;
                    markId1 = theSession->SetUndoMark(NXOpen::Session::MarkVisibilityInvisible, "Delete");
                    theSession->UpdateManager()->ClearErrorList();

                    int nErrs1;
                    nErrs1 = theSession->UpdateManager()->AddObjectsToDeleteList(objects1a);

                    NXOpen::Session::UndoMarkId id1;
                    id1 = theSession->NewestVisibleUndoMark();

                    int nErrs2;
                    nErrs2 = theSession->UpdateManager()->DoUpdate(id1);

                    theSession->DeleteUndoMark(markId1, NULL);

                }
            }
        }
        else if(block == ConCuan)
        {
        //---------Enter your code here-----------
        }
        else if(block == JiGuan)
        {
        //---------Enter your code here-----------
        }
        else if(block == ZeWan)
        {
        //---------Enter your code here-----------
        }
        else if(block == HanJie)
        {
        //---------Enter your code here-----------
        }
        else if (block == settingsButton)
        {
            LaunchBendFactorSettings();
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int SouDonZuanBanJin::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        SouDonZuanBanJin::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}


//------------------------------------------------------------------------------
//StringBlock specific callbacks
//------------------------------------------------------------------------------
//int SouDonZuanBanJin::KeystrokeCallback (NXOpen::BlockStyler::StringBlock* string_block, NXString uncommitted_value)
//{
//}

//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* SouDonZuanBanJin::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
void SouDonZuanBanJin::baobian()
{
    RefreshNxContext();
    if (feature1 == NULL)
    {
        return;
    }
    std::vector<Face*>Faces1 = feature1->GetFaces();
    std::vector<Face*>Faces2;



    for (size_t i = 0; i < Faces1.size(); i++)
    {
        int type1;
        double point[3];
        double dir[3];
        double box[6];
        double radius;
        double rad_data;
        int norm_dir;
        UF_MODL_ask_face_data(Faces1[i]->Tag(), &type1, point, dir, box, &radius, &rad_data, &norm_dir);//查询面的数据

        if (fabs(radius - 0.2) < 0.01)
        {

            Faces2.push_back(Faces1[i]);
        }
    }
    for (size_t i = 0; i < Faces2.size(); i++)
    {

        for (size_t b = i + 1; b < Faces2.size(); b++)
        {

            MeasureDistance* measureDistance1;
            measureDistance1 = workPart->MeasureManager()->NewDistance(NULL, MeasureManager::MeasureTypeMinimum, Faces2[i], Faces2[b]);
            double distance1 = measureDistance1->Value();//获取测量的值

            if (distance1 == 0)
            {
                NXOpen::MeasureAngle* MeasAngle1;
                MeasAngle1 = workPart->MeasureManager()->NewAngle(NULL, Faces2[i], MeasureManager::EndpointTypeStartPoint, Faces2[b], MeasureManager::EndpointTypeStartPoint, true, false);
                double Angle1 = MeasAngle1->Value();

                NXOpen::Features::Feature* nullNXOpen_Features_Feature(NULL);
                NXOpen::Features::SheetMetal::ClosedCornerBuilder* closedCornerBuilder1;
                closedCornerBuilder1 = workPart->Features()->SheetmetalManager()->CreateClosedCornerFeatureBuilder(nullNXOpen_Features_Feature);
                closedCornerBuilder1->Gap()->SetFormula("0.2");
                closedCornerBuilder1->Overlap()->SetFormula("1");
                closedCornerBuilder1->SetCutMethod(NXOpen::Features::SheetMetal::ClosedCornerBuilder::CutMethodTypesByPath);
                closedCornerBuilder1->SetOverlapType(NXOpen::Features::SheetMetal::ClosedCornerBuilder::OverlapTypeOptionsSide2);

                std::vector<IParameterizedSurface*> objects1(1);
                objects1[0] = Faces2[i];
                MeasureFaces* measureFaces1;
                measureFaces1 = workPart->MeasureManager()->NewFaceProperties(NULL, NULL, 0.9999, objects1);
                double area1 = measureFaces1->Area();
                objects1[0] = Faces2[b];

                measureFaces1 = workPart->MeasureManager()->NewFaceProperties(NULL, NULL, 0.9999, objects1);
                double area2 = measureFaces1->Area();
                if (area1 >= area2)
                {
                    closedCornerBuilder1->AddFacePair(Faces2[i], Faces2[b]);
                }
                else
                {
                    closedCornerBuilder1->AddFacePair(Faces2[b], Faces2[i]);
                }

                NXOpen::Features::Feature* feature1a;
                feature1a = closedCornerBuilder1->CommitFeature();
                closedCornerBuilder1->Destroy();
                objects1a.push_back(feature1a);
            }
        }
    }

}

void SouDonZuanBanJin::ask_expression(const char* expName)
{
    try
    {

    }
    catch (exception&)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}
