//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\LPOpenPrint\application\BODYNOT.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 22738
//              Version: NX 1973
//              Date: 08-18-2021  (Format: mm-dd-yyyy)
//              Time: 22:30 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "BODYNOT.hpp"
#include "third_party/ZhaoFuNxLicenseGate/ZhaoFuNxLicenseGate.hpp"
#include <windows.h>
#ifdef CreateDialog
#undef CreateDialog
#endif
#include <NXOpen/Annotations_DraftingNoteBuilder.hxx>
#include <NXOpen/Annotations_TextWithSymbolsBuilder.hxx>
#include <NXOpen/Drawings_DraftingBodyCollection.hxx>
#include <NXOpen/Drawings_DraftingCurve.hxx>
#include <NXOpen/Drawings_DraftingCurveCollection.hxx>
#include <NXOpen/Drawings_DraftingView.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/ExpressionCollection.hxx>
#include <uf_draw.h>
#include <uf_modl.h>
#include <uf_modl_utilities.h>
#include <uf_obj.h>
#include <uf_retiring.h>
#include <uf_view.h>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <set>
#include <sstream>
#include <string>
#include <vector>
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

extern "C" IMAGE_DOS_HEADER __ImageBase;

//------------------------------------------------------------------------------
// Local static variables
//------------------------------------------------------------------------------
static NXOpen::Part* workPart = NULL;
static NXOpen::Part* displayPart = NULL;
static NXOpen::Annotations::DraftingNoteBuilder* draftingNoteBuilder1 = NULL;

namespace
{
static const char* kDefaultBodyNoteFormat = "{\xE7\xBC\x96\xE5\x8F\xB7=}{\xE6\x9D\x90\xE6\x96\x99} T={\xE5\x8E\x9A\xE5\xBA\xA6} {\xE6\x95\xB0\xE9\x87\x8F}PCS{\xE9\x95\x9C\xE5\x83\x8F}";

class UfSessionGuard
{
public:
    UfSessionGuard() : initialized(UF_initialize() == 0) {}
    ~UfSessionGuard()
    {
        if (initialized)
        {
            UF_terminate();
        }
    }

    bool IsInitialized() const { return initialized; }

private:
    bool initialized;
};

std::wstring PluginDirectory()
{
    wchar_t modulePath[MAX_PATH] = {};
    const DWORD length = GetModuleFileNameW(reinterpret_cast<HMODULE>(&__ImageBase), modulePath, MAX_PATH);
    if (length == 0 || length == MAX_PATH)
    {
        return L".";
    }

    std::wstring path(modulePath, length);
    const std::wstring::size_type slash = path.find_last_of(L"\\/");
    if (slash == std::wstring::npos)
    {
        return L".";
    }
    return path.substr(0, slash);
}

std::wstring BodyNoteConfigFilePath()
{
    return PluginDirectory() + L"\\ZiDonCuTu_note_format.ini";
}

void EnsureDefaultBodyNoteConfigFile(const std::wstring& path)
{
    const DWORD attributes = GetFileAttributesW(path.c_str());
    if (attributes != INVALID_FILE_ATTRIBUTES && (attributes & FILE_ATTRIBUTE_DIRECTORY) == 0)
    {
        return;
    }

    std::ofstream file(path, std::ios::binary);
    if (!file)
    {
        return;
    }

    const unsigned char bom[] = { 0xEF, 0xBB, 0xBF };
    file.write(reinterpret_cast<const char*>(bom), sizeof(bom));
    file
        << "# Placeholders: {number}, {number=}, {material}, {thickness}, {quantity}, {mirror}\r\n"
        << "# Use Chinese placeholders: {\xE7\xBC\x96\xE5\x8F\xB7}, {\xE7\xBC\x96\xE5\x8F\xB7=}, {\xE6\x9D\x90\xE6\x96\x99}, {\xE5\x8E\x9A\xE5\xBA\xA6}, {\xE6\x95\xB0\xE9\x87\x8F}, {\xE9\x95\x9C\xE5\x83\x8F}\r\n"
        << "# Use \\n for multiple lines.\r\n\r\n"
        << "[\xE6\xA0\x87\xE6\xB3\xA8\xE6\xB3\xA8\xE9\x87\x8A]\r\n"
        << kDefaultBodyNoteFormat << "\r\n";
}

void DestroyDraftingNoteBuilder()
{
    if (draftingNoteBuilder1 != NULL)
    {
        draftingNoteBuilder1->Destroy();
        draftingNoteBuilder1 = NULL;
    }
}

bool IsEmptyText(const NXOpen::NXString& value)
{
    const char* text = value.GetLocaleText();
    return text == NULL || strlen(text) == 0;
}

std::string TrimText(std::string value)
{
    value.erase(value.begin(), std::find_if(value.begin(), value.end(), [](unsigned char ch) {
        return !std::isspace(ch);
        }));
    value.erase(std::find_if(value.rbegin(), value.rend(), [](unsigned char ch) {
        return !std::isspace(ch);
        }).base(), value.end());
    return value;
}

std::string RemoveUtf8Bom(const std::string& value)
{
    if (value.size() >= 3 &&
        static_cast<unsigned char>(value[0]) == 0xEF &&
        static_cast<unsigned char>(value[1]) == 0xBB &&
        static_cast<unsigned char>(value[2]) == 0xBF)
    {
        return value.substr(3);
    }
    return value;
}

void ReplaceAllText(std::string& text, const std::string& from, const std::string& to)
{
    if (from.empty())
    {
        return;
    }

    size_t pos = 0;
    while ((pos = text.find(from, pos)) != std::string::npos)
    {
        text.replace(pos, from.length(), to);
        pos += to.length();
    }
}

std::string DecodeConfigEscapes(const std::string& value)
{
    std::string result;
    bool escape = false;
    for (size_t i = 0; i < value.size(); ++i)
    {
        const char ch = value[i];
        if (escape)
        {
            if (ch == 'n')
            {
                result += '\n';
            }
            else if (ch == 'r')
            {
                result += '\r';
            }
            else if (ch == 't')
            {
                result += '\t';
            }
            else
            {
                result += ch;
            }
            escape = false;
            continue;
        }

        if (ch == '\\')
        {
            escape = true;
            continue;
        }
        result += ch;
    }

    if (escape)
    {
        result += '\\';
    }
    return result;
}

bool TryReadBodyNoteFormatLine(const std::string& rawLine, std::string& formatText)
{
    std::string line = TrimText(RemoveUtf8Bom(rawLine));
    if (line.empty() || line[0] == '#' || line[0] == ';')
    {
        return false;
    }
    if (line.front() == '[' && line.back() == ']')
    {
        return false;
    }

    const std::string key = "body_note_format";
    if (line.compare(0, key.size(), key) == 0)
    {
        const size_t equalPos = line.find('=');
        if (equalPos != std::string::npos)
        {
            line = TrimText(line.substr(equalPos + 1));
        }
    }

    if (line.empty())
    {
        return false;
    }

    formatText = DecodeConfigEscapes(line);
    return !formatText.empty();
}
bool HasAnyUserAttribute(NXOpen::NXObject* object, const char* title)
{
    if (object == NULL || title == NULL)
    {
        return false;
    }

    try
    {
        return object->HasUserAttribute(title, NXOpen::NXObject::AttributeType::AttributeTypeString, -1) ||
            object->HasUserAttribute(title, NXOpen::NXObject::AttributeType::AttributeTypeInteger, -1) ||
            object->HasUserAttribute(title, NXOpen::NXObject::AttributeType::AttributeTypeReal, -1);
    }
    catch (...)
    {
        return false;
    }
}

std::string ObjectAttributeReferenceText(NXOpen::NXObject* object, const char* title)
{
    if (object == NULL || title == NULL)
    {
        return "";
    }
    try
    {
        if (!HasAnyUserAttribute(object, title))
        {
            return "";
        }

        std::string objectName = object->Name().GetLocaleText();
        if (objectName.empty())
        {
            char generatedName[64] = {};
            sprintf(generatedName, "ZDCT_BODY_%u", static_cast<unsigned int>(object->Tag()));
            object->SetName(generatedName);
            objectName = generatedName;
        }
        return std::string("<W") + objectName + "@" + title + ">";
    }
    catch (...)
    {
        return "";
    }
}

std::string PartAttributeReferenceText(NXOpen::Part* part, const char* title)
{
    if (!HasAnyUserAttribute(part, title))
    {
        return "";
    }

    return std::string("<W@") + title + ">";
}

std::string ExpressionReferenceText(NXOpen::Part* part, const std::string& expressionName)
{
    if (part == NULL || expressionName.empty())
    {
        return "";
    }

    try
    {
        NXOpen::Expression* expression = part->Expressions()->FindObject(expressionName.c_str());
        if (expression == NULL)
        {
            return "";
        }
        return std::string("<X0.0@") + expressionName + ">";
    }
    catch (...)
    {
        return "";
    }
}

std::string LoadBodyNoteFormat()
{
    const std::wstring path = BodyNoteConfigFilePath();
    EnsureDefaultBodyNoteConfigFile(path);

    std::ifstream file(path, std::ios::binary);
    if (!file)
    {
        return kDefaultBodyNoteFormat;
    }

    std::string line;
    std::string formatText;
    std::string multiLineFormat;
    while (std::getline(file, line))
    {
        if (TryReadBodyNoteFormatLine(line, formatText))
        {
            if (!multiLineFormat.empty())
            {
                multiLineFormat += '\n';
            }
            multiLineFormat += formatText;
        }
    }
    if (!multiLineFormat.empty())
    {
        return multiLineFormat;
    }
    return kDefaultBodyNoteFormat;
}

std::string FormatRealForNote(double value)
{
    std::ostringstream stream;
    if (std::fabs(value - std::round(value)) < 1.0e-6)
    {
        stream << static_cast<long long>(std::llround(value));
    }
    else
    {
        stream.setf(std::ios::fixed);
        stream.precision(3);
        stream << value;
        std::string text = stream.str();
        while (!text.empty() && text[text.size() - 1] == '0')
        {
            text.erase(text.size() - 1);
        }
        if (!text.empty() && text[text.size() - 1] == '.')
        {
            text.erase(text.size() - 1);
        }
        return text;
    }
    return stream.str();
}

std::string LocaleTextToUtf8(const char* text)
{
    if (text == NULL || text[0] == '\0')
    {
        return "";
    }

    const int wideLength = MultiByteToWideChar(CP_ACP, 0, text, -1, NULL, 0);
    if (wideLength <= 0)
    {
        return text;
    }

    std::wstring wideText(static_cast<size_t>(wideLength), L'\0');
    if (MultiByteToWideChar(CP_ACP, 0, text, -1, &wideText[0], wideLength) <= 0)
    {
        return text;
    }

    const int utf8Length = WideCharToMultiByte(CP_UTF8, 0, wideText.c_str(), -1, NULL, 0, NULL, NULL);
    if (utf8Length <= 0)
    {
        return text;
    }

    std::string utf8Text(static_cast<size_t>(utf8Length), '\0');
    if (WideCharToMultiByte(CP_UTF8, 0, wideText.c_str(), -1, &utf8Text[0], utf8Length, NULL, NULL) <= 0)
    {
        return text;
    }
    if (!utf8Text.empty() && utf8Text[utf8Text.size() - 1] == '\0')
    {
        utf8Text.erase(utf8Text.size() - 1);
    }
    return utf8Text;
}

std::string ReadAttributeText(NXOpen::NXObject* object, const char* title)
{
    if (object == NULL || title == NULL)
    {
        return "";
    }

    try
    {
        if (object->HasUserAttribute(title, NXOpen::NXObject::AttributeType::AttributeTypeString, -1))
        {
            return TrimText(LocaleTextToUtf8(object->GetStringAttribute(title).GetLocaleText()));
        }
        if (object->HasUserAttribute(title, NXOpen::NXObject::AttributeType::AttributeTypeInteger, -1))
        {
            return std::to_string(object->GetIntegerAttribute(title));
        }
        if (object->HasUserAttribute(title, NXOpen::NXObject::AttributeType::AttributeTypeReal, -1))
        {
            return FormatRealForNote(object->GetRealAttribute(title));
        }
    }
    catch (...)
    {
        return "";
    }
    return "";
}

std::string ReadExpressionIntegerText(NXOpen::Part* part, const char* expressionName)
{
    if (part == NULL || expressionName == NULL)
    {
        return "";
    }

    try
    {
        NXOpen::Expression* expression = part->Expressions()->FindObject(expressionName);
        if (expression != NULL)
        {
            return std::to_string(expression->IntegerValue());
        }
    }
    catch (...)
    {
    }
    return "";
}

std::string ReadBodyTotalQuantityText(NXOpen::Part* part, NXOpen::Body* body)
{
    if (part != NULL && body != NULL)
    {
        try
        {
            char expressionName[256] = {};
            sprintf(expressionName, "ZSuLian_%d", body->GetIntegerAttribute("BodyID"));
            std::string totalQuantity = ReadExpressionIntegerText(part, expressionName);
            if (!totalQuantity.empty())
            {
                return totalQuantity;
            }
        }
        catch (...)
        {
        }
    }

    std::string quantity = ReadAttributeText(body, "sulian");
    if (quantity.empty())
    {
        quantity = ReadAttributeText(body, "数量");
    }
    return quantity;
}
std::string ReadBodyTotalQuantityReferenceText(NXOpen::Part* part, NXOpen::Body* body)
{
    if (part != NULL && body != NULL)
    {
        try
        {
            char expressionName[256] = {};
            sprintf(expressionName, "ZSuLian_%d", body->GetIntegerAttribute("BodyID"));
            const std::string expressionReference = ExpressionReferenceText(part, expressionName);
            if (!expressionReference.empty())
            {
                return expressionReference;
            }
        }
        catch (...)
        {
        }
    }

    std::string quantityReference = ObjectAttributeReferenceText(body, "sulian");
    if (quantityReference.empty())
    {
        quantityReference = ObjectAttributeReferenceText(body, "\xE6\x95\xB0\xE9\x87\x8F");
    }
    if (!quantityReference.empty())
    {
        return quantityReference;
    }
    return ReadBodyTotalQuantityText(part, body);
}

std::string ReadMaterialText(NXOpen::Part* part, NXOpen::Body* body)
{
    std::string material = ReadAttributeText(body, "cailiao");
    if (!material.empty())
    {
        return material;
    }

    material = ReadAttributeText(body, "\xE6\x9D\x90\xE6\x96\x99");
    if (!material.empty())
    {
        return material;
    }

    material = ReadAttributeText(body, "\xE6\x9D\x90\xE8\xB4\xA8");
    if (!material.empty())
    {
        return material;
    }

    material = ReadAttributeText(part, "\xE6\x9D\x90\xE6\x96\x99");
    if (!material.empty())
    {
        return material;
    }

    material = ReadAttributeText(part, "\xE6\x9D\x90\xE8\xB4\xA8");
    if (!material.empty())
    {
        return material;
    }

    return ReadAttributeText(part, "cailiao");
}
std::string ReadMaterialReferenceText(NXOpen::Part* part, NXOpen::Body* body)
{
    std::string materialReference = ObjectAttributeReferenceText(body, "cailiao");
    if (!materialReference.empty())
    {
        return materialReference;
    }

    materialReference = ObjectAttributeReferenceText(body, "\xE6\x9D\x90\xE6\x96\x99");
    if (!materialReference.empty())
    {
        return materialReference;
    }

    materialReference = ObjectAttributeReferenceText(body, "\xE6\x9D\x90\xE8\xB4\xA8");
    if (!materialReference.empty())
    {
        return materialReference;
    }

    materialReference = PartAttributeReferenceText(part, "\xE6\x9D\x90\xE6\x96\x99");
    if (!materialReference.empty())
    {
        return materialReference;
    }

    materialReference = PartAttributeReferenceText(part, "\xE6\x9D\x90\xE8\xB4\xA8");
    if (!materialReference.empty())
    {
        return materialReference;
    }

    materialReference = PartAttributeReferenceText(part, "cailiao");
    if (!materialReference.empty())
    {
        return materialReference;
    }

    return ReadMaterialText(part, body);
}

std::string BuildBodyNoteText(NXOpen::Part* part, NXOpen::Body* body, bool includeNumber)
{
    const std::string material = ReadMaterialReferenceText(part, body);
    std::string thickness = ObjectAttributeReferenceText(body, "Z");
    if (thickness.empty())
    {
        thickness = ReadAttributeText(body, "Z");
    }
    const std::string quantity = ReadBodyTotalQuantityReferenceText(part, body);
    std::string mirror = ObjectAttributeReferenceText(body, "MIRR");
    if (mirror.empty())
    {
        mirror = ReadAttributeText(body, "MIRR");
    }
    std::string number = includeNumber ? ObjectAttributeReferenceText(body, "bianhao") : "";
    if (includeNumber && number.empty())
    {
        number = ReadAttributeText(body, "bianhao");
    }

    std::string line = LoadBodyNoteFormat();
    ReplaceAllText(line, "{\xE7\xBC\x96\xE5\x8F\xB7=}", number.empty() ? "" : number + "=");
    ReplaceAllText(line, "{\xE7\xBC\x96\xE5\x8F\xB7}", number);
    ReplaceAllText(line, "{\xE6\x9D\x90\xE6\x96\x99}", material);
    ReplaceAllText(line, "{\xE5\x8E\x9A\xE5\xBA\xA6}", thickness);
    ReplaceAllText(line, "{\xE6\x95\xB0\xE9\x87\x8F}", quantity.empty() ? "1" : quantity);
    ReplaceAllText(line, "{\xE9\x95\x9C\xE5\x83\x8F}", mirror);
    return line;
}

std::vector<NXOpen::NXString> BuildBodyNoteLines(NXOpen::Part* part, NXOpen::Body* body, bool includeNumber)
{
    const std::string noteText = BuildBodyNoteText(part, body, includeNumber);
    std::vector<NXOpen::NXString> lines;
    std::string current;
    for (size_t i = 0; i < noteText.size(); ++i)
    {
        const char ch = noteText[i];
        if (ch == '\r')
        {
            continue;
        }
        if (ch == '\n')
        {
            lines.push_back(NXOpen::NXString(current.c_str(), NXOpen::NXString::UTF8));
            current.clear();
            continue;
        }
        current += ch;
    }
    lines.push_back(NXOpen::NXString(current.c_str(), NXOpen::NXString::UTF8));
    return lines;
}

bool SetStringUserAttribute(NXOpen::NXObject* object, const char* title, const std::string& value)
{
    if (object == NULL || title == NULL)
    {
        return false;
    }
    try
    {
        object->SetUserAttribute(title, -1, value.c_str(), NXOpen::Update::OptionNow);
        return true;
    }
    catch (...)
    {
        return false;
    }
}

struct DraftNoteReferenceInsert
{
    enum Kind
    {
        KindAttribute,
        KindExpression
    };

    Kind kind;
    NXOpen::NXObject* owner;
    std::string title;
    std::string expressionName;
    int lineNo;
    int cursorPos;
};

int Utf8CodePointCount(const std::string& text)
{
    int count = 0;
    for (size_t i = 0; i < text.size(); ++i)
    {
        const unsigned char ch = static_cast<unsigned char>(text[i]);
        if ((ch & 0xC0) != 0x80)
        {
            ++count;
        }
    }
    return count;
}

bool FindMaterialReferenceOwner(NXOpen::Part* part, NXOpen::Body* body, NXOpen::NXObject*& owner, std::string& title)
{
    const char* titles[] = {
        "cailiao",
        "\xE6\x9D\x90\xE6\x96\x99",
        "\xE6\x9D\x90\xE8\xB4\xA8"
    };
    for (size_t i = 0; i < sizeof(titles) / sizeof(titles[0]); ++i)
    {
        if (HasAnyUserAttribute(body, titles[i]))
        {
            owner = body;
            title = titles[i];
            return true;
        }
    }
    for (size_t i = 1; i < sizeof(titles) / sizeof(titles[0]); ++i)
    {
        if (HasAnyUserAttribute(part, titles[i]))
        {
            owner = part;
            title = titles[i];
            return true;
        }
    }
    if (HasAnyUserAttribute(part, "cailiao"))
    {
        owner = part;
        title = "cailiao";
        return true;
    }
    return false;
}

bool EnsureBodyThicknessAttribute(NXOpen::Part* part, NXOpen::Body* body)
{
    if (HasAnyUserAttribute(body, "Z"))
    {
        return true;
    }
    if (part == NULL || body == NULL)
    {
        return false;
    }
    try
    {
        const double bodyThickness = part->Features()->SheetmetalManager()->GetBodyThickness(body);
        if (bodyThickness > 1.0e-6)
        {
            SetStringUserAttribute(body, "Z", FormatRealForNote(bodyThickness));
            return HasAnyUserAttribute(body, "Z");
        }
    }
    catch (...)
    {
    }
    return false;
}

bool FindQuantityReference(NXOpen::Part* part, NXOpen::Body* body, DraftNoteReferenceInsert& insert)
{
    if (part != NULL && body != NULL)
    {
        try
        {
            const int bodyId = body->GetIntegerAttribute("BodyID");
            char expressionName[256] = {};
            sprintf(expressionName, "ZSuLian_%d", bodyId);
            if (part->Expressions()->FindObject(expressionName) != NULL)
            {
                insert.kind = DraftNoteReferenceInsert::KindExpression;
                insert.owner = NULL;
                insert.expressionName = expressionName;
                return true;
            }
        }
        catch (...)
        {
        }
    }
    if (HasAnyUserAttribute(body, "sulian"))
    {
        insert.kind = DraftNoteReferenceInsert::KindAttribute;
        insert.owner = body;
        insert.title = "sulian";
        return true;
    }
    if (HasAnyUserAttribute(body, "\xE6\x95\xB0\xE9\x87\x8F"))
    {
        insert.kind = DraftNoteReferenceInsert::KindAttribute;
        insert.owner = body;
        insert.title = "\xE6\x95\xB0\xE9\x87\x8F";
        return true;
    }
    return false;
}

bool PrepareDraftNoteReferenceForToken(
    const std::string& token,
    NXOpen::Part* part,
    NXOpen::Body* body,
    bool includeNumber,
    DraftNoteReferenceInsert& insert,
    std::string& fallbackText,
    bool& appendEqual)
{
    appendEqual = false;
    fallbackText.clear();

    if (token == "{\xE7\xBC\x96\xE5\x8F\xB7=}" || token == "{\xE7\xBC\x96\xE5\x8F\xB7}")
    {
        if (!includeNumber)
        {
            return false;
        }
        if (HasAnyUserAttribute(body, "bianhao"))
        {
            insert.kind = DraftNoteReferenceInsert::KindAttribute;
            insert.owner = body;
            insert.title = "bianhao";
            appendEqual = (token == "{\xE7\xBC\x96\xE5\x8F\xB7=}");
            return true;
        }
        fallbackText = ReadAttributeText(body, "bianhao");
        if (!fallbackText.empty() && token == "{\xE7\xBC\x96\xE5\x8F\xB7=}")
        {
            fallbackText += "=";
        }
        return false;
    }

    if (token == "{\xE6\x9D\x90\xE6\x96\x99}")
    {
        NXOpen::NXObject* owner = NULL;
        std::string title;
        if (FindMaterialReferenceOwner(part, body, owner, title))
        {
            insert.kind = DraftNoteReferenceInsert::KindAttribute;
            insert.owner = owner;
            insert.title = title;
            return true;
        }
        fallbackText = ReadMaterialText(part, body);
        return false;
    }

    if (token == "{\xE5\x8E\x9A\xE5\xBA\xA6}")
    {
        if (EnsureBodyThicknessAttribute(part, body))
        {
            insert.kind = DraftNoteReferenceInsert::KindAttribute;
            insert.owner = body;
            insert.title = "Z";
            return true;
        }
        fallbackText = ReadAttributeText(body, "Z");
        return false;
    }

    if (token == "{\xE6\x95\xB0\xE9\x87\x8F}")
    {
        if (FindQuantityReference(part, body, insert))
        {
            return true;
        }
        fallbackText = ReadBodyTotalQuantityText(part, body);
        if (fallbackText.empty())
        {
            fallbackText = "1";
        }
        return false;
    }

    if (token == "{\xE9\x95\x9C\xE5\x83\x8F}")
    {
        if (HasAnyUserAttribute(body, "MIRR"))
        {
            insert.kind = DraftNoteReferenceInsert::KindAttribute;
            insert.owner = body;
            insert.title = "MIRR";
            return true;
        }
        fallbackText = ReadAttributeText(body, "MIRR");
        return false;
    }

    return false;
}

bool MatchDraftNoteToken(const std::string& format, size_t index, std::string& token)
{
    const char* tokens[] = {
        "{\xE7\xBC\x96\xE5\x8F\xB7=}",
        "{\xE7\xBC\x96\xE5\x8F\xB7}",
        "{\xE6\x9D\x90\xE6\x96\x99}",
        "{\xE5\x8E\x9A\xE5\xBA\xA6}",
        "{\xE6\x95\xB0\xE9\x87\x8F}",
        "{\xE9\x95\x9C\xE5\x83\x8F}"
    };
    for (size_t i = 0; i < sizeof(tokens) / sizeof(tokens[0]); ++i)
    {
        const std::string current = tokens[i];
        if (format.compare(index, current.size(), current) == 0)
        {
            token = current;
            return true;
        }
    }
    return false;
}

void SetBodyDraftNoteTextFromConfig(
    NXOpen::Annotations::TextWithSymbolsBuilder* textBlock,
    NXOpen::Part* part,
    NXOpen::Body* body,
    bool includeNumber,
    const std::vector<NXOpen::NXString>& prefixLines)
{
    if (textBlock == NULL)
    {
        return;
    }

    std::vector<NXOpen::NXString> emptyText(1);
    emptyText[0] = "";
    textBlock->SetText(emptyText);

    std::vector<NXOpen::NXString> lines = prefixLines;
    std::vector<DraftNoteReferenceInsert> inserts;
    std::string currentLine;
    int currentLineNo = static_cast<int>(lines.size()) + 1;
    const std::string format = LoadBodyNoteFormat();

    for (size_t i = 0; i < format.size();)
    {
        if (format[i] == '\r')
        {
            ++i;
            continue;
        }
        if (format[i] == '\n')
        {
            lines.push_back(NXOpen::NXString(currentLine.c_str(), NXOpen::NXString::UTF8));
            currentLine.clear();
            ++currentLineNo;
            ++i;
            continue;
        }

        std::string token;
        if (MatchDraftNoteToken(format, i, token))
        {
            DraftNoteReferenceInsert insert;
            std::string fallback;
            bool appendEqual = false;
            const int cursorPos = Utf8CodePointCount(currentLine) + 1;
            if (PrepareDraftNoteReferenceForToken(token, part, body, includeNumber, insert, fallback, appendEqual))
            {
                insert.lineNo = currentLineNo;
                insert.cursorPos = cursorPos;
                inserts.push_back(insert);
                if (appendEqual)
                {
                    currentLine += "=";
                }
            }
            else
            {
                currentLine += fallback;
            }
            i += token.size();
            continue;
        }

        currentLine += format[i];
        ++i;
    }
    lines.push_back(NXOpen::NXString(currentLine.c_str(), NXOpen::NXString::UTF8));
    if (lines.empty())
    {
        lines.push_back("");
    }

    textBlock->SetText(lines);

    std::sort(inserts.begin(), inserts.end(), [](const DraftNoteReferenceInsert& a, const DraftNoteReferenceInsert& b) {
        if (a.lineNo != b.lineNo)
        {
            return a.lineNo > b.lineNo;
        }
        return a.cursorPos > b.cursorPos;
        });

    for (size_t i = 0; i < inserts.size(); ++i)
    {
        try
        {
            const DraftNoteReferenceInsert& insert = inserts[i];
            if (insert.kind == DraftNoteReferenceInsert::KindAttribute)
            {
                textBlock->AddAttributeReference(insert.owner, insert.title.c_str(), false, insert.lineNo, insert.cursorPos);
            }
            else
            {
                textBlock->AddExpressionReference(insert.expressionName.c_str(), "0.2", insert.lineNo, insert.cursorPos);
            }
        }
        catch (...)
        {
        }
    }
}

bool IsDraftingApplication()
{
    UfSessionGuard ufSession;
    if (ufSession.IsInitialized())
    {
        int moduleId = 0;
        if (UF_ask_application_module(&moduleId) == 0 && moduleId == UF_APP_DRAFTING)
        {
            return true;
        }
    }

    if (BODYNOT::theSession == NULL)
    {
        return false;
    }

    const char* applicationName = BODYNOT::theSession->ApplicationName().GetLocaleText();
    if (applicationName == NULL)
    {
        return false;
    }

    return strcmp(applicationName, "UG_APP_DRAFTING") == 0 ||
           strcmp(applicationName, "DRAFTING") == 0 ||
           strstr(applicationName, "DRAFTING") != NULL ||
           strstr(applicationName, "DRAFT") != NULL ||
           strstr(applicationName, "Draft") != NULL ||
           strstr(applicationName, "draft") != NULL;
}

std::string WideToUtf8(const std::wstring& value)
{
    if (value.empty())
    {
        return std::string();
    }

    int size = WideCharToMultiByte(CP_UTF8, 0, value.c_str(), static_cast<int>(value.size()), NULL, 0, NULL, NULL);
    if (size <= 0)
    {
        return std::string();
    }

    std::string result(static_cast<size_t>(size), '\0');
    WideCharToMultiByte(CP_UTF8, 0, value.c_str(), static_cast<int>(value.size()), &result[0], size, NULL, NULL);
    return result;
}

void ShowAuthorizationMessage(const std::wstring& message)
{
    (void)message;
}

bool EnsureBodyNotAuthorized()
{
    std::wstring licenseMessage;
    if (zhaofu::nxlicense::EnsureAuthorized(L"ZHIHUI.BODYNOT", L"实体标注", &licenseMessage))
    {
        return true;
    }

    ShowAuthorizationMessage(licenseMessage);
    return false;
}

bool TryGetBodyTagFromParent(tag_t parentTag, tag_t* bodyTag)
{
    if (parentTag == NULL_TAG || bodyTag == NULL)
    {
        return false;
    }

    int objectType = 0;
    int objectSubtype = 0;
    if (UF_OBJ_ask_type_and_subtype(parentTag, &objectType, &objectSubtype) != 0)
    {
        return false;
    }

    if (objectType != UF_solid_type)
    {
        return false;
    }

    if (objectSubtype == UF_solid_body_subtype)
    {
        *bodyTag = parentTag;
        return true;
    }

    if (objectSubtype == UF_solid_face_subtype)
    {
        return UF_MODL_ask_face_body(parentTag, bodyTag) == 0 && *bodyTag != NULL_TAG;
    }

    if (objectSubtype == UF_solid_edge_subtype)
    {
        return UF_MODL_ask_edge_body(parentTag, bodyTag) == 0 && *bodyTag != NULL_TAG;
    }

    return false;
}

bool TryGetBodyTagFromFeatureLocal(tag_t featureTag, tag_t* bodyTag)
{
    if (featureTag == NULL_TAG || bodyTag == NULL)
    {
        return false;
    }

    if (UF_MODL_ask_feat_body(featureTag, bodyTag) == 0 && *bodyTag != NULL_TAG)
    {
        return true;
    }

    int featureObjectCount = 0;
    tag_t* featureObjects = NULL;
    if (UF_MODL_ask_feat_object(featureTag, &featureObjectCount, &featureObjects) == 0 && featureObjects != NULL)
    {
        for (int objectIndex = 0; objectIndex < featureObjectCount; ++objectIndex)
        {
            *bodyTag = NULL_TAG;
            if (TryGetBodyTagFromParent(featureObjects[objectIndex], bodyTag))
            {
                UF_free(featureObjects);
                return true;
            }
        }
        UF_free(featureObjects);
    }

    uf_list_p_t featureFaceList = NULL;
    if (UF_MODL_ask_feat_faces(featureTag, &featureFaceList) == 0 && featureFaceList != NULL)
    {
        int faceCount = 0;
        UF_MODL_ask_list_count(featureFaceList, &faceCount);
        for (int faceIndex = 0; faceIndex < faceCount; ++faceIndex)
        {
            tag_t faceTag = NULL_TAG;
            if (UF_MODL_ask_list_item(featureFaceList, faceIndex, &faceTag) == 0 && faceTag != NULL_TAG)
            {
                *bodyTag = NULL_TAG;
                if (UF_MODL_ask_face_body(faceTag, bodyTag) == 0 && *bodyTag != NULL_TAG)
                {
                    UF_MODL_delete_list(&featureFaceList);
                    return true;
                }
            }
        }
        UF_MODL_delete_list(&featureFaceList);
    }

    return false;
}

bool TryGetBodyTagFromFeature(tag_t featureTag, tag_t* bodyTag)
{
    if (TryGetBodyTagFromFeatureLocal(featureTag, bodyTag))
    {
        return true;
    }

    int numParents = 0;
    int numChildren = 0;
    tag_t* parentFeatures = NULL;
    tag_t* childFeatures = NULL;
    if (UF_MODL_ask_feat_relatives(featureTag, &numParents, &parentFeatures, &numChildren, &childFeatures) != 0)
    {
        return false;
    }

    bool resolved = false;
    for (int parentIndex = 0; parentIndex < numParents; ++parentIndex)
    {
        if (TryGetBodyTagFromFeatureLocal(parentFeatures[parentIndex], bodyTag))
        {
            resolved = true;
            break;
        }
    }

    if (parentFeatures != NULL)
    {
        UF_free(parentFeatures);
    }
    if (childFeatures != NULL)
    {
        UF_free(childFeatures);
    }

    return resolved;
}

bool TryGetBodyTagFromCandidate(tag_t candidateTag, tag_t* bodyTag)
{
    if (bodyTag == NULL)
    {
        return false;
    }

    *bodyTag = NULL_TAG;
    if (TryGetBodyTagFromParent(candidateTag, bodyTag))
    {
        return true;
    }

    tag_t featureTag = NULL_TAG;
    if (UF_MODL_ask_object_feat(candidateTag, &featureTag) == 0 && featureTag != NULL_TAG)
    {
        if (TryGetBodyTagFromFeature(featureTag, bodyTag))
        {
            return true;
        }
    }

    int parentsCount = 0;
    tag_t* parents = NULL;
    if (UF_DRAW_ask_drafting_curve_parents(candidateTag, &parentsCount, &parents) != 0 || parents == NULL)
    {
        return false;
    }

    bool resolved = false;
    for (int parentIndex = 0; parentIndex < parentsCount; ++parentIndex)
    {
        *bodyTag = NULL_TAG;
        if (TryGetBodyTagFromParent(parents[parentIndex], bodyTag))
        {
            resolved = true;
            break;
        }

        featureTag = NULL_TAG;
        if (UF_MODL_ask_object_feat(parents[parentIndex], &featureTag) == 0 && featureTag != NULL_TAG)
        {
            if (TryGetBodyTagFromFeature(featureTag, bodyTag))
            {
                resolved = true;
                break;
            }
        }
    }
    UF_free(parents);
    return resolved;
}

double AskBodyBoxVolume(tag_t bodyTag)
{
    double box[6] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
    if (UF_MODL_ask_bounding_box(bodyTag, box) != 0)
    {
        return 0.0;
    }

    const double dx = fabs(box[3] - box[0]);
    const double dy = fabs(box[4] - box[1]);
    const double dz = fabs(box[5] - box[2]);
    const double volume = dx * dy * dz;
    return volume > 0.0 ? volume : (dx * dy + dy * dz + dx * dz);
}

NXOpen::Body* FindLargestBodyFromTags(const std::set<tag_t>& bodyTags)
{
    tag_t largestBodyTag = NULL_TAG;
    double largestVolume = -1.0;
    for (std::set<tag_t>::const_iterator it = bodyTags.begin(); it != bodyTags.end(); ++it)
    {
        const double volume = AskBodyBoxVolume(*it);
        if (volume > largestVolume)
        {
            largestVolume = volume;
            largestBodyTag = *it;
        }
    }

    return largestBodyTag == NULL_TAG ? NULL : dynamic_cast<NXOpen::Body*>(NXOpen::NXObjectManager::Get(largestBodyTag));
}

NXOpen::Body* FindLargestBodyInDraftingView(NXOpen::Drawings::DraftingView* draftingView)
{
    if (draftingView == NULL)
    {
        return NULL;
    }

    std::set<tag_t> bodyTags;
    NXOpen::Drawings::DraftingBodyCollection* bodyCollection = draftingView->DraftingBodies();
    for (NXOpen::Drawings::DraftingBodyCollection::iterator bodyIt = bodyCollection->begin();
         bodyIt != bodyCollection->end();
         ++bodyIt)
    {
        NXOpen::Drawings::DraftingBody* draftingBody = *bodyIt;
        if (draftingBody == NULL)
        {
            continue;
        }

        NXOpen::Drawings::DraftingCurveCollection* curveCollection = draftingBody->DraftingCurves();
        tag_t draftingBodyModelTag = NULL_TAG;
        for (NXOpen::Drawings::DraftingCurveCollection::iterator curveIt = curveCollection->begin();
             curveIt != curveCollection->end();
             ++curveIt)
        {
            NXOpen::Drawings::DraftingCurve* draftingCurve = *curveIt;
            if (draftingCurve == NULL)
            {
                continue;
            }

            tag_t bodyTag = NULL_TAG;
            if (TryGetBodyTagFromCandidate(draftingCurve->Tag(), &bodyTag))
            {
                draftingBodyModelTag = bodyTag;
                break;
            }
        }

        if (draftingBodyModelTag != NULL_TAG)
        {
            bodyTags.insert(draftingBodyModelTag);
        }
    }

    return FindLargestBodyFromTags(bodyTags);
}

NXOpen::Body* ResolveSelectedBody(NXOpen::TaggedObject* selectedObject)
{
    if (selectedObject == NULL)
    {
        return NULL;
    }

    NXOpen::Body* selectedBody = dynamic_cast<NXOpen::Body*>(NXOpen::NXObjectManager::Get(selectedObject->Tag()));
    if (selectedBody != NULL)
    {
        return selectedBody;
    }

    NXOpen::Drawings::DraftingView* draftingView =
        dynamic_cast<NXOpen::Drawings::DraftingView*>(NXOpen::NXObjectManager::Get(selectedObject->Tag()));
    if (draftingView != NULL)
    {
        return FindLargestBodyInDraftingView(draftingView);
    }

    return NULL;
}
}

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(BODYNOT::theSession) = NULL;
UI *(BODYNOT::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
BODYNOT::BODYNOT()
{
    try
    {
        // Initialize the NX Open C++ API environment
        BODYNOT::theSession = NXOpen::Session::GetSession();
        BODYNOT::theUI = UI::GetUI();
        workPart = theSession->Parts()->Work();
        displayPart = theSession->Parts()->Display();
        theDlxFileName = "BODYNOT.dlx";
        theDialog = BODYNOT::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &BODYNOT::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &BODYNOT::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &BODYNOT::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &BODYNOT::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &BODYNOT::dialogShown_cb));
    }
    catch(exception&)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
BODYNOT::~BODYNOT()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    BODYNOT *theBODYNOT = NULL;
    BODYNOT::theSession = NXOpen::Session::GetSession();
    BODYNOT::theUI = UI::GetUI();
    if (retcod != NULL)
    {
        *retcod = 1;
    }

    try
    {
        if (!IsDraftingApplication())
        {
            BODYNOT::theUI->NXMessageBox()->Show("运行环境", NXOpen::NXMessageBox::DialogTypeWarning, "请先切换到制图模式后再运行实体标注。");
            return;
        }

        if (!EnsureBodyNotAuthorized())
        {
            if (retcod != NULL)
            {
                *retcod = 1;
            }
            return;
        }

        theBODYNOT = new BODYNOT();
        // The following method shows the dialog immediately
        theBODYNOT->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        if (BODYNOT::theUI != NULL)
        {
            BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
        }
    }
    catch(...)
    {
        if (BODYNOT::theUI != NULL)
        {
            BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, "未处理的异常导致插件启动失败。");
        }
    }

    if(theBODYNOT != NULL)
    {
        delete theBODYNOT;
        theBODYNOT = NULL;
    }

    if (retcod != NULL)
    {
        *retcod = 0;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        if (BODYNOT::theUI != NULL)
        {
            BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
        }
    }
}

int BODYNOT::Show()
{
    try
    {
        if (!EnsureBodyNotAuthorized())
        {
            return 1;
        }

        theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void BODYNOT::initialize_cb()
{
    try
    {
        toggle0 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle0"));
        toggle01 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle01"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point0"));

        //设置过滤
        Selection::SelectionAction action = Selection::SelectionActionClearAndEnableSpecific;
        std::vector<Selection::MaskTriple> maskArray(2);
        maskArray[0] = Selection::MaskTriple(UF_solid_type, UF_solid_body_subtype, UF_UI_SEL_FEATURE_BODY); // 实体
        maskArray[1] = Selection::MaskTriple(UF_view_type, UF_all_subtype, UF_all_subtype); // 工程图视图
        PropertyList* selection0Props = selection0->GetProperties();
        selection0Props->SetSelectionFilter("SelectionFilter", action, maskArray);
        delete selection0Props;
        selection0Props = NULL;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set
//here will take precedence and dialog will be launched showing that value.
//------------------------------------------------------------------------------
void BODYNOT::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int BODYNOT::apply_cb()
{
    int errorCode = 0;
    try
    {
        DestroyDraftingNoteBuilder();
        theSession->CleanUpFacetedFacesAndEdges();
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int BODYNOT::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == toggle0)
        {
        //---------Enter your code here-----------
        }
        else if(block == selection0)
        {
            UfSessionGuard ufSession;
            if (!ufSession.IsInitialized())
            {
                BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, "UFUN 初始化失败，无法继续创建实体标注。");
                return 0;
            }

            //获取选择对象TAG_T
            PropertyList* selection0Props = selection0->GetProperties();
            std::vector<NXOpen::TaggedObject*> notbody1 = selection0Props->GetTaggedObjectVector("SelectedObjects");
            delete selection0Props;
            selection0Props = NULL;

            if (notbody1.empty())
            {
                BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, "未选择对象，请先选择实体或工程图视图。");
                return 0;
            }

            PropertyList* toggle01Props = toggle01->GetProperties();
            bool Thetoggle01 = (toggle01Props->GetLogical("Value") != 0);
            delete toggle01Props;
            toggle01Props = NULL;

            NXOpen::Body* body1 = ResolveSelectedBody(notbody1[0]);
            if (body1 == NULL)
            {
                BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, "未能从所选对象取得实体。请选择实体，或选择包含模型曲线的工程图视图。");
                return 0;
            }

            DestroyDraftingNoteBuilder();
            NXOpen::Annotations::SimpleDraftingAid* nullNXOpen_Annotations_SimpleDraftingAid(NULL);
            draftingNoteBuilder1 = workPart->Annotations()->CreateDraftingNoteBuilder(nullNXOpen_Annotations_SimpleDraftingAid);
            draftingNoteBuilder1->Origin()->Plane()->SetPlaneMethod(NXOpen::Annotations::PlaneBuilder::PlaneMethodTypeXyPlane);
            draftingNoteBuilder1->Origin()->SetAnchor(NXOpen::Annotations::OriginBuilder::AlignmentPositionMidCenter);
            draftingNoteBuilder1->Origin()->SetInferRelativeToGeometry(false);
            draftingNoteBuilder1->Style()->LetteringStyle()->SetGeneralTextColor(workPart->Colors()->Find("Emerald"));

            double x = 0.0;
            double y = 0.0;
            bool foundFlatPattern = false;
            std::vector<Features::Feature*> Feature01 = workPart->Features()->GetFeatures();
            for (size_t i = 0; i < Feature01.size(); i++)
            {
                if (strcmp(Feature01[i]->FeatureType().GetLocaleText(), "FLAT_PATTERN") == 0)
                {
                    NXOpen::Features::FlatPattern* convertToSheetmetal1 = dynamic_cast<NXOpen::Features::FlatPattern*>(NXOpen::NXObjectManager::Get(Feature01[i]->Tag()));
                    if (convertToSheetmetal1 == NULL)
                        continue;

                    NXOpen::Features::SheetMetal::FlatPatternBuilder* flatPatternBuilder1 = workPart->Features()->SheetmetalManager()->CreateFlatPatternBuilder(convertToSheetmetal1);
                    NXOpen::Face* FACE1A = flatPatternBuilder1->UpwardFace()->Value();
                    if (FACE1A != NULL)
                    {
                        std::vector<NXOpen::Face*> bodyFaces = body1->GetFaces();
                        for (size_t C = 0; C < bodyFaces.size(); C++)
                        {
                            if (bodyFaces[C]->Tag() == FACE1A->Tag())
                            {
                                x = convertToSheetmetal1->GetRealAttribute("Minimum X");
                                y = convertToSheetmetal1->GetRealAttribute("Minimum Y");
                                foundFlatPattern = true;
                                break;
                            }
                        }
                    }
                    flatPatternBuilder1->Destroy();
                    break;
                }
            }
            int Body1ID = 0;
            Body1ID = body1->GetIntegerAttribute("BodyID");
            std::vector<NXOpen::NXString> Kong(1), text11;
            Kong[0] = "";

            if (Thetoggle01)
            {
                char ExName1YY[256];
                char ExName1XX[256];




                sprintf(ExName1YY, "YY_%d", Body1ID);
                sprintf(ExName1XX, "XX_%d", Body1ID);
                std::string textX = ReadExpressionIntegerText(workPart, ExName1XX);
                std::string textY = ReadExpressionIntegerText(workPart, ExName1YY);
                if (!textX.empty() && !textY.empty())
                {
                    text11.push_back((textX + "X" + textY + " ").c_str());
                }
                else
                {
                    if (foundFlatPattern)
                    {
                        char flatSizeText[128];
                        sprintf(flatSizeText, "%.2fX%.2f ", x, y);
                        text11.push_back(flatSizeText);
                    }
                }
            }

            draftingNoteBuilder1->Style()->LetteringStyle()->SetGeneralTextLineSpaceFactor(1.5);
            //获取编号开关值
            PropertyList* toggle0Props = toggle0->GetProperties();
            bool Thetoggle0 = (toggle0Props->GetLogical("Value") != 0);
            delete toggle0Props;
            toggle0Props = NULL;
            std::vector<NXOpen::NXString> finalText;
            for (size_t textIndex = 0; textIndex < text11.size(); ++textIndex)
            {
                if (!IsEmptyText(text11[textIndex]))
                {
                    finalText.push_back(text11[textIndex]);
                }
            }
            SetBodyDraftNoteTextFromConfig(draftingNoteBuilder1->Text()->TextBlock(), workPart, body1, Thetoggle0, finalText);
        }
        else if (block == toggle01)
        {

        }
        else if(block == point0)
        {
            UfSessionGuard ufSession;
            if (!ufSession.IsInitialized())
            {
                BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, "UFUN 初始化失败，无法提交实体标注。");
                return 0;
            }
            //Get the point
            PropertyList* pointPropertyList = point0->GetProperties();
            Point3d originPoint = pointPropertyList->GetPoint("Point");
            delete pointPropertyList;
            pointPropertyList = NULL;

            NXOpen::View* nullNXOpen_View(NULL);
            if (draftingNoteBuilder1 != NULL)
            {
                draftingNoteBuilder1->Origin()->Origin()->SetValue(NULL, nullNXOpen_View, originPoint);
                NXOpen::NXObject* nXObject1 = draftingNoteBuilder1->Commit();
                DestroyDraftingNoteBuilder();
            }


        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int BODYNOT::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        BODYNOT::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* BODYNOT::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
