//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\LPOpenPrint\application\BaoLonTiFenGe.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Mechrevo
//              Version: NX 2306
//              Date: 02-02-2025  (Format: mm-dd-yyyy)
//              Time: 15:42
//
//==============================================================================

#ifndef BAOLONTIFENGE_H_INCLUDED
#define BAOLONTIFENGE_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "F:\BaiduSyncdisk\UGKaiFa(9.29)\UG_TouWenJian.h"
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesEnabled
//------------------------------------------------------------------------------
#define              SnapPointTypesEnabled_UserDefined (1 << 0);
#define                 SnapPointTypesEnabled_Inferred (1 << 1);
#define           SnapPointTypesEnabled_ScreenPosition (1 << 2);
#define                 SnapPointTypesEnabled_EndPoint (1 << 3);
#define                 SnapPointTypesEnabled_MidPoint (1 << 4);
#define             SnapPointTypesEnabled_ControlPoint (1 << 5);
#define             SnapPointTypesEnabled_Intersection (1 << 6);
#define                SnapPointTypesEnabled_ArcCenter (1 << 7);
#define            SnapPointTypesEnabled_QuadrantPoint (1 << 8);
#define            SnapPointTypesEnabled_ExistingPoint (1 << 9);
#define             SnapPointTypesEnabled_PointonCurve (1 <<10);
#define           SnapPointTypesEnabled_PointonSurface (1 <<11);
#define         SnapPointTypesEnabled_PointConstructor (1 <<12);
#define     SnapPointTypesEnabled_TwocurveIntersection (1 <<13);
#define             SnapPointTypesEnabled_TangentPoint (1 <<14);
#define                    SnapPointTypesEnabled_Poles (1 <<15);
#define         SnapPointTypesEnabled_BoundedGridPoint (1 <<16);
#define         SnapPointTypesEnabled_FacetVertexPoint (1 <<17);
#define            SnapPointTypesEnabled_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define             SnapPointTypesOnByDefault_EndPoint (1 << 3);
#define             SnapPointTypesOnByDefault_MidPoint (1 << 4);
#define         SnapPointTypesOnByDefault_ControlPoint (1 << 5);
#define         SnapPointTypesOnByDefault_Intersection (1 << 6);
#define            SnapPointTypesOnByDefault_ArcCenter (1 << 7);
#define        SnapPointTypesOnByDefault_QuadrantPoint (1 << 8);
#define        SnapPointTypesOnByDefault_ExistingPoint (1 << 9);
#define         SnapPointTypesOnByDefault_PointonCurve (1 <<10);
#define       SnapPointTypesOnByDefault_PointonSurface (1 <<11);
#define     SnapPointTypesOnByDefault_PointConstructor (1 <<12);
#define     SnapPointTypesOnByDefault_BoundedGridPoint (1 <<16);
#define     SnapPointTypesOnByDefault_FacetVertexPoint (1 <<17);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define          SnapPointTypesOnByDefault_UserDefined (1 << 0);
#define             SnapPointTypesOnByDefault_Inferred (1 << 1);
#define       SnapPointTypesOnByDefault_ScreenPosition (1 << 2);
#define SnapPointTypesOnByDefault_TwocurveIntersection (1 <<13);
#define         SnapPointTypesOnByDefault_TangentPoint (1 <<14);
#define                SnapPointTypesOnByDefault_Poles (1 <<15);
#define        SnapPointTypesOnByDefault_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
//Bit Option for Property: VisibleManipulatorHandles
//------------------------------------------------------------------------------
#define               VisibleManipulatorHandles_Origin (1 << 0);
#define           VisibleManipulatorHandles_TranslateX (1 << 1);
#define           VisibleManipulatorHandles_TranslateY (1 << 2);
#define           VisibleManipulatorHandles_TranslateZ (1 << 3);
#define              VisibleManipulatorHandles_RotateX (1 << 4);
#define              VisibleManipulatorHandles_RotateY (1 << 5);
#define              VisibleManipulatorHandles_RotateZ (1 << 6);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport BaoLonTiFenGe
{
    // class members
public:
    static Session* theSession;
    static UI* theUI;
    BaoLonTiFenGe();
    ~BaoLonTiFenGe();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();

    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the BaoLonTiFenGe.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    int filter_cb(NXOpen::BlockStyler::UIBlock* block, NXOpen::TaggedObject* selectedObject);
    PropertyList* GetBlockProperties(const char* blockID);

private:
    NXOpen::Body* GetSelectionBody(NXOpen::TaggedObject* selectedObject);
    bool IsValidSelectionObject(NXOpen::TaggedObject* selectedObject);
    std::vector<NXOpen::TaggedObject*> FilterObjectsOnSelectionBody(const std::vector<NXOpen::TaggedObject*>& selectedObjects);
    void SetSelectionObjects(const std::vector<NXOpen::TaggedObject*>& selectedObjects);

    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;
    NXOpen::BlockStyler::SelectObject* selection0;// Block type: Selection
    NXOpen::BlockStyler::SpecifyOrientation* manip0;// Block type: Specify Orientation
    NXOpen::BlockStyler::LinearDimension* linear_dim_x;// Block type: Linear Dim
    NXOpen::BlockStyler::LinearDimension* linear_dim_x1;// Block type: Linear Dim
    NXOpen::BlockStyler::LinearDimension* linear_dim_y;// Block type: Linear Dim
    NXOpen::BlockStyler::LinearDimension* linear_dim_y1;// Block type: Linear Dim
    NXOpen::BlockStyler::LinearDimension* linear_dim_z;// Block type: Linear Dim
    NXOpen::BlockStyler::LinearDimension* linear_dim_z1;// Block type: Linear Dim
    NXOpen::Body* selectionBody;
    bool isUpdatingSelection;

};
#endif //BAOLONTIFENGE_H_INCLUDED
